apiVersion: apps/v1
kind: Deployment
metadata:
  name: aisom-gw
  namespace: aisom
  labels:
    app: aisom-gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aisom-gw
  template:
    metadata:
      labels:
        app: aisom-gw
    spec:
      nodeSelector:
        kubernetes.io/hostname: klynx-poc-01
      containers:
        - name: aisom-gw
          image: regis.pointit.co.th/infra/go:1.1.6
          imagePullPolicy: IfNotPresent
          workingDir: /app
          command: ["sleep", "infinity"]
          env:
            - name: MASTER_KEYRING_JSON
              valueFrom:
                secretKeyRef:
                  name: klynx-masterkey
                  key: MASTER_KEYRING_JSON
          ports:
            - name: http
              containerPort: 3001
          volumeMounts:
            - name: src-code
              mountPath: /app
            - name: rootca-volume
              mountPath: /app/certs/tls.ca
              subPath: tls.ca
              readOnly: true
          securityContext:
            privileged: true
      volumes:
        - name: src-code
          hostPath:
            path: /home/aisom/gateway-api
            type: Directory
        - name: rootca-volume
          configMap:
            name: rootca
            items:
              - key: ca.crt
                path: tls.ca
---
apiVersion: v1
kind: Service
metadata:
  name: aisom-gw
  namespace: aisom
spec:
  selector:
    app: aisom-gw
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
