apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapi
  namespace: aliza
  labels:
    app: kapi
spec:
  selector:
    matchLabels:
      app: kapi
  template:
    metadata:
      labels:
        app: kapi
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: k8sserver3
      containers:
        - name: kapi
          image: regis.pointit.co.th/infra/go:1.1.6
          # command: ["sleep"]
          # args: ["infinity"]
          # command: ["go", "run", ".", "--env=prod"]
          # command: ["./main", "--env=prod"]
          imagePullPolicy: IfNotPresent
          env:
            - name: MASTER_KEYRING_JSON
              valueFrom:
                secretKeyRef:
                  name: klynx-masterkey
                  key: MASTER_KEYRING_JSON
          envFrom:
            - configMapRef:
                name: kapi-config
            - secretRef:
                name: kapi-secrets
          ports:
            - name: http
              containerPort: 3001
          volumeMounts:
            # - name: src-code
            #   mountPath: /app
            - name: rootca-volume
              mountPath: /app/certs/tls.ca
              subPath: tls.ca
              readOnly: true
          securityContext:
            privileged: true
      volumes:
        # - name: src-code
        #   hostPath:
        #     path: /home/klynx/klynx-api
        #     type: Directory
        - name: rootca-volume
          configMap:
            name: rootca
            items:
              - key: ca.crt
                path: tls.ca
---
apiVersion: v1
kind: Service
metadata:
  name: kapi
  namespace: aliza
spec:
  selector:
    app: kapi
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
  type: ClusterIP
