# ใช้ golang image จาก docker hub
FROM docker.io/library/golang:1.24

WORKDIR /app
USER root

ENV GOPROXY=direct

# ติดตั้ง air สำหรับ live reload
RUN go install github.com/air-verse/air@latest

# ติดตั้งโปรเจกต์
COPY go.mod go.sum ./
RUN go mod tidy
COPY . .

EXPOSE 3001

# ✅ เพิ่ม limit ของ file descriptors ก่อนรัน air
CMD ["/bin/sh", "-c", "ulimit -n 65535"]
