// cmd/license.go
package main

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/hotkhwan/gateway-api/config"
	"github.com/hotkhwan/gateway-api/internal/logger"
	"github.com/hotkhwan/gateway-api/internal/repo/subscriprepo"
	"github.com/hotkhwan/gateway-api/models/subscripmod"
	"github.com/joho/godotenv"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

const (
	licenseKeyFormat = "XXXX-YYYY-ZZZZ-WWWW"
)

// GenerateLicenseKey generates a unique license key in format XXXX-YYYY-ZZZZ-WWWW
func GenerateLicenseKey(secretKey string) (string, error) {
	// Generate 16 random bytes
	bytes := make([]byte, 16)
	if _, err := rand.Read(bytes); err != nil {
		return "", fmt.Errorf("failed to generate random bytes: %w", err)
	}

	// Sign with HMAC for authenticity (ensures key was generated by this system)
	h := hmac.New(sha256.New, []byte(secretKey))
	h.Write(bytes)
	signature := hex.EncodeToString(h.Sum(nil))

	// Combine: 8 random chars + 8 signature chars = 16 chars
	combined := hex.EncodeToString(bytes)[:8] + signature[:8]

	// Format as XXXX-YYYY-ZZZZ-WWWW
	segments := []string{
		combined[0:4],
		combined[4:8],
		combined[8:12],
		combined[12:16],
	}

	return strings.ToUpper(strings.Join(segments, "-")), nil
}

// ValidateLicenseKeyFormat validates the license key format
func ValidateLicenseKeyFormat(key string) bool {
	parts := strings.Split(key, "-")
	if len(parts) != 4 {
		return false
	}
	for _, part := range parts {
		if len(part) != 4 {
			return false
		}
		for _, c := range part {
			if !((c >= 'A' && c <= 'F') || (c >= '0' && c <= '9')) {
				return false
			}
		}
	}
	return true
}

// CreateEnterpriseLicense creates a new enterprise license
func CreateEnterpriseLicense(
	ctx context.Context,
	licenseRepo *subscriprepo.LicenseRepo,
	secretKey string,
	limits *subscripmod.SubscriptionLimits,
	notes *string,
) (*subscripmod.LicenseKey, error) {
	// Generate license key
	key, err := GenerateLicenseKey(secretKey)
	if err != nil {
		return nil, fmt.Errorf("failed to generate license key: %w", err)
	}

	// Create license record
	license := &subscripmod.LicenseKey{
		ID:        primitive.NewObjectID(),
		Key:       key,
		PlanId:    "enterprise",
		Limits:    limits,
		Status:    subscripmod.LicenseStatusAvailable,
		CreatedAt: time.Now().UTC(),
		Notes:     notes,
	}

	// Save to database
	if err := licenseRepo.Create(ctx, license); err != nil {
		return nil, fmt.Errorf("failed to save license to database: %w", err)
	}

	return license, nil
}

func main() {
	// Parse flags
	env := flag.String("env", "dev", "Environment: dev / uat / prod")
	action := flag.String("action", "generate", "Action: generate / list / validate / count")
	licenseKey := flag.String("key", "", "License key to validate (for validate action)")
	notes := flag.String("notes", "", "Optional notes for the license (for generate action)")
	flag.Parse()

	// Load env file
	envFile := fmt.Sprintf(".env.%s", *env)
	if err := godotenv.Load(envFile); err != nil {
		fmt.Printf("❌ Failed to load env file: %s\n", err)
		os.Exit(1)
	}

	// Check ALLOW_CMD_LIC
	allowCmdLic := strings.ToLower(os.Getenv("ALLOW_CMD_LIC")) == "true"
	if !allowCmdLic {
		fmt.Println("❌ License CLI tool is disabled. Set ALLOW_CMD_LIC=true in your .env file to enable.")
		fmt.Println("\nExample: Add 'ALLOW_CMD_LIC=true' to your .env.dev file")
		os.Exit(1)
	}

	// Check Enterprise Subscription (required for license key generation)
	licenseSecretKey := os.Getenv("LIC_SEC_KEY")
	if licenseSecretKey == "" {
		fmt.Println("❌ Enterprise environment variable is required to generate license keys.")
		fmt.Println("This enterprise subscription is used to sign license keys for security verification.")
		os.Exit(1)
	}

	// Initialize logger and MongoDB connection
	logger.Init()
	config.InitMongo()
	log := logger.Boot("license-cli", "main")

	ctx := context.Background()
	licenseRepo := subscriprepo.NewLicenseRepo(config.DB)

	log.Info().Msg("🔑 License Key Management Tool")

	switch *action {
	case "generate":
		// Generate new license key
		license, err := CreateEnterpriseLicense(ctx, licenseRepo, licenseSecretKey, nil, func(s string) *string { return &s }(*notes))
		if err != nil {
			log.Fatal().Err(err).Msg("Failed to create license")
		}

		fmt.Println("\n✅ License Key Generated Successfully!")
		fmt.Println("=====================================")
		fmt.Printf("License Key:  %s\n", license.Key)
		fmt.Printf("Plan:         %s\n", license.PlanId)
		fmt.Printf("Status:       %s\n", license.Status)
		fmt.Printf("Created At:    %s\n", license.CreatedAt.Format(time.RFC3339))
		if license.Notes != nil {
			fmt.Printf("Notes:        %s\n", *license.Notes)
		}
		fmt.Println("\n📝 Use this key to activate enterprise plan:")
		fmt.Printf("   curl -X POST 'https://your-api.com/api/v1/subscriptions/enterprise/activate' \\\n")
		fmt.Printf("        -H 'Authorization: Bearer YOUR_TOKEN' \\\n")
		fmt.Printf("        -H 'X-Tenant-Id: YOUR_TENANT_ID' \\\n")
		fmt.Printf("        -H 'Content-Type: application/json' \\\n")
		fmt.Printf("        -d '{\"licenseKey\": \"%s\"}'\n", license.Key)

	case "list":
		// List all license keys
		licenses, err := licenseRepo.List(ctx, bson.M{})
		if err != nil {
			log.Fatal().Err(err).Msg("Failed to list licenses")
		}

		fmt.Printf("\n📋 License Keys (Total: %d)\n", len(licenses))
		fmt.Println("=====================================")
		for i, lic := range licenses {
			fmt.Printf("\n[%d] Key: %s\n", i+1, lic.Key)
			fmt.Printf("    Status: %s\n", lic.Status)
			fmt.Printf("    Plan: %s\n", lic.PlanId)
			fmt.Printf("    Created: %s\n", lic.CreatedAt.Format(time.RFC3339))
			if lic.TenantId != nil {
				fmt.Printf("    Activated by: %s\n", *lic.TenantId)
				if lic.ActivatedAt != nil {
					fmt.Printf("    Activated at: %s\n", lic.ActivatedAt.Format(time.RFC3339))
				}
			}
			if lic.Notes != nil {
				fmt.Printf("    Notes: %s\n", *lic.Notes)
			}
		}

	case "validate":
		// Validate a license key
		if *licenseKey == "" {
			fmt.Println("❌ Please provide a license key using -key flag")
			fmt.Println("   Example: go run cmd/license.go -action=validate -key=XXXX-YYYY-ZZZZ-WWWW")
			os.Exit(1)
		}

		if !ValidateLicenseKeyFormat(*licenseKey) {
			fmt.Printf("❌ Invalid license key format. Expected format: %s\n", licenseKeyFormat)
			os.Exit(1)
		}

		license, err := licenseRepo.ValidateLicenseKey(ctx, *licenseKey)
		if err != nil {
			switch {
			case errors.Is(err, subscriprepo.ErrLicenseNotFound):
				fmt.Println("❌ License key not found in database")
			case errors.Is(err, subscriprepo.ErrLicenseAlreadyActivated):
				fmt.Println("⚠️  License key has already been activated")
			case errors.Is(err, subscriprepo.ErrLicenseRevoked):
				fmt.Println("⚠️  License key has been revoked")
			default:
				fmt.Printf("❌ Validation error: %s\n", err.Error())
			}
			os.Exit(1)
		}

		fmt.Println("✅ License key is valid and available for activation!")
		fmt.Printf("   Key: %s\n", license.Key)
		fmt.Printf("   Status: %s\n", license.Status)
		fmt.Printf("   Created: %s\n", license.CreatedAt.Format(time.RFC3339))

	case "count":
		// Count licenses by status
		for _, status := range []subscripmod.LicenseStatus{
			subscripmod.LicenseStatusAvailable,
			subscripmod.LicenseStatusActivated,
			subscripmod.LicenseStatusRevoked,
		} {
			count, err := licenseRepo.CountByStatus(ctx, status)
			if err != nil {
				log.Error().Err(err).Msgf("Failed to count %s licenses", status)
				continue
			}
			fmt.Printf("   %-12s: %d\n", status, count)
		}

	default:
		fmt.Println("❌ Invalid action. Valid actions: generate, list, validate, count")
		fmt.Println("\nUsage:")
		fmt.Println("  Generate license:")
		fmt.Println("    go run cmd/license.go -action=generate [-notes=\"Customer X\"]")
		fmt.Println("  List all licenses:")
		fmt.Println("    go run cmd/license.go -action=list")
		fmt.Println("  Validate license key:")
		fmt.Println("    go run cmd/license.go -action=validate -key=XXXX-YYYY-ZZZZ-WWWW")
		fmt.Println("  Count licenses by status:")
		fmt.Println("    go run cmd/license.go -action=count")
		fmt.Println("\nDon't forget to set ALLOW_CMD_LIC=true in your .env file!")
		os.Exit(1)
	}
}
