# # ใช้ golang image จาก docker hub
# FROM docker.io/library/golang:1.24

# WORKDIR /app
# USER root

# ENV GOPROXY=direct

# # ติดตั้ง air สำหรับ live reload
# RUN go install github.com/air-verse/air@latest

# # ติดตั้งโปรเจกต์
# COPY go.mod go.sum ./
# RUN go mod tidy
# COPY . .

# EXPOSE 3001

# # ✅ เพิ่ม limit ของ file descriptors ก่อนรัน air
# CMD ["/bin/sh", "-c", "ulimit -n 65535"]

# ----- Build Stage -----
FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o main .

# ----- Runtime Stage -----
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/main .
COPY .env.dev .env.dev

EXPOSE 3000

# Run with default env flag (can be overridden at runtime)
CMD ["./main", "--env=dev"]
