// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: ACCelerometer_data.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HisACCelerometer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp    *DateTime `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	AccDataCount *uint32   `protobuf:"fixed32,2,req,name=acc_data_count,json=accDataCount" json:"acc_data_count,omitempty"`
	AccX         []byte    `protobuf:"bytes,3,req,name=acc_x,json=accX" json:"acc_x,omitempty"`
	AccY         []byte    `protobuf:"bytes,4,req,name=acc_y,json=accY" json:"acc_y,omitempty"`
	AccZ         []byte    `protobuf:"bytes,5,req,name=acc_z,json=accZ" json:"acc_z,omitempty"`
}

func (x *HisACCelerometer) Reset() {
	*x = HisACCelerometer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ACCelerometer_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisACCelerometer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisACCelerometer) ProtoMessage() {}

func (x *HisACCelerometer) ProtoReflect() protoreflect.Message {
	mi := &file_ACCelerometer_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisACCelerometer.ProtoReflect.Descriptor instead.
func (*HisACCelerometer) Descriptor() ([]byte, []int) {
	return file_ACCelerometer_data_proto_rawDescGZIP(), []int{0}
}

func (x *HisACCelerometer) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *HisACCelerometer) GetAccDataCount() uint32 {
	if x != nil && x.AccDataCount != nil {
		return *x.AccDataCount
	}
	return 0
}

func (x *HisACCelerometer) GetAccX() []byte {
	if x != nil {
		return x.AccX
	}
	return nil
}

func (x *HisACCelerometer) GetAccY() []byte {
	if x != nil {
		return x.AccY
	}
	return nil
}

func (x *HisACCelerometer) GetAccZ() []byte {
	if x != nil {
		return x.AccZ
	}
	return nil
}

var File_ACCelerometer_data_proto protoreflect.FileDescriptor

var file_ACCelerometer_data_proto_rawDesc = []byte{
	0x0a, 0x18, 0x41, 0x43, 0x43, 0x65, 0x6c, 0x65, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x72, 0x65, 0x61, 0x6c,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa1, 0x01, 0x0a, 0x10, 0x48, 0x69, 0x73, 0x41, 0x43, 0x43, 0x65, 0x6c, 0x65, 0x72, 0x6f, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x24,
	0x0a, 0x0e, 0x61, 0x63, 0x63, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x44, 0x61, 0x74, 0x61, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x61, 0x63, 0x63, 0x5f, 0x78, 0x18, 0x03, 0x20,
	0x02, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x63, 0x63, 0x58, 0x12, 0x13, 0x0a, 0x05, 0x61, 0x63, 0x63,
	0x5f, 0x79, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x63, 0x63, 0x59, 0x12, 0x13,
	0x0a, 0x05, 0x61, 0x63, 0x63, 0x5f, 0x7a, 0x18, 0x05, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x61,
	0x63, 0x63, 0x5a, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x69, 0x77, 0x6f, 0x77, 0x6e,
}

var (
	file_ACCelerometer_data_proto_rawDescOnce sync.Once
	file_ACCelerometer_data_proto_rawDescData = file_ACCelerometer_data_proto_rawDesc
)

func file_ACCelerometer_data_proto_rawDescGZIP() []byte {
	file_ACCelerometer_data_proto_rawDescOnce.Do(func() {
		file_ACCelerometer_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_ACCelerometer_data_proto_rawDescData)
	})
	return file_ACCelerometer_data_proto_rawDescData
}

var file_ACCelerometer_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ACCelerometer_data_proto_goTypes = []interface{}{
	(*HisACCelerometer)(nil), // 0: HisACCelerometer
	(*DateTime)(nil),         // 1: DateTime
}
var file_ACCelerometer_data_proto_depIdxs = []int32{
	1, // 0: HisACCelerometer.time_stamp:type_name -> DateTime
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ACCelerometer_data_proto_init() }
func file_ACCelerometer_data_proto_init() {
	if File_ACCelerometer_data_proto != nil {
		return
	}
	file_realtime_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ACCelerometer_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisACCelerometer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ACCelerometer_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ACCelerometer_data_proto_goTypes,
		DependencyIndexes: file_ACCelerometer_data_proto_depIdxs,
		MessageInfos:      file_ACCelerometer_data_proto_msgTypes,
	}.Build()
	File_ACCelerometer_data_proto = out.File
	file_ACCelerometer_data_proto_rawDesc = nil
	file_ACCelerometer_data_proto_goTypes = nil
	file_ACCelerometer_data_proto_depIdxs = nil
}
