// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: Alarm_info.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SOSGNSSINFOV3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp *DateTime `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	Longitude *float32  `protobuf:"fixed32,2,req,name=longitude" json:"longitude,omitempty"`
	Latitude  *float32  `protobuf:"fixed32,3,req,name=latitude" json:"latitude,omitempty"`
	GpsType   *GPSTYPE  `protobuf:"varint,4,req,name=gps_type,json=gpsType,enum=GPSTYPE" json:"gps_type,omitempty"`
}

func (x *SOSGNSSINFOV3) Reset() {
	*x = SOSGNSSINFOV3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Alarm_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SOSGNSSINFOV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SOSGNSSINFOV3) ProtoMessage() {}

func (x *SOSGNSSINFOV3) ProtoReflect() protoreflect.Message {
	mi := &file_Alarm_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SOSGNSSINFOV3.ProtoReflect.Descriptor instead.
func (*SOSGNSSINFOV3) Descriptor() ([]byte, []int) {
	return file_Alarm_info_proto_rawDescGZIP(), []int{0}
}

func (x *SOSGNSSINFOV3) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *SOSGNSSINFOV3) GetLongitude() float32 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *SOSGNSSINFOV3) GetLatitude() float32 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *SOSGNSSINFOV3) GetGpsType() GPSTYPE {
	if x != nil && x.GpsType != nil {
		return *x.GpsType
	}
	return GPSTYPE_NULL
}

type HrAlarmV3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp *DateTime `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	Hr        *uint32   `protobuf:"fixed32,2,req,name=hr" json:"hr,omitempty"`
}

func (x *HrAlarmV3) Reset() {
	*x = HrAlarmV3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Alarm_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HrAlarmV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HrAlarmV3) ProtoMessage() {}

func (x *HrAlarmV3) ProtoReflect() protoreflect.Message {
	mi := &file_Alarm_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HrAlarmV3.ProtoReflect.Descriptor instead.
func (*HrAlarmV3) Descriptor() ([]byte, []int) {
	return file_Alarm_info_proto_rawDescGZIP(), []int{1}
}

func (x *HrAlarmV3) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *HrAlarmV3) GetHr() uint32 {
	if x != nil && x.Hr != nil {
		return *x.Hr
	}
	return 0
}

type Spo2AlarmV3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp *DateTime `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	Spo2      *uint32   `protobuf:"fixed32,2,req,name=spo2" json:"spo2,omitempty"`
}

func (x *Spo2AlarmV3) Reset() {
	*x = Spo2AlarmV3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Alarm_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spo2AlarmV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spo2AlarmV3) ProtoMessage() {}

func (x *Spo2AlarmV3) ProtoReflect() protoreflect.Message {
	mi := &file_Alarm_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spo2AlarmV3.ProtoReflect.Descriptor instead.
func (*Spo2AlarmV3) Descriptor() ([]byte, []int) {
	return file_Alarm_info_proto_rawDescGZIP(), []int{2}
}

func (x *Spo2AlarmV3) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *Spo2AlarmV3) GetSpo2() uint32 {
	if x != nil && x.Spo2 != nil {
		return *x.Spo2
	}
	return 0
}

type ThrombusAlarmV3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp     *DateTime `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	ThrombusAlarm *bool     `protobuf:"varint,2,req,name=Thrombus_alarm,json=ThrombusAlarm" json:"Thrombus_alarm,omitempty"`
}

func (x *ThrombusAlarmV3) Reset() {
	*x = ThrombusAlarmV3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Alarm_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThrombusAlarmV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrombusAlarmV3) ProtoMessage() {}

func (x *ThrombusAlarmV3) ProtoReflect() protoreflect.Message {
	mi := &file_Alarm_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrombusAlarmV3.ProtoReflect.Descriptor instead.
func (*ThrombusAlarmV3) Descriptor() ([]byte, []int) {
	return file_Alarm_info_proto_rawDescGZIP(), []int{3}
}

func (x *ThrombusAlarmV3) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *ThrombusAlarmV3) GetThrombusAlarm() bool {
	if x != nil && x.ThrombusAlarm != nil {
		return *x.ThrombusAlarm
	}
	return false
}

type FallAlarmConfV3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp *DateTime `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	FallAlarm *bool     `protobuf:"varint,2,req,name=fall_alarm,json=fallAlarm" json:"fall_alarm,omitempty"`
}

func (x *FallAlarmConfV3) Reset() {
	*x = FallAlarmConfV3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Alarm_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FallAlarmConfV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FallAlarmConfV3) ProtoMessage() {}

func (x *FallAlarmConfV3) ProtoReflect() protoreflect.Message {
	mi := &file_Alarm_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FallAlarmConfV3.ProtoReflect.Descriptor instead.
func (*FallAlarmConfV3) Descriptor() ([]byte, []int) {
	return file_Alarm_info_proto_rawDescGZIP(), []int{4}
}

func (x *FallAlarmConfV3) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *FallAlarmConfV3) GetFallAlarm() bool {
	if x != nil && x.FallAlarm != nil {
		return *x.FallAlarm
	}
	return false
}

type TemperatureConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp   *DateTime `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	Temperature *uint32   `protobuf:"fixed32,2,req,name=temperature" json:"temperature,omitempty"`
}

func (x *TemperatureConf) Reset() {
	*x = TemperatureConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Alarm_info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemperatureConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureConf) ProtoMessage() {}

func (x *TemperatureConf) ProtoReflect() protoreflect.Message {
	mi := &file_Alarm_info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperatureConf.ProtoReflect.Descriptor instead.
func (*TemperatureConf) Descriptor() ([]byte, []int) {
	return file_Alarm_info_proto_rawDescGZIP(), []int{5}
}

func (x *TemperatureConf) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *TemperatureConf) GetTemperature() uint32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

type BpConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp *DateTime `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	Sbp       *uint32   `protobuf:"fixed32,2,req,name=sbp" json:"sbp,omitempty"`
	Dbp       *uint32   `protobuf:"fixed32,3,req,name=dbp" json:"dbp,omitempty"`
}

func (x *BpConf) Reset() {
	*x = BpConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Alarm_info_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BpConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BpConf) ProtoMessage() {}

func (x *BpConf) ProtoReflect() protoreflect.Message {
	mi := &file_Alarm_info_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BpConf.ProtoReflect.Descriptor instead.
func (*BpConf) Descriptor() ([]byte, []int) {
	return file_Alarm_info_proto_rawDescGZIP(), []int{6}
}

func (x *BpConf) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *BpConf) GetSbp() uint32 {
	if x != nil && x.Sbp != nil {
		return *x.Sbp
	}
	return 0
}

func (x *BpConf) GetDbp() uint32 {
	if x != nil && x.Dbp != nil {
		return *x.Dbp
	}
	return 0
}

type SedentaryConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp *DateTime `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
}

func (x *SedentaryConf) Reset() {
	*x = SedentaryConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Alarm_info_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SedentaryConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SedentaryConf) ProtoMessage() {}

func (x *SedentaryConf) ProtoReflect() protoreflect.Message {
	mi := &file_Alarm_info_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SedentaryConf.ProtoReflect.Descriptor instead.
func (*SedentaryConf) Descriptor() ([]byte, []int) {
	return file_Alarm_info_proto_rawDescGZIP(), []int{7}
}

func (x *SedentaryConf) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

type BloodSugar_Conf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp  *DateTime `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	BloodSugar *float32  `protobuf:"fixed32,2,req,name=Blood_sugar,json=BloodSugar" json:"Blood_sugar,omitempty"`
}

func (x *BloodSugar_Conf) Reset() {
	*x = BloodSugar_Conf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Alarm_info_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BloodSugar_Conf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloodSugar_Conf) ProtoMessage() {}

func (x *BloodSugar_Conf) ProtoReflect() protoreflect.Message {
	mi := &file_Alarm_info_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloodSugar_Conf.ProtoReflect.Descriptor instead.
func (*BloodSugar_Conf) Descriptor() ([]byte, []int) {
	return file_Alarm_info_proto_rawDescGZIP(), []int{8}
}

func (x *BloodSugar_Conf) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *BloodSugar_Conf) GetBloodSugar() float32 {
	if x != nil && x.BloodSugar != nil {
		return *x.BloodSugar
	}
	return 0
}

type BloodPotassium_Conf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp      *DateTime `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	BloodPotassium *float32  `protobuf:"fixed32,2,req,name=Blood_potassium,json=BloodPotassium" json:"Blood_potassium,omitempty"`
}

func (x *BloodPotassium_Conf) Reset() {
	*x = BloodPotassium_Conf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Alarm_info_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BloodPotassium_Conf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloodPotassium_Conf) ProtoMessage() {}

func (x *BloodPotassium_Conf) ProtoReflect() protoreflect.Message {
	mi := &file_Alarm_info_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloodPotassium_Conf.ProtoReflect.Descriptor instead.
func (*BloodPotassium_Conf) Descriptor() ([]byte, []int) {
	return file_Alarm_info_proto_rawDescGZIP(), []int{9}
}

func (x *BloodPotassium_Conf) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *BloodPotassium_Conf) GetBloodPotassium() float32 {
	if x != nil && x.BloodPotassium != nil {
		return *x.BloodPotassium
	}
	return 0
}

type AlarminfoV3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp          *DateTime `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	Wearstate          *bool     `protobuf:"varint,2,opt,name=wearstate" json:"wearstate,omitempty"`                                   //Not wearing status information warning report
	Sleepstate         *bool     `protobuf:"varint,3,opt,name=sleepstate" json:"sleepstate,omitempty"`                                 //sleep status information warning report
	LowpowerPercentage *uint32   `protobuf:"fixed32,4,opt,name=lowpowerPercentage" json:"lowpowerPercentage,omitempty"`                //Low battery warning information reporting
	PoweroffPercentage *uint32   `protobuf:"fixed32,5,opt,name=poweroffPercentage" json:"poweroffPercentage,omitempty"`                //Report shutdown information
	InterceptNumber    *string   `protobuf:"bytes,6,opt,name=intercept_number,json=interceptNumber" json:"intercept_number,omitempty"` //Unknown number blocking
}

func (x *AlarminfoV3) Reset() {
	*x = AlarminfoV3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Alarm_info_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlarminfoV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarminfoV3) ProtoMessage() {}

func (x *AlarminfoV3) ProtoReflect() protoreflect.Message {
	mi := &file_Alarm_info_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarminfoV3.ProtoReflect.Descriptor instead.
func (*AlarminfoV3) Descriptor() ([]byte, []int) {
	return file_Alarm_info_proto_rawDescGZIP(), []int{10}
}

func (x *AlarminfoV3) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *AlarminfoV3) GetWearstate() bool {
	if x != nil && x.Wearstate != nil {
		return *x.Wearstate
	}
	return false
}

func (x *AlarminfoV3) GetSleepstate() bool {
	if x != nil && x.Sleepstate != nil {
		return *x.Sleepstate
	}
	return false
}

func (x *AlarminfoV3) GetLowpowerPercentage() uint32 {
	if x != nil && x.LowpowerPercentage != nil {
		return *x.LowpowerPercentage
	}
	return 0
}

func (x *AlarminfoV3) GetPoweroffPercentage() uint32 {
	if x != nil && x.PoweroffPercentage != nil {
		return *x.PoweroffPercentage
	}
	return 0
}

func (x *AlarminfoV3) GetInterceptNumber() string {
	if x != nil && x.InterceptNumber != nil {
		return *x.InterceptNumber
	}
	return ""
}

type HealthAlarmV3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlarmHr              []*HrAlarmV3           `protobuf:"bytes,1,rep,name=alarm_hr,json=alarmHr" json:"alarm_hr,omitempty"`
	AlarmSpo2            []*Spo2AlarmV3         `protobuf:"bytes,2,rep,name=alarm_spo2,json=alarmSpo2" json:"alarm_spo2,omitempty"`
	Alarm_Thrombus       []*ThrombusAlarmV3     `protobuf:"bytes,3,rep,name=alarm_Thrombus,json=alarmThrombus" json:"alarm_Thrombus,omitempty"`
	AlarmFall            []*FallAlarmConfV3     `protobuf:"bytes,4,rep,name=alarm_fall,json=alarmFall" json:"alarm_fall,omitempty"`
	Alarm_Temperature    []*TemperatureConf     `protobuf:"bytes,5,rep,name=alarm_Temperature,json=alarmTemperature" json:"alarm_Temperature,omitempty"`
	Alarm_Bp             []*BpConf              `protobuf:"bytes,6,rep,name=alarm_Bp,json=alarmBp" json:"alarm_Bp,omitempty"`
	Gnssinfo             []*SOSGNSSINFOV3       `protobuf:"bytes,7,rep,name=gnssinfo" json:"gnssinfo,omitempty"` //SOS warning information reporting
	Alarm_Sedentary      []*SedentaryConf       `protobuf:"bytes,8,rep,name=alarm_Sedentary,json=alarmSedentary" json:"alarm_Sedentary,omitempty"`
	SOS_NotificationTime *DateTime              `protobuf:"bytes,9,opt,name=SOS_Notification_time,json=SOSNotificationTime" json:"SOS_Notification_time,omitempty"`
	Alarm_BloodSugar     []*BloodSugar_Conf     `protobuf:"bytes,10,rep,name=alarm_Blood_sugar,json=alarmBloodSugar" json:"alarm_Blood_sugar,omitempty"`
	Alarm_BloodPotassium []*BloodPotassium_Conf `protobuf:"bytes,11,rep,name=alarm_Blood_potassium,json=alarmBloodPotassium" json:"alarm_Blood_potassium,omitempty"`
}

func (x *HealthAlarmV3) Reset() {
	*x = HealthAlarmV3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Alarm_info_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthAlarmV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthAlarmV3) ProtoMessage() {}

func (x *HealthAlarmV3) ProtoReflect() protoreflect.Message {
	mi := &file_Alarm_info_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthAlarmV3.ProtoReflect.Descriptor instead.
func (*HealthAlarmV3) Descriptor() ([]byte, []int) {
	return file_Alarm_info_proto_rawDescGZIP(), []int{11}
}

func (x *HealthAlarmV3) GetAlarmHr() []*HrAlarmV3 {
	if x != nil {
		return x.AlarmHr
	}
	return nil
}

func (x *HealthAlarmV3) GetAlarmSpo2() []*Spo2AlarmV3 {
	if x != nil {
		return x.AlarmSpo2
	}
	return nil
}

func (x *HealthAlarmV3) GetAlarm_Thrombus() []*ThrombusAlarmV3 {
	if x != nil {
		return x.Alarm_Thrombus
	}
	return nil
}

func (x *HealthAlarmV3) GetAlarmFall() []*FallAlarmConfV3 {
	if x != nil {
		return x.AlarmFall
	}
	return nil
}

func (x *HealthAlarmV3) GetAlarm_Temperature() []*TemperatureConf {
	if x != nil {
		return x.Alarm_Temperature
	}
	return nil
}

func (x *HealthAlarmV3) GetAlarm_Bp() []*BpConf {
	if x != nil {
		return x.Alarm_Bp
	}
	return nil
}

func (x *HealthAlarmV3) GetGnssinfo() []*SOSGNSSINFOV3 {
	if x != nil {
		return x.Gnssinfo
	}
	return nil
}

func (x *HealthAlarmV3) GetAlarm_Sedentary() []*SedentaryConf {
	if x != nil {
		return x.Alarm_Sedentary
	}
	return nil
}

func (x *HealthAlarmV3) GetSOS_NotificationTime() *DateTime {
	if x != nil {
		return x.SOS_NotificationTime
	}
	return nil
}

func (x *HealthAlarmV3) GetAlarm_BloodSugar() []*BloodSugar_Conf {
	if x != nil {
		return x.Alarm_BloodSugar
	}
	return nil
}

func (x *HealthAlarmV3) GetAlarm_BloodPotassium() []*BloodPotassium_Conf {
	if x != nil {
		return x.Alarm_BloodPotassium
	}
	return nil
}

type AlarmInfokConfirm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alarminfo *AlarminfoV3   `protobuf:"bytes,1,opt,name=Alarminfo" json:"Alarminfo,omitempty"`
	Alarm     *HealthAlarmV3 `protobuf:"bytes,2,opt,name=alarm" json:"alarm,omitempty"`
}

func (x *AlarmInfokConfirm) Reset() {
	*x = AlarmInfokConfirm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Alarm_info_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlarmInfokConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmInfokConfirm) ProtoMessage() {}

func (x *AlarmInfokConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_Alarm_info_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmInfokConfirm.ProtoReflect.Descriptor instead.
func (*AlarmInfokConfirm) Descriptor() ([]byte, []int) {
	return file_Alarm_info_proto_rawDescGZIP(), []int{12}
}

func (x *AlarmInfokConfirm) GetAlarminfo() *AlarminfoV3 {
	if x != nil {
		return x.Alarminfo
	}
	return nil
}

func (x *AlarmInfokConfirm) GetAlarm() *HealthAlarmV3 {
	if x != nil {
		return x.Alarm
	}
	return nil
}

var File_Alarm_info_proto protoreflect.FileDescriptor

var file_Alarm_info_proto_rawDesc = []byte{
	0x0a, 0x10, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x13, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x6f, 0x6d, 0x30, 0x5f, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98, 0x01, 0x0a, 0x0d, 0x53,
	0x4f, 0x53, 0x47, 0x4e, 0x53, 0x53, 0x49, 0x4e, 0x46, 0x4f, 0x56, 0x33, 0x12, 0x28, 0x0a, 0x0a,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x23, 0x0a, 0x08, 0x67, 0x70, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x02,
	0x28, 0x0e, 0x32, 0x08, 0x2e, 0x47, 0x50, 0x53, 0x54, 0x59, 0x50, 0x45, 0x52, 0x07, 0x67, 0x70,
	0x73, 0x54, 0x79, 0x70, 0x65, 0x22, 0x45, 0x0a, 0x09, 0x48, 0x72, 0x41, 0x6c, 0x61, 0x72, 0x6d,
	0x56, 0x33, 0x12, 0x28, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x68, 0x72, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x02, 0x68, 0x72, 0x22, 0x4b, 0x0a, 0x0b,
	0x53, 0x70, 0x6f, 0x32, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x56, 0x33, 0x12, 0x28, 0x0a, 0x0a, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x70, 0x6f, 0x32, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x07, 0x52, 0x04, 0x73, 0x70, 0x6f, 0x32, 0x22, 0x62, 0x0a, 0x0f, 0x54, 0x68, 0x72,
	0x6f, 0x6d, 0x62, 0x75, 0x73, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x56, 0x33, 0x12, 0x28, 0x0a, 0x0a,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x25, 0x0a, 0x0e, 0x54, 0x68, 0x72, 0x6f, 0x6d, 0x62,
	0x75, 0x73, 0x5f, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x02, 0x28, 0x08, 0x52, 0x0d,
	0x54, 0x68, 0x72, 0x6f, 0x6d, 0x62, 0x75, 0x73, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x22, 0x5a, 0x0a,
	0x0f, 0x46, 0x61, 0x6c, 0x6c, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x56, 0x33,
	0x12, 0x28, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x61,
	0x6c, 0x6c, 0x5f, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x02, 0x28, 0x08, 0x52, 0x09,
	0x66, 0x61, 0x6c, 0x6c, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x22, 0x5d, 0x0a, 0x0f, 0x54, 0x65, 0x6d,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x28, 0x0a, 0x0a,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x0b, 0x74, 0x65, 0x6d,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x56, 0x0a, 0x06, 0x42, 0x70, 0x43, 0x6f,
	0x6e, 0x66, 0x12, 0x28, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x62, 0x70, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x03, 0x73, 0x62, 0x70, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x62, 0x70, 0x18, 0x03, 0x20, 0x02, 0x28, 0x07, 0x52, 0x03, 0x64, 0x62, 0x70,
	0x22, 0x39, 0x0a, 0x0d, 0x53, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x79, 0x43, 0x6f, 0x6e,
	0x66, 0x12, 0x28, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x5d, 0x0a, 0x10, 0x42,
	0x6c, 0x6f, 0x6f, 0x64, 0x5f, 0x73, 0x75, 0x67, 0x61, 0x72, 0x5f, 0x43, 0x6f, 0x6e, 0x66, 0x12,
	0x28, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x42, 0x6c, 0x6f,
	0x6f, 0x64, 0x5f, 0x73, 0x75, 0x67, 0x61, 0x72, 0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x0a,
	0x42, 0x6c, 0x6f, 0x6f, 0x64, 0x53, 0x75, 0x67, 0x61, 0x72, 0x22, 0x69, 0x0a, 0x14, 0x42, 0x6c,
	0x6f, 0x6f, 0x64, 0x5f, 0x70, 0x6f, 0x74, 0x61, 0x73, 0x73, 0x69, 0x75, 0x6d, 0x5f, 0x43, 0x6f,
	0x6e, 0x66, 0x12, 0x28, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x27, 0x0a, 0x0f,
	0x42, 0x6c, 0x6f, 0x6f, 0x64, 0x5f, 0x70, 0x6f, 0x74, 0x61, 0x73, 0x73, 0x69, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x0e, 0x42, 0x6c, 0x6f, 0x6f, 0x64, 0x50, 0x6f, 0x74, 0x61,
	0x73, 0x73, 0x69, 0x75, 0x6d, 0x22, 0x80, 0x02, 0x0a, 0x0b, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x69,
	0x6e, 0x66, 0x6f, 0x56, 0x33, 0x12, 0x28, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x1c, 0x0a, 0x09, 0x77, 0x65, 0x61, 0x72, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x77, 0x65, 0x61, 0x72, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a,
	0x12, 0x6c, 0x6f, 0x77, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x07, 0x52, 0x12, 0x6c, 0x6f, 0x77, 0x70, 0x6f,
	0x77, 0x65, 0x72, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a,
	0x12, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6f, 0x66, 0x66, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x07, 0x52, 0x12, 0x70, 0x6f, 0x77, 0x65, 0x72,
	0x6f, 0x66, 0x66, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a,
	0x10, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x65, 0x70, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x65,
	0x70, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0xde, 0x04, 0x0a, 0x0d, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x56, 0x33, 0x12, 0x25, 0x0a, 0x08, 0x61, 0x6c,
	0x61, 0x72, 0x6d, 0x5f, 0x68, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x48,
	0x72, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x56, 0x33, 0x52, 0x07, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x48,
	0x72, 0x12, 0x2b, 0x0a, 0x0a, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x5f, 0x73, 0x70, 0x6f, 0x32, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x70, 0x6f, 0x32, 0x41, 0x6c, 0x61, 0x72,
	0x6d, 0x56, 0x33, 0x52, 0x09, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x53, 0x70, 0x6f, 0x32, 0x12, 0x37,
	0x0a, 0x0e, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x5f, 0x54, 0x68, 0x72, 0x6f, 0x6d, 0x62, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x54, 0x68, 0x72, 0x6f, 0x6d, 0x62, 0x75,
	0x73, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x56, 0x33, 0x52, 0x0d, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x54,
	0x68, 0x72, 0x6f, 0x6d, 0x62, 0x75, 0x73, 0x12, 0x2f, 0x0a, 0x0a, 0x61, 0x6c, 0x61, 0x72, 0x6d,
	0x5f, 0x66, 0x61, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x46, 0x61,
	0x6c, 0x6c, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x56, 0x33, 0x52, 0x09, 0x61,
	0x6c, 0x61, 0x72, 0x6d, 0x46, 0x61, 0x6c, 0x6c, 0x12, 0x3d, 0x0a, 0x11, 0x61, 0x6c, 0x61, 0x72,
	0x6d, 0x5f, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x10, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x54, 0x65, 0x6d, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x22, 0x0a, 0x08, 0x61, 0x6c, 0x61, 0x72, 0x6d,
	0x5f, 0x42, 0x70, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x42, 0x70, 0x43, 0x6f,
	0x6e, 0x66, 0x52, 0x07, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x42, 0x70, 0x12, 0x2a, 0x0a, 0x08, 0x67,
	0x6e, 0x73, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x53, 0x4f, 0x53, 0x47, 0x4e, 0x53, 0x53, 0x49, 0x4e, 0x46, 0x4f, 0x56, 0x33, 0x52, 0x08, 0x67,
	0x6e, 0x73, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x37, 0x0a, 0x0f, 0x61, 0x6c, 0x61, 0x72, 0x6d,
	0x5f, 0x53, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x79, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x53, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x66,
	0x52, 0x0e, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x53, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x79,
	0x12, 0x3d, 0x0a, 0x15, 0x53, 0x4f, 0x53, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x13, 0x53, 0x4f, 0x53, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x3d, 0x0a, 0x11, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x5f, 0x42, 0x6c, 0x6f, 0x6f, 0x64, 0x5f, 0x73,
	0x75, 0x67, 0x61, 0x72, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x42, 0x6c, 0x6f,
	0x6f, 0x64, 0x5f, 0x73, 0x75, 0x67, 0x61, 0x72, 0x5f, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x0f, 0x61,
	0x6c, 0x61, 0x72, 0x6d, 0x42, 0x6c, 0x6f, 0x6f, 0x64, 0x53, 0x75, 0x67, 0x61, 0x72, 0x12, 0x49,
	0x0a, 0x15, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x5f, 0x42, 0x6c, 0x6f, 0x6f, 0x64, 0x5f, 0x70, 0x6f,
	0x74, 0x61, 0x73, 0x73, 0x69, 0x75, 0x6d, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x42, 0x6c, 0x6f, 0x6f, 0x64, 0x5f, 0x70, 0x6f, 0x74, 0x61, 0x73, 0x73, 0x69, 0x75, 0x6d, 0x5f,
	0x43, 0x6f, 0x6e, 0x66, 0x52, 0x13, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x42, 0x6c, 0x6f, 0x6f, 0x64,
	0x50, 0x6f, 0x74, 0x61, 0x73, 0x73, 0x69, 0x75, 0x6d, 0x22, 0x66, 0x0a, 0x12, 0x41, 0x6c, 0x61,
	0x72, 0x6d, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12,
	0x2a, 0x0a, 0x09, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x69, 0x6e, 0x66, 0x6f, 0x56, 0x33,
	0x52, 0x09, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x05, 0x61,
	0x6c, 0x61, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x56, 0x33, 0x52, 0x05, 0x61, 0x6c, 0x61, 0x72,
	0x6d, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x69, 0x77, 0x6f, 0x77, 0x6e,
}

var (
	file_Alarm_info_proto_rawDescOnce sync.Once
	file_Alarm_info_proto_rawDescData = file_Alarm_info_proto_rawDesc
)

func file_Alarm_info_proto_rawDescGZIP() []byte {
	file_Alarm_info_proto_rawDescOnce.Do(func() {
		file_Alarm_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_Alarm_info_proto_rawDescData)
	})
	return file_Alarm_info_proto_rawDescData
}

var file_Alarm_info_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_Alarm_info_proto_goTypes = []interface{}{
	(*SOSGNSSINFOV3)(nil),       // 0: SOSGNSSINFOV3
	(*HrAlarmV3)(nil),           // 1: HrAlarmV3
	(*Spo2AlarmV3)(nil),         // 2: Spo2AlarmV3
	(*ThrombusAlarmV3)(nil),     // 3: ThrombusAlarmV3
	(*FallAlarmConfV3)(nil),     // 4: FallAlarmConfV3
	(*TemperatureConf)(nil),     // 5: TemperatureConf
	(*BpConf)(nil),              // 6: BpConf
	(*SedentaryConf)(nil),       // 7: SedentaryConf
	(*BloodSugar_Conf)(nil),     // 8: Blood_sugar_Conf
	(*BloodPotassium_Conf)(nil), // 9: Blood_potassium_Conf
	(*AlarminfoV3)(nil),         // 10: AlarminfoV3
	(*HealthAlarmV3)(nil),       // 11: HealthAlarmV3
	(*AlarmInfokConfirm)(nil),   // 12: Alarm_infokConfirm
	(*DateTime)(nil),            // 13: DateTime
	(GPSTYPE)(0),                // 14: GPSTYPE
}
var file_Alarm_info_proto_depIdxs = []int32{
	13, // 0: SOSGNSSINFOV3.time_stamp:type_name -> DateTime
	14, // 1: SOSGNSSINFOV3.gps_type:type_name -> GPSTYPE
	13, // 2: HrAlarmV3.time_stamp:type_name -> DateTime
	13, // 3: Spo2AlarmV3.time_stamp:type_name -> DateTime
	13, // 4: ThrombusAlarmV3.time_stamp:type_name -> DateTime
	13, // 5: FallAlarmConfV3.time_stamp:type_name -> DateTime
	13, // 6: TemperatureConf.time_stamp:type_name -> DateTime
	13, // 7: BpConf.time_stamp:type_name -> DateTime
	13, // 8: SedentaryConf.time_stamp:type_name -> DateTime
	13, // 9: Blood_sugar_Conf.time_stamp:type_name -> DateTime
	13, // 10: Blood_potassium_Conf.time_stamp:type_name -> DateTime
	13, // 11: AlarminfoV3.time_stamp:type_name -> DateTime
	1,  // 12: HealthAlarmV3.alarm_hr:type_name -> HrAlarmV3
	2,  // 13: HealthAlarmV3.alarm_spo2:type_name -> Spo2AlarmV3
	3,  // 14: HealthAlarmV3.alarm_Thrombus:type_name -> ThrombusAlarmV3
	4,  // 15: HealthAlarmV3.alarm_fall:type_name -> FallAlarmConfV3
	5,  // 16: HealthAlarmV3.alarm_Temperature:type_name -> TemperatureConf
	6,  // 17: HealthAlarmV3.alarm_Bp:type_name -> BpConf
	0,  // 18: HealthAlarmV3.gnssinfo:type_name -> SOSGNSSINFOV3
	7,  // 19: HealthAlarmV3.alarm_Sedentary:type_name -> SedentaryConf
	13, // 20: HealthAlarmV3.SOS_Notification_time:type_name -> DateTime
	8,  // 21: HealthAlarmV3.alarm_Blood_sugar:type_name -> Blood_sugar_Conf
	9,  // 22: HealthAlarmV3.alarm_Blood_potassium:type_name -> Blood_potassium_Conf
	10, // 23: Alarm_infokConfirm.Alarminfo:type_name -> AlarminfoV3
	11, // 24: Alarm_infokConfirm.alarm:type_name -> HealthAlarmV3
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_Alarm_info_proto_init() }
func file_Alarm_info_proto_init() {
	if File_Alarm_info_proto != nil {
		return
	}
	file_realtime_data_proto_init()
	file_om0_command_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Alarm_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SOSGNSSINFOV3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Alarm_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HrAlarmV3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Alarm_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spo2AlarmV3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Alarm_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThrombusAlarmV3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Alarm_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FallAlarmConfV3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Alarm_info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemperatureConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Alarm_info_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BpConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Alarm_info_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SedentaryConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Alarm_info_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BloodSugar_Conf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Alarm_info_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BloodPotassium_Conf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Alarm_info_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlarminfoV3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Alarm_info_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthAlarmV3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Alarm_info_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlarmInfokConfirm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Alarm_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Alarm_info_proto_goTypes,
		DependencyIndexes: file_Alarm_info_proto_depIdxs,
		MessageInfos:      file_Alarm_info_proto_msgTypes,
	}.Build()
	File_Alarm_info_proto = out.File
	file_Alarm_info_proto_rawDesc = nil
	file_Alarm_info_proto_goTypes = nil
	file_Alarm_info_proto_depIdxs = nil
}
