// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: dev_info.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DevInfoFota int32

const (
	DevInfoFota_NON         DevInfoFota = 0
	DevInfoFota_CC2540      DevInfoFota = 1
	DevInfoFota_NRF51       DevInfoFota = 2
	DevInfoFota_DA1468X     DevInfoFota = 3
	DevInfoFota_MT2523      DevInfoFota = 4
	DevInfoFota_NRF52_BLE   DevInfoFota = 5
	DevInfoFota_GH551X_BLE  DevInfoFota = 6
	DevInfoFota_ATS3085_BLE DevInfoFota = 7
)

// Enum value maps for DevInfoFota.
var (
	DevInfoFota_name = map[int32]string{
		0: "NON",
		1: "CC2540",
		2: "NRF51",
		3: "DA1468X",
		4: "MT2523",
		5: "NRF52_BLE",
		6: "GH551X_BLE",
		7: "ATS3085_BLE",
	}
	DevInfoFota_value = map[string]int32{
		"NON":         0,
		"CC2540":      1,
		"NRF51":       2,
		"DA1468X":     3,
		"MT2523":      4,
		"NRF52_BLE":   5,
		"GH551X_BLE":  6,
		"ATS3085_BLE": 7,
	}
)

func (x DevInfoFota) Enum() *DevInfoFota {
	p := new(DevInfoFota)
	*p = x
	return p
}

func (x DevInfoFota) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DevInfoFota) Descriptor() protoreflect.EnumDescriptor {
	return file_dev_info_proto_enumTypes[0].Descriptor()
}

func (DevInfoFota) Type() protoreflect.EnumType {
	return &file_dev_info_proto_enumTypes[0]
}

func (x DevInfoFota) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DevInfoFota) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DevInfoFota(num)
	return nil
}

// Deprecated: Use DevInfoFota.Descriptor instead.
func (DevInfoFota) EnumDescriptor() ([]byte, []int) {
	return file_dev_info_proto_rawDescGZIP(), []int{0}
}

type DevInfoOperation int32

const (
	DevInfoOperation_Read  DevInfoOperation = 0
	DevInfoOperation_Write DevInfoOperation = 1
)

// Enum value maps for DevInfoOperation.
var (
	DevInfoOperation_name = map[int32]string{
		0: "Read",
		1: "Write",
	}
	DevInfoOperation_value = map[string]int32{
		"Read":  0,
		"Write": 1,
	}
)

func (x DevInfoOperation) Enum() *DevInfoOperation {
	p := new(DevInfoOperation)
	*p = x
	return p
}

func (x DevInfoOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DevInfoOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_dev_info_proto_enumTypes[1].Descriptor()
}

func (DevInfoOperation) Type() protoreflect.EnumType {
	return &file_dev_info_proto_enumTypes[1]
}

func (x DevInfoOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DevInfoOperation) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DevInfoOperation(num)
	return nil
}

// Deprecated: Use DevInfoOperation.Descriptor instead.
func (DevInfoOperation) EnumDescriptor() ([]byte, []int) {
	return file_dev_info_proto_rawDescGZIP(), []int{1}
}

type DevInfoManu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date    *string `protobuf:"bytes,1,req,name=date" json:"date,omitempty"`
	Factory *string `protobuf:"bytes,2,req,name=factory" json:"factory,omitempty"`
}

func (x *DevInfoManu) Reset() {
	*x = DevInfoManu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dev_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DevInfoManu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevInfoManu) ProtoMessage() {}

func (x *DevInfoManu) ProtoReflect() protoreflect.Message {
	mi := &file_dev_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevInfoManu.ProtoReflect.Descriptor instead.
func (*DevInfoManu) Descriptor() ([]byte, []int) {
	return file_dev_info_proto_rawDescGZIP(), []int{0}
}

func (x *DevInfoManu) GetDate() string {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return ""
}

func (x *DevInfoManu) GetFactory() string {
	if x != nil && x.Factory != nil {
		return *x.Factory
	}
	return ""
}

type DeviceInfoapn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mcc             *uint32 `protobuf:"fixed32,1,req,name=mcc" json:"mcc,omitempty"`
	Mnc             *uint32 `protobuf:"fixed32,2,req,name=mnc" json:"mnc,omitempty"`
	SettingName     *string `protobuf:"bytes,3,req,name=setting_name,json=settingName" json:"setting_name,omitempty"`
	AuthType        *uint32 `protobuf:"fixed32,4,req,name=auth_type,json=authType" json:"auth_type,omitempty"`
	RoamingProtocol *uint32 `protobuf:"fixed32,5,req,name=roaming_protocol,json=roamingProtocol" json:"roaming_protocol,omitempty"`
	ApnStr          *string `protobuf:"bytes,6,req,name=apn_str,json=apnStr" json:"apn_str,omitempty"`
	UserName        *string `protobuf:"bytes,7,req,name=user_name,json=userName" json:"user_name,omitempty"`
	Password        *string `protobuf:"bytes,8,req,name=password" json:"password,omitempty"`
}

func (x *DeviceInfoapn) Reset() {
	*x = DeviceInfoapn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dev_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceInfoapn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoapn) ProtoMessage() {}

func (x *DeviceInfoapn) ProtoReflect() protoreflect.Message {
	mi := &file_dev_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoapn.ProtoReflect.Descriptor instead.
func (*DeviceInfoapn) Descriptor() ([]byte, []int) {
	return file_dev_info_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceInfoapn) GetMcc() uint32 {
	if x != nil && x.Mcc != nil {
		return *x.Mcc
	}
	return 0
}

func (x *DeviceInfoapn) GetMnc() uint32 {
	if x != nil && x.Mnc != nil {
		return *x.Mnc
	}
	return 0
}

func (x *DeviceInfoapn) GetSettingName() string {
	if x != nil && x.SettingName != nil {
		return *x.SettingName
	}
	return ""
}

func (x *DeviceInfoapn) GetAuthType() uint32 {
	if x != nil && x.AuthType != nil {
		return *x.AuthType
	}
	return 0
}

func (x *DeviceInfoapn) GetRoamingProtocol() uint32 {
	if x != nil && x.RoamingProtocol != nil {
		return *x.RoamingProtocol
	}
	return 0
}

func (x *DeviceInfoapn) GetApnStr() string {
	if x != nil && x.ApnStr != nil {
		return *x.ApnStr
	}
	return ""
}

func (x *DeviceInfoapn) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *DeviceInfoapn) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type DeviceInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model            *string      `protobuf:"bytes,1,opt,name=model" json:"model,omitempty"`
	Version          *string      `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Mac              []byte       `protobuf:"bytes,3,opt,name=mac" json:"mac,omitempty"`
	Fota             *DevInfoFota `protobuf:"varint,4,opt,name=fota,enum=DevInfoFota" json:"fota,omitempty"`
	Manu             *DevInfoManu `protobuf:"bytes,5,opt,name=manu" json:"manu,omitempty"`
	UserData         []byte       `protobuf:"bytes,6,opt,name=user_data,json=userData" json:"user_data,omitempty"`
	PbVersion        *string      `protobuf:"bytes,7,opt,name=pb_version,json=pbVersion" json:"pb_version,omitempty"`
	CtpCs            *uint32      `protobuf:"fixed32,8,opt,name=ctp_cs,json=ctpCs" json:"ctp_cs,omitempty"`
	ProgramAddr      *uint32      `protobuf:"fixed32,9,opt,name=program_addr,json=programAddr" json:"program_addr,omitempty"`
	ResourceAddr     *uint32      `protobuf:"fixed32,10,opt,name=resource_addr,json=resourceAddr" json:"resource_addr,omitempty"`
	ApnContext       *bool        `protobuf:"varint,11,opt,name=apn_context,json=apnContext" json:"apn_context,omitempty"`
	BleName          *string      `protobuf:"bytes,12,opt,name=ble_name,json=bleName" json:"ble_name,omitempty"`
	EncryptionStatus *uint32      `protobuf:"fixed32,13,opt,name=encryption_status,json=encryptionStatus" json:"encryption_status,omitempty"`
	BpVersion        *string      `protobuf:"bytes,14,opt,name=bp_version,json=bpVersion" json:"bp_version,omitempty"`
}

func (x *DeviceInfoResponse) Reset() {
	*x = DeviceInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dev_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoResponse) ProtoMessage() {}

func (x *DeviceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoResponse.ProtoReflect.Descriptor instead.
func (*DeviceInfoResponse) Descriptor() ([]byte, []int) {
	return file_dev_info_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceInfoResponse) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *DeviceInfoResponse) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *DeviceInfoResponse) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *DeviceInfoResponse) GetFota() DevInfoFota {
	if x != nil && x.Fota != nil {
		return *x.Fota
	}
	return DevInfoFota_NON
}

func (x *DeviceInfoResponse) GetManu() *DevInfoManu {
	if x != nil {
		return x.Manu
	}
	return nil
}

func (x *DeviceInfoResponse) GetUserData() []byte {
	if x != nil {
		return x.UserData
	}
	return nil
}

func (x *DeviceInfoResponse) GetPbVersion() string {
	if x != nil && x.PbVersion != nil {
		return *x.PbVersion
	}
	return ""
}

func (x *DeviceInfoResponse) GetCtpCs() uint32 {
	if x != nil && x.CtpCs != nil {
		return *x.CtpCs
	}
	return 0
}

func (x *DeviceInfoResponse) GetProgramAddr() uint32 {
	if x != nil && x.ProgramAddr != nil {
		return *x.ProgramAddr
	}
	return 0
}

func (x *DeviceInfoResponse) GetResourceAddr() uint32 {
	if x != nil && x.ResourceAddr != nil {
		return *x.ResourceAddr
	}
	return 0
}

func (x *DeviceInfoResponse) GetApnContext() bool {
	if x != nil && x.ApnContext != nil {
		return *x.ApnContext
	}
	return false
}

func (x *DeviceInfoResponse) GetBleName() string {
	if x != nil && x.BleName != nil {
		return *x.BleName
	}
	return ""
}

func (x *DeviceInfoResponse) GetEncryptionStatus() uint32 {
	if x != nil && x.EncryptionStatus != nil {
		return *x.EncryptionStatus
	}
	return 0
}

func (x *DeviceInfoResponse) GetBpVersion() string {
	if x != nil && x.BpVersion != nil {
		return *x.BpVersion
	}
	return ""
}

type DeviceInfoCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserData            []byte         `protobuf:"bytes,1,opt,name=user_data,json=userData" json:"user_data,omitempty"`
	ApnContext          *DeviceInfoapn `protobuf:"bytes,2,opt,name=apn_context,json=apnContext" json:"apn_context,omitempty"`
	DataUrl             *string        `protobuf:"bytes,3,opt,name=data_url,json=dataUrl" json:"data_url,omitempty"`
	ResonantFrequency   *uint32        `protobuf:"fixed32,4,opt,name=Resonant_frequency,json=ResonantFrequency" json:"Resonant_frequency,omitempty"`
	AppQrUrl            *string        `protobuf:"bytes,5,opt,name=app_qr_url,json=appQrUrl" json:"app_qr_url,omitempty"`
	BleName             *string        `protobuf:"bytes,6,opt,name=ble_name,json=bleName" json:"ble_name,omitempty"`
	OtherInfoData       []byte         `protobuf:"bytes,7,opt,name=Other_info_data,json=OtherInfoData" json:"Other_info_data,omitempty"`
	DeviceIRemainingSum *uint32        `protobuf:"fixed32,8,opt,name=DeviceI_remaining_sum,json=DeviceIRemainingSum" json:"DeviceI_remaining_sum,omitempty"`
}

func (x *DeviceInfoCommand) Reset() {
	*x = DeviceInfoCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dev_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceInfoCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoCommand) ProtoMessage() {}

func (x *DeviceInfoCommand) ProtoReflect() protoreflect.Message {
	mi := &file_dev_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoCommand.ProtoReflect.Descriptor instead.
func (*DeviceInfoCommand) Descriptor() ([]byte, []int) {
	return file_dev_info_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceInfoCommand) GetUserData() []byte {
	if x != nil {
		return x.UserData
	}
	return nil
}

func (x *DeviceInfoCommand) GetApnContext() *DeviceInfoapn {
	if x != nil {
		return x.ApnContext
	}
	return nil
}

func (x *DeviceInfoCommand) GetDataUrl() string {
	if x != nil && x.DataUrl != nil {
		return *x.DataUrl
	}
	return ""
}

func (x *DeviceInfoCommand) GetResonantFrequency() uint32 {
	if x != nil && x.ResonantFrequency != nil {
		return *x.ResonantFrequency
	}
	return 0
}

func (x *DeviceInfoCommand) GetAppQrUrl() string {
	if x != nil && x.AppQrUrl != nil {
		return *x.AppQrUrl
	}
	return ""
}

func (x *DeviceInfoCommand) GetBleName() string {
	if x != nil && x.BleName != nil {
		return *x.BleName
	}
	return ""
}

func (x *DeviceInfoCommand) GetOtherInfoData() []byte {
	if x != nil {
		return x.OtherInfoData
	}
	return nil
}

func (x *DeviceInfoCommand) GetDeviceIRemainingSum() uint32 {
	if x != nil && x.DeviceIRemainingSum != nil {
		return *x.DeviceIRemainingSum
	}
	return 0
}

type DeviceInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reserved  *uint32            `protobuf:"fixed32,1,opt,name=reserved" json:"reserved,omitempty"`
	Operation *DevInfoOperation  `protobuf:"varint,2,req,name=operation,enum=DevInfoOperation" json:"operation,omitempty"`
	Devinfo   *DeviceInfoCommand `protobuf:"bytes,3,opt,name=devinfo" json:"devinfo,omitempty"`
}

func (x *DeviceInfoRequest) Reset() {
	*x = DeviceInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dev_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoRequest) ProtoMessage() {}

func (x *DeviceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoRequest.ProtoReflect.Descriptor instead.
func (*DeviceInfoRequest) Descriptor() ([]byte, []int) {
	return file_dev_info_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceInfoRequest) GetReserved() uint32 {
	if x != nil && x.Reserved != nil {
		return *x.Reserved
	}
	return 0
}

func (x *DeviceInfoRequest) GetOperation() DevInfoOperation {
	if x != nil && x.Operation != nil {
		return *x.Operation
	}
	return DevInfoOperation_Read
}

func (x *DeviceInfoRequest) GetDevinfo() *DeviceInfoCommand {
	if x != nil {
		return x.Devinfo
	}
	return nil
}

var File_dev_info_proto protoreflect.FileDescriptor

var file_dev_info_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x65, 0x76, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x3b, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x61, 0x6e, 0x75, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x22, 0xf0, 0x01,
	0x0a, 0x0d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x61, 0x70, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x63, 0x63, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x03, 0x6d, 0x63,
	0x63, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x03,
	0x6d, 0x6e, 0x63, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x07, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x6f, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x02, 0x28, 0x07, 0x52, 0x0f, 0x72,
	0x6f, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x17,
	0x0a, 0x07, 0x61, 0x70, 0x6e, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x06, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x70, 0x6e, 0x53, 0x74, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x08, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0xbd, 0x03, 0x0a, 0x12, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x61, 0x63, 0x12, 0x20, 0x0a, 0x04, 0x66, 0x6f, 0x74,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x44, 0x65, 0x76, 0x49, 0x6e, 0x66,
	0x6f, 0x46, 0x6f, 0x74, 0x61, 0x52, 0x04, 0x66, 0x6f, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x04, 0x6d,
	0x61, 0x6e, 0x75, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x44, 0x65, 0x76, 0x49,
	0x6e, 0x66, 0x6f, 0x4d, 0x61, 0x6e, 0x75, 0x52, 0x04, 0x6d, 0x61, 0x6e, 0x75, 0x12, 0x1b, 0x0a,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x62,
	0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x62, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x74, 0x70,
	0x5f, 0x63, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x07, 0x52, 0x05, 0x63, 0x74, 0x70, 0x43, 0x73,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x41,
	0x64, 0x64, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x6e, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x61,
	0x70, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x07, 0x52,
	0x10, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x70, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0xc0, 0x02, 0x0a, 0x11, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x0b, 0x61, 0x70, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x61, 0x70, 0x6e, 0x52, 0x0a, 0x61, 0x70, 0x6e, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x55, 0x72, 0x6c, 0x12,
	0x2d, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x6f, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x66, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x07, 0x52, 0x11, 0x52, 0x65, 0x73,
	0x6f, 0x6e, 0x61, 0x6e, 0x74, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1c,
	0x0a, 0x0a, 0x61, 0x70, 0x70, 0x5f, 0x71, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x61, 0x70, 0x70, 0x51, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x19, 0x0a, 0x08,
	0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x4f, 0x74, 0x68, 0x65, 0x72,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0d, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x32, 0x0a, 0x15, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x5f, 0x72, 0x65, 0x6d, 0x61, 0x69,
	0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x75, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x07, 0x52, 0x13,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67,
	0x53, 0x75, 0x6d, 0x22, 0x8e, 0x01, 0x0a, 0x11, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x64, 0x12, 0x2f, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x44, 0x65, 0x76, 0x49, 0x6e,
	0x66, 0x6f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x64, 0x65, 0x76,
	0x69, 0x6e, 0x66, 0x6f, 0x2a, 0x76, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x49, 0x6e, 0x66, 0x6f, 0x46,
	0x6f, 0x74, 0x61, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x43, 0x43, 0x32, 0x35, 0x34, 0x30, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x52, 0x46, 0x35,
	0x31, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x41, 0x31, 0x34, 0x36, 0x38, 0x58, 0x10, 0x03,
	0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x54, 0x32, 0x35, 0x32, 0x33, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09,
	0x4e, 0x52, 0x46, 0x35, 0x32, 0x5f, 0x42, 0x4c, 0x45, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x47,
	0x48, 0x35, 0x35, 0x31, 0x58, 0x5f, 0x42, 0x4c, 0x45, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x41,
	0x54, 0x53, 0x33, 0x30, 0x38, 0x35, 0x5f, 0x42, 0x4c, 0x45, 0x10, 0x07, 0x2a, 0x27, 0x0a, 0x10,
	0x44, 0x65, 0x76, 0x49, 0x6e, 0x66, 0x6f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x08, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x10, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x69, 0x77, 0x6f, 0x77, 0x6e,
}

var (
	file_dev_info_proto_rawDescOnce sync.Once
	file_dev_info_proto_rawDescData = file_dev_info_proto_rawDesc
)

func file_dev_info_proto_rawDescGZIP() []byte {
	file_dev_info_proto_rawDescOnce.Do(func() {
		file_dev_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_dev_info_proto_rawDescData)
	})
	return file_dev_info_proto_rawDescData
}

var file_dev_info_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dev_info_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dev_info_proto_goTypes = []interface{}{
	(DevInfoFota)(0),           // 0: DevInfoFota
	(DevInfoOperation)(0),      // 1: DevInfoOperation
	(*DevInfoManu)(nil),        // 2: DevInfoManu
	(*DeviceInfoapn)(nil),      // 3: DeviceInfoapn
	(*DeviceInfoResponse)(nil), // 4: DeviceInfoResponse
	(*DeviceInfoCommand)(nil),  // 5: DeviceInfoCommand
	(*DeviceInfoRequest)(nil),  // 6: DeviceInfoRequest
}
var file_dev_info_proto_depIdxs = []int32{
	0, // 0: DeviceInfoResponse.fota:type_name -> DevInfoFota
	2, // 1: DeviceInfoResponse.manu:type_name -> DevInfoManu
	3, // 2: DeviceInfoCommand.apn_context:type_name -> DeviceInfoapn
	1, // 3: DeviceInfoRequest.operation:type_name -> DevInfoOperation
	5, // 4: DeviceInfoRequest.devinfo:type_name -> DeviceInfoCommand
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_dev_info_proto_init() }
func file_dev_info_proto_init() {
	if File_dev_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dev_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DevInfoManu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dev_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceInfoapn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dev_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dev_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceInfoCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dev_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dev_info_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_info_proto_goTypes,
		DependencyIndexes: file_dev_info_proto_depIdxs,
		EnumInfos:         file_dev_info_proto_enumTypes,
		MessageInfos:      file_dev_info_proto_msgTypes,
	}.Build()
	File_dev_info_proto = out.File
	file_dev_info_proto_rawDesc = nil
	file_dev_info_proto_goTypes = nil
	file_dev_info_proto_depIdxs = nil
}
