// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: his_health_data.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HisMdtState int32

const (
	HisMdtState_PREPARE HisMdtState = 0
	HisMdtState_ONGOING HisMdtState = 1
	HisMdtState_RELAX   HisMdtState = 2
)

// Enum value maps for HisMdtState.
var (
	HisMdtState_name = map[int32]string{
		0: "PREPARE",
		1: "ONGOING",
		2: "RELAX",
	}
	HisMdtState_value = map[string]int32{
		"PREPARE": 0,
		"ONGOING": 1,
		"RELAX":   2,
	}
)

func (x HisMdtState) Enum() *HisMdtState {
	p := new(HisMdtState)
	*p = x
	return p
}

func (x HisMdtState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HisMdtState) Descriptor() protoreflect.EnumDescriptor {
	return file_his_health_data_proto_enumTypes[0].Descriptor()
}

func (HisMdtState) Type() protoreflect.EnumType {
	return &file_his_health_data_proto_enumTypes[0]
}

func (x HisMdtState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HisMdtState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HisMdtState(num)
	return nil
}

// Deprecated: Use HisMdtState.Descriptor instead.
func (HisMdtState) EnumDescriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{0}
}

type TPAMeasureType int32

const (
	TPAMeasureType_TPA_MEASURE_TYPE_NULL   TPAMeasureType = 0
	TPAMeasureType_TPA_MEASURE_TYPE_AUTO   TPAMeasureType = 1
	TPAMeasureType_TPA_MEASURE_TYPE_ARMPIT TPAMeasureType = 2
)

// Enum value maps for TPAMeasureType.
var (
	TPAMeasureType_name = map[int32]string{
		0: "TPA_MEASURE_TYPE_NULL",
		1: "TPA_MEASURE_TYPE_AUTO",
		2: "TPA_MEASURE_TYPE_ARMPIT",
	}
	TPAMeasureType_value = map[string]int32{
		"TPA_MEASURE_TYPE_NULL":   0,
		"TPA_MEASURE_TYPE_AUTO":   1,
		"TPA_MEASURE_TYPE_ARMPIT": 2,
	}
)

func (x TPAMeasureType) Enum() *TPAMeasureType {
	p := new(TPAMeasureType)
	*p = x
	return p
}

func (x TPAMeasureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TPAMeasureType) Descriptor() protoreflect.EnumDescriptor {
	return file_his_health_data_proto_enumTypes[1].Descriptor()
}

func (TPAMeasureType) Type() protoreflect.EnumType {
	return &file_his_health_data_proto_enumTypes[1]
}

func (x TPAMeasureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TPAMeasureType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TPAMeasureType(num)
	return nil
}

// Deprecated: Use TPAMeasureType.Descriptor instead.
func (TPAMeasureType) EnumDescriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{1}
}

type HisHealthPedo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     *uint32 `protobuf:"fixed32,1,req,name=type" json:"type,omitempty"`
	State    *uint32 `protobuf:"fixed32,2,req,name=state" json:"state,omitempty"`
	Calorie  *uint32 `protobuf:"fixed32,3,req,name=calorie" json:"calorie,omitempty"`
	Step     *uint32 `protobuf:"fixed32,4,req,name=step" json:"step,omitempty"`
	Distance *uint32 `protobuf:"fixed32,5,req,name=distance" json:"distance,omitempty"`
}

func (x *HisHealthPedo) Reset() {
	*x = HisHealthPedo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthPedo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthPedo) ProtoMessage() {}

func (x *HisHealthPedo) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthPedo.ProtoReflect.Descriptor instead.
func (*HisHealthPedo) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{0}
}

func (x *HisHealthPedo) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *HisHealthPedo) GetState() uint32 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

func (x *HisHealthPedo) GetCalorie() uint32 {
	if x != nil && x.Calorie != nil {
		return *x.Calorie
	}
	return 0
}

func (x *HisHealthPedo) GetStep() uint32 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *HisHealthPedo) GetDistance() uint32 {
	if x != nil && x.Distance != nil {
		return *x.Distance
	}
	return 0
}

type HisHealthHr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinBpm *uint32 `protobuf:"fixed32,1,req,name=min_bpm,json=minBpm" json:"min_bpm,omitempty"`
	MaxBpm *uint32 `protobuf:"fixed32,2,req,name=max_bpm,json=maxBpm" json:"max_bpm,omitempty"`
	AvgBpm *uint32 `protobuf:"fixed32,3,req,name=avg_bpm,json=avgBpm" json:"avg_bpm,omitempty"`
}

func (x *HisHealthHr) Reset() {
	*x = HisHealthHr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthHr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthHr) ProtoMessage() {}

func (x *HisHealthHr) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthHr.ProtoReflect.Descriptor instead.
func (*HisHealthHr) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{1}
}

func (x *HisHealthHr) GetMinBpm() uint32 {
	if x != nil && x.MinBpm != nil {
		return *x.MinBpm
	}
	return 0
}

func (x *HisHealthHr) GetMaxBpm() uint32 {
	if x != nil && x.MaxBpm != nil {
		return *x.MaxBpm
	}
	return 0
}

func (x *HisHealthHr) GetAvgBpm() uint32 {
	if x != nil && x.AvgBpm != nil {
		return *x.AvgBpm
	}
	return 0
}

type HisHealthbloodPotassium struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BloodPotassium *uint32 `protobuf:"fixed32,1,req,name=bloodPotassium" json:"bloodPotassium,omitempty"`
}

func (x *HisHealthbloodPotassium) Reset() {
	*x = HisHealthbloodPotassium{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthbloodPotassium) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthbloodPotassium) ProtoMessage() {}

func (x *HisHealthbloodPotassium) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthbloodPotassium.ProtoReflect.Descriptor instead.
func (*HisHealthbloodPotassium) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{2}
}

func (x *HisHealthbloodPotassium) GetBloodPotassium() uint32 {
	if x != nil && x.BloodPotassium != nil {
		return *x.BloodPotassium
	}
	return 0
}

type HisHealthBloodSugar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BloodSugar *uint32 `protobuf:"fixed32,1,req,name=Blood_sugar,json=BloodSugar" json:"Blood_sugar,omitempty"`
}

func (x *HisHealthBloodSugar) Reset() {
	*x = HisHealthBloodSugar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthBloodSugar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthBloodSugar) ProtoMessage() {}

func (x *HisHealthBloodSugar) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthBloodSugar.ProtoReflect.Descriptor instead.
func (*HisHealthBloodSugar) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{3}
}

func (x *HisHealthBloodSugar) GetBloodSugar() uint32 {
	if x != nil && x.BloodSugar != nil {
		return *x.BloodSugar
	}
	return 0
}

type HisHealthOutAct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutAct *uint32 `protobuf:"fixed32,1,req,name=out_act,json=outAct" json:"out_act,omitempty"`
}

func (x *HisHealthOutAct) Reset() {
	*x = HisHealthOutAct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthOutAct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthOutAct) ProtoMessage() {}

func (x *HisHealthOutAct) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthOutAct.ProtoReflect.Descriptor instead.
func (*HisHealthOutAct) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{4}
}

func (x *HisHealthOutAct) GetOutAct() uint32 {
	if x != nil && x.OutAct != nil {
		return *x.OutAct
	}
	return 0
}

type HisHealthHrv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SDNN    *float32 `protobuf:"fixed32,1,req,name=SDNN" json:"SDNN,omitempty"`
	RMSSD   *float32 `protobuf:"fixed32,2,req,name=RMSSD" json:"RMSSD,omitempty"`
	PNN50   *float32 `protobuf:"fixed32,3,req,name=PNN50" json:"PNN50,omitempty"`
	MEAN    *float32 `protobuf:"fixed32,4,req,name=MEAN" json:"MEAN,omitempty"`
	Fatigue *float32 `protobuf:"fixed32,5,req,name=fatigue" json:"fatigue,omitempty"`
}

func (x *HisHealthHrv) Reset() {
	*x = HisHealthHrv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthHrv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthHrv) ProtoMessage() {}

func (x *HisHealthHrv) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthHrv.ProtoReflect.Descriptor instead.
func (*HisHealthHrv) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{5}
}

func (x *HisHealthHrv) GetSDNN() float32 {
	if x != nil && x.SDNN != nil {
		return *x.SDNN
	}
	return 0
}

func (x *HisHealthHrv) GetRMSSD() float32 {
	if x != nil && x.RMSSD != nil {
		return *x.RMSSD
	}
	return 0
}

func (x *HisHealthHrv) GetPNN50() float32 {
	if x != nil && x.PNN50 != nil {
		return *x.PNN50
	}
	return 0
}

func (x *HisHealthHrv) GetMEAN() float32 {
	if x != nil && x.MEAN != nil {
		return *x.MEAN
	}
	return 0
}

func (x *HisHealthHrv) GetFatigue() float32 {
	if x != nil && x.Fatigue != nil {
		return *x.Fatigue
	}
	return 0
}

type HisHealthMdt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SDNN   *float32     `protobuf:"fixed32,1,req,name=SDNN" json:"SDNN,omitempty"`
	RMSSD  *float32     `protobuf:"fixed32,2,req,name=RMSSD" json:"RMSSD,omitempty"`
	PNN50  *float32     `protobuf:"fixed32,3,req,name=PNN50" json:"PNN50,omitempty"`
	MEAN   *float32     `protobuf:"fixed32,4,req,name=MEAN" json:"MEAN,omitempty"`
	Status *HisMdtState `protobuf:"varint,5,req,name=status,enum=HisMdtState" json:"status,omitempty"`
	RESULT *float32     `protobuf:"fixed32,6,req,name=RESULT" json:"RESULT,omitempty"`
	RELAX  *float32     `protobuf:"fixed32,7,req,name=RELAX" json:"RELAX,omitempty"`
}

func (x *HisHealthMdt) Reset() {
	*x = HisHealthMdt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthMdt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthMdt) ProtoMessage() {}

func (x *HisHealthMdt) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthMdt.ProtoReflect.Descriptor instead.
func (*HisHealthMdt) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{6}
}

func (x *HisHealthMdt) GetSDNN() float32 {
	if x != nil && x.SDNN != nil {
		return *x.SDNN
	}
	return 0
}

func (x *HisHealthMdt) GetRMSSD() float32 {
	if x != nil && x.RMSSD != nil {
		return *x.RMSSD
	}
	return 0
}

func (x *HisHealthMdt) GetPNN50() float32 {
	if x != nil && x.PNN50 != nil {
		return *x.PNN50
	}
	return 0
}

func (x *HisHealthMdt) GetMEAN() float32 {
	if x != nil && x.MEAN != nil {
		return *x.MEAN
	}
	return 0
}

func (x *HisHealthMdt) GetStatus() HisMdtState {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return HisMdtState_PREPARE
}

func (x *HisHealthMdt) GetRESULT() float32 {
	if x != nil && x.RESULT != nil {
		return *x.RESULT
	}
	return 0
}

func (x *HisHealthMdt) GetRELAX() float32 {
	if x != nil && x.RELAX != nil {
		return *x.RELAX
	}
	return 0
}

type HisHealthBp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sbp  *uint32 `protobuf:"fixed32,1,req,name=sbp" json:"sbp,omitempty"`
	Dbp  *uint32 `protobuf:"fixed32,2,req,name=dbp" json:"dbp,omitempty"`
	Time *uint32 `protobuf:"fixed32,3,opt,name=time" json:"time,omitempty"`
}

func (x *HisHealthBp) Reset() {
	*x = HisHealthBp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthBp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthBp) ProtoMessage() {}

func (x *HisHealthBp) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthBp.ProtoReflect.Descriptor instead.
func (*HisHealthBp) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{7}
}

func (x *HisHealthBp) GetSbp() uint32 {
	if x != nil && x.Sbp != nil {
		return *x.Sbp
	}
	return 0
}

func (x *HisHealthBp) GetDbp() uint32 {
	if x != nil && x.Dbp != nil {
		return *x.Dbp
	}
	return 0
}

func (x *HisHealthBp) GetTime() uint32 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

type HisHealthbpBpm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bpm *uint32 `protobuf:"fixed32,1,req,name=bpm" json:"bpm,omitempty"`
}

func (x *HisHealthbpBpm) Reset() {
	*x = HisHealthbpBpm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthbpBpm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthbpBpm) ProtoMessage() {}

func (x *HisHealthbpBpm) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthbpBpm.ProtoReflect.Descriptor instead.
func (*HisHealthbpBpm) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{8}
}

func (x *HisHealthbpBpm) GetBpm() uint32 {
	if x != nil && x.Bpm != nil {
		return *x.Bpm
	}
	return 0
}

type HisHealthAf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Af     *int32 `protobuf:"fixed32,1,req,name=af" json:"af,omitempty"`
	Manual *bool  `protobuf:"varint,2,opt,name=manual" json:"manual,omitempty"` // true for manual measurement
}

func (x *HisHealthAf) Reset() {
	*x = HisHealthAf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthAf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthAf) ProtoMessage() {}

func (x *HisHealthAf) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthAf.ProtoReflect.Descriptor instead.
func (*HisHealthAf) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{9}
}

func (x *HisHealthAf) GetAf() int32 {
	if x != nil && x.Af != nil {
		return *x.Af
	}
	return 0
}

func (x *HisHealthAf) GetManual() bool {
	if x != nil && x.Manual != nil {
		return *x.Manual
	}
	return false
}

type HisHealthSleep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SleepData []uint32 `protobuf:"fixed32,1,rep,packed,name=sleep_data,json=sleepData" json:"sleep_data,omitempty"`
	ShutDown  *bool    `protobuf:"varint,2,req,name=shut_down,json=shutDown" json:"shut_down,omitempty"`
	Charge    *bool    `protobuf:"varint,3,req,name=charge" json:"charge,omitempty"`
}

func (x *HisHealthSleep) Reset() {
	*x = HisHealthSleep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthSleep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthSleep) ProtoMessage() {}

func (x *HisHealthSleep) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthSleep.ProtoReflect.Descriptor instead.
func (*HisHealthSleep) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{10}
}

func (x *HisHealthSleep) GetSleepData() []uint32 {
	if x != nil {
		return x.SleepData
	}
	return nil
}

func (x *HisHealthSleep) GetShutDown() bool {
	if x != nil && x.ShutDown != nil {
		return *x.ShutDown
	}
	return false
}

func (x *HisHealthSleep) GetCharge() bool {
	if x != nil && x.Charge != nil {
		return *x.Charge
	}
	return false
}

type HisHealthMood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MoodLevel *uint32 `protobuf:"fixed32,1,req,name=mood_level,json=moodLevel" json:"mood_level,omitempty"`
}

func (x *HisHealthMood) Reset() {
	*x = HisHealthMood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthMood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthMood) ProtoMessage() {}

func (x *HisHealthMood) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthMood.ProtoReflect.Descriptor instead.
func (*HisHealthMood) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{11}
}

func (x *HisHealthMood) GetMoodLevel() uint32 {
	if x != nil && x.MoodLevel != nil {
		return *x.MoodLevel
	}
	return 0
}

type HisHealthBreath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Breathrate *uint32 `protobuf:"fixed32,1,req,name=breathrate" json:"breathrate,omitempty"`
}

func (x *HisHealthBreath) Reset() {
	*x = HisHealthBreath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthBreath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthBreath) ProtoMessage() {}

func (x *HisHealthBreath) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthBreath.ProtoReflect.Descriptor instead.
func (*HisHealthBreath) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{12}
}

func (x *HisHealthBreath) GetBreathrate() uint32 {
	if x != nil && x.Breathrate != nil {
		return *x.Breathrate
	}
	return 0
}

type HisHealthBioz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R    *uint32 `protobuf:"fixed32,1,req,name=R" json:"R,omitempty"`
	X    *uint32 `protobuf:"fixed32,2,req,name=X" json:"X,omitempty"`
	Fat  *uint32 `protobuf:"fixed32,3,req,name=fat" json:"fat,omitempty"`
	Bmi  *uint32 `protobuf:"fixed32,4,req,name=bmi" json:"bmi,omitempty"`
	Type *uint32 `protobuf:"fixed32,5,req,name=type" json:"type,omitempty"`
}

func (x *HisHealthBioz) Reset() {
	*x = HisHealthBioz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthBioz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthBioz) ProtoMessage() {}

func (x *HisHealthBioz) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthBioz.ProtoReflect.Descriptor instead.
func (*HisHealthBioz) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{13}
}

func (x *HisHealthBioz) GetR() uint32 {
	if x != nil && x.R != nil {
		return *x.R
	}
	return 0
}

func (x *HisHealthBioz) GetX() uint32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *HisHealthBioz) GetFat() uint32 {
	if x != nil && x.Fat != nil {
		return *x.Fat
	}
	return 0
}

func (x *HisHealthBioz) GetBmi() uint32 {
	if x != nil && x.Bmi != nil {
		return *x.Bmi
	}
	return 0
}

func (x *HisHealthBioz) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

type HisHealthBOxy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinOxy *uint32 `protobuf:"fixed32,1,req,name=min_oxy,json=minOxy" json:"min_oxy,omitempty"`
	MaxOxy *uint32 `protobuf:"fixed32,2,req,name=max_oxy,json=maxOxy" json:"max_oxy,omitempty"`
	AgvOxy *uint32 `protobuf:"fixed32,3,req,name=agv_oxy,json=agvOxy" json:"agv_oxy,omitempty"`
}

func (x *HisHealthBOxy) Reset() {
	*x = HisHealthBOxy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthBOxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthBOxy) ProtoMessage() {}

func (x *HisHealthBOxy) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthBOxy.ProtoReflect.Descriptor instead.
func (*HisHealthBOxy) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{14}
}

func (x *HisHealthBOxy) GetMinOxy() uint32 {
	if x != nil && x.MinOxy != nil {
		return *x.MinOxy
	}
	return 0
}

func (x *HisHealthBOxy) GetMaxOxy() uint32 {
	if x != nil && x.MaxOxy != nil {
		return *x.MaxOxy
	}
	return 0
}

func (x *HisHealthBOxy) GetAgvOxy() uint32 {
	if x != nil && x.AgvOxy != nil {
		return *x.AgvOxy
	}
	return 0
}

type HisHealthTemp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    *TPAMeasureType `protobuf:"varint,1,req,name=type,enum=TPAMeasureType" json:"type,omitempty"`
	EviBody *uint32         `protobuf:"fixed32,2,req,name=evi_body,json=eviBody" json:"evi_body,omitempty"`
	EstiArm *uint32         `protobuf:"fixed32,3,req,name=esti_arm,json=estiArm" json:"esti_arm,omitempty"`
}

func (x *HisHealthTemp) Reset() {
	*x = HisHealthTemp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthTemp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthTemp) ProtoMessage() {}

func (x *HisHealthTemp) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthTemp.ProtoReflect.Descriptor instead.
func (*HisHealthTemp) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{15}
}

func (x *HisHealthTemp) GetType() TPAMeasureType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return TPAMeasureType_TPA_MEASURE_TYPE_NULL
}

func (x *HisHealthTemp) GetEviBody() uint32 {
	if x != nil && x.EviBody != nil {
		return *x.EviBody
	}
	return 0
}

func (x *HisHealthTemp) GetEstiArm() uint32 {
	if x != nil && x.EstiArm != nil {
		return *x.EstiArm
	}
	return 0
}

type HisHealthOAQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	O3ConcPpb *float32 `protobuf:"fixed32,1,req,name=O3_conc_ppb,json=O3ConcPpb" json:"O3_conc_ppb,omitempty"`
	FAST_AQI  *uint32  `protobuf:"fixed32,2,req,name=FAST_AQI,json=FASTAQI" json:"FAST_AQI,omitempty"`
	EPA_AQI   *uint32  `protobuf:"fixed32,3,req,name=EPA_AQI,json=EPAAQI" json:"EPA_AQI,omitempty"`
}

func (x *HisHealthOAQ) Reset() {
	*x = HisHealthOAQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthOAQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthOAQ) ProtoMessage() {}

func (x *HisHealthOAQ) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthOAQ.ProtoReflect.Descriptor instead.
func (*HisHealthOAQ) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{16}
}

func (x *HisHealthOAQ) GetO3ConcPpb() float32 {
	if x != nil && x.O3ConcPpb != nil {
		return *x.O3ConcPpb
	}
	return 0
}

func (x *HisHealthOAQ) GetFAST_AQI() uint32 {
	if x != nil && x.FAST_AQI != nil {
		return *x.FAST_AQI
	}
	return 0
}

func (x *HisHealthOAQ) GetEPA_AQI() uint32 {
	if x != nil && x.EPA_AQI != nil {
		return *x.EPA_AQI
	}
	return 0
}

type HisHealthIAQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Iaq  *float32 `protobuf:"fixed32,1,req,name=iaq" json:"iaq,omitempty"`
	Tvoc *float32 `protobuf:"fixed32,2,req,name=tvoc" json:"tvoc,omitempty"`
	Etoh *float32 `protobuf:"fixed32,3,req,name=etoh" json:"etoh,omitempty"`
	Eco2 *float32 `protobuf:"fixed32,4,req,name=eco2" json:"eco2,omitempty"`
}

func (x *HisHealthIAQ) Reset() {
	*x = HisHealthIAQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthIAQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthIAQ) ProtoMessage() {}

func (x *HisHealthIAQ) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthIAQ.ProtoReflect.Descriptor instead.
func (*HisHealthIAQ) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{17}
}

func (x *HisHealthIAQ) GetIaq() float32 {
	if x != nil && x.Iaq != nil {
		return *x.Iaq
	}
	return 0
}

func (x *HisHealthIAQ) GetTvoc() float32 {
	if x != nil && x.Tvoc != nil {
		return *x.Tvoc
	}
	return 0
}

func (x *HisHealthIAQ) GetEtoh() float32 {
	if x != nil && x.Etoh != nil {
		return *x.Etoh
	}
	return 0
}

func (x *HisHealthIAQ) GetEco2() float32 {
	if x != nil && x.Eco2 != nil {
		return *x.Eco2
	}
	return 0
}

type HisHealthHuMiTure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Humidity    *float32 `protobuf:"fixed32,1,req,name=Humidity" json:"Humidity,omitempty"`
	Temperature *float32 `protobuf:"fixed32,2,req,name=temperature" json:"temperature,omitempty"`
}

func (x *HisHealthHuMiTure) Reset() {
	*x = HisHealthHuMiTure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisHealthHuMiTure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisHealthHuMiTure) ProtoMessage() {}

func (x *HisHealthHuMiTure) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisHealthHuMiTure.ProtoReflect.Descriptor instead.
func (*HisHealthHuMiTure) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{18}
}

func (x *HisHealthHuMiTure) GetHumidity() float32 {
	if x != nil && x.Humidity != nil {
		return *x.Humidity
	}
	return 0
}

func (x *HisHealthHuMiTure) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

type HisDataHealth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp          *DateTime                `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	SleepData          *HisHealthSleep          `protobuf:"bytes,2,opt,name=sleep_data,json=sleepData" json:"sleep_data,omitempty"`
	PedoData           *HisHealthPedo           `protobuf:"bytes,3,opt,name=pedo_data,json=pedoData" json:"pedo_data,omitempty"`
	HrData             *HisHealthHr             `protobuf:"bytes,4,opt,name=hr_data,json=hrData" json:"hr_data,omitempty"`
	HrvData            *HisHealthHrv            `protobuf:"bytes,5,opt,name=hrv_data,json=hrvData" json:"hrv_data,omitempty"`
	BpData             *HisHealthBp             `protobuf:"bytes,6,opt,name=bp_data,json=bpData" json:"bp_data,omitempty"`
	AfData             *HisHealthAf             `protobuf:"bytes,7,opt,name=af_data,json=afData" json:"af_data,omitempty"`
	MdtData            *HisHealthMdt            `protobuf:"bytes,8,opt,name=mdt_data,json=mdtData" json:"mdt_data,omitempty"`
	MoodData           *HisHealthMood           `protobuf:"bytes,9,opt,name=mood_data,json=moodData" json:"mood_data,omitempty"`
	BreathData         *HisHealthBreath         `protobuf:"bytes,10,opt,name=breath_data,json=breathData" json:"breath_data,omitempty"`
	BiozData           *HisHealthBioz           `protobuf:"bytes,11,opt,name=bioz_data,json=biozData" json:"bioz_data,omitempty"`
	BxoyData           *HisHealthBOxy           `protobuf:"bytes,12,opt,name=bxoy_data,json=bxoyData" json:"bxoy_data,omitempty"`
	TemperatureData    *HisHealthTemp           `protobuf:"bytes,13,opt,name=temperature_data,json=temperatureData" json:"temperature_data,omitempty"`
	OutActData         *HisHealthOutAct         `protobuf:"bytes,14,opt,name=out_act_data,json=outActData" json:"out_act_data,omitempty"`
	OaqData            *HisHealthOAQ            `protobuf:"bytes,15,opt,name=oaq_data,json=oaqData" json:"oaq_data,omitempty"`
	IaqData            *HisHealthIAQ            `protobuf:"bytes,16,opt,name=iaq_data,json=iaqData" json:"iaq_data,omitempty"`
	HumitureData       *HisHealthHuMiTure       `protobuf:"bytes,17,opt,name=humiture_data,json=humitureData" json:"humiture_data,omitempty"`
	BloodSugarData     *HisHealthBloodSugar     `protobuf:"bytes,18,opt,name=Blood_sugar_data,json=BloodSugarData" json:"Blood_sugar_data,omitempty"`
	BpBpmData          *HisHealthbpBpm          `protobuf:"bytes,19,opt,name=bp_bpm_data,json=bpBpmData" json:"bp_bpm_data,omitempty"`
	BloodPotassiumData *HisHealthbloodPotassium `protobuf:"bytes,20,opt,name=bloodPotassium_data,json=bloodPotassiumData" json:"bloodPotassium_data,omitempty"`
}

func (x *HisDataHealth) Reset() {
	*x = HisDataHealth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_health_data_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisDataHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisDataHealth) ProtoMessage() {}

func (x *HisDataHealth) ProtoReflect() protoreflect.Message {
	mi := &file_his_health_data_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisDataHealth.ProtoReflect.Descriptor instead.
func (*HisDataHealth) Descriptor() ([]byte, []int) {
	return file_his_health_data_proto_rawDescGZIP(), []int{19}
}

func (x *HisDataHealth) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *HisDataHealth) GetSleepData() *HisHealthSleep {
	if x != nil {
		return x.SleepData
	}
	return nil
}

func (x *HisDataHealth) GetPedoData() *HisHealthPedo {
	if x != nil {
		return x.PedoData
	}
	return nil
}

func (x *HisDataHealth) GetHrData() *HisHealthHr {
	if x != nil {
		return x.HrData
	}
	return nil
}

func (x *HisDataHealth) GetHrvData() *HisHealthHrv {
	if x != nil {
		return x.HrvData
	}
	return nil
}

func (x *HisDataHealth) GetBpData() *HisHealthBp {
	if x != nil {
		return x.BpData
	}
	return nil
}

func (x *HisDataHealth) GetAfData() *HisHealthAf {
	if x != nil {
		return x.AfData
	}
	return nil
}

func (x *HisDataHealth) GetMdtData() *HisHealthMdt {
	if x != nil {
		return x.MdtData
	}
	return nil
}

func (x *HisDataHealth) GetMoodData() *HisHealthMood {
	if x != nil {
		return x.MoodData
	}
	return nil
}

func (x *HisDataHealth) GetBreathData() *HisHealthBreath {
	if x != nil {
		return x.BreathData
	}
	return nil
}

func (x *HisDataHealth) GetBiozData() *HisHealthBioz {
	if x != nil {
		return x.BiozData
	}
	return nil
}

func (x *HisDataHealth) GetBxoyData() *HisHealthBOxy {
	if x != nil {
		return x.BxoyData
	}
	return nil
}

func (x *HisDataHealth) GetTemperatureData() *HisHealthTemp {
	if x != nil {
		return x.TemperatureData
	}
	return nil
}

func (x *HisDataHealth) GetOutActData() *HisHealthOutAct {
	if x != nil {
		return x.OutActData
	}
	return nil
}

func (x *HisDataHealth) GetOaqData() *HisHealthOAQ {
	if x != nil {
		return x.OaqData
	}
	return nil
}

func (x *HisDataHealth) GetIaqData() *HisHealthIAQ {
	if x != nil {
		return x.IaqData
	}
	return nil
}

func (x *HisDataHealth) GetHumitureData() *HisHealthHuMiTure {
	if x != nil {
		return x.HumitureData
	}
	return nil
}

func (x *HisDataHealth) GetBloodSugarData() *HisHealthBloodSugar {
	if x != nil {
		return x.BloodSugarData
	}
	return nil
}

func (x *HisDataHealth) GetBpBpmData() *HisHealthbpBpm {
	if x != nil {
		return x.BpBpmData
	}
	return nil
}

func (x *HisDataHealth) GetBloodPotassiumData() *HisHealthbloodPotassium {
	if x != nil {
		return x.BloodPotassiumData
	}
	return nil
}

var File_his_health_data_proto protoreflect.FileDescriptor

var file_his_health_data_proto_rawDesc = []byte{
	0x0a, 0x15, 0x68, 0x69, 0x73, 0x5f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a,
	0x0d, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x50, 0x65, 0x64, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x07, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6f,
	0x72, 0x69, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x07, 0x52, 0x07, 0x63, 0x61, 0x6c, 0x6f, 0x72,
	0x69, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x04, 0x20, 0x02, 0x28, 0x07,
	0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x02, 0x28, 0x07, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x22, 0x58, 0x0a, 0x0b, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x48,
	0x72, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x5f, 0x62, 0x70, 0x6d, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x07, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x42, 0x70, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61,
	0x78, 0x5f, 0x62, 0x70, 0x6d, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x06, 0x6d, 0x61, 0x78,
	0x42, 0x70, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x76, 0x67, 0x5f, 0x62, 0x70, 0x6d, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x07, 0x52, 0x06, 0x61, 0x76, 0x67, 0x42, 0x70, 0x6d, 0x22, 0x41, 0x0a, 0x17,
	0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x62, 0x6c, 0x6f, 0x6f, 0x64, 0x50, 0x6f,
	0x74, 0x61, 0x73, 0x73, 0x69, 0x75, 0x6d, 0x12, 0x26, 0x0a, 0x0e, 0x62, 0x6c, 0x6f, 0x6f, 0x64,
	0x50, 0x6f, 0x74, 0x61, 0x73, 0x73, 0x69, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52,
	0x0e, 0x62, 0x6c, 0x6f, 0x6f, 0x64, 0x50, 0x6f, 0x74, 0x61, 0x73, 0x73, 0x69, 0x75, 0x6d, 0x22,
	0x37, 0x0a, 0x14, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x6c, 0x6f, 0x6f,
	0x64, 0x5f, 0x73, 0x75, 0x67, 0x61, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x6f, 0x64,
	0x5f, 0x73, 0x75, 0x67, 0x61, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x0a, 0x42, 0x6c,
	0x6f, 0x6f, 0x64, 0x53, 0x75, 0x67, 0x61, 0x72, 0x22, 0x2a, 0x0a, 0x0f, 0x48, 0x69, 0x73, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x4f, 0x75, 0x74, 0x41, 0x63, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6f,
	0x75, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x06, 0x6f, 0x75,
	0x74, 0x41, 0x63, 0x74, 0x22, 0x7c, 0x0a, 0x0c, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x48, 0x72, 0x76, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x44, 0x4e, 0x4e, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x02, 0x52, 0x04, 0x53, 0x44, 0x4e, 0x4e, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x4d, 0x53, 0x53,
	0x44, 0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x05, 0x52, 0x4d, 0x53, 0x53, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x50, 0x4e, 0x4e, 0x35, 0x30, 0x18, 0x03, 0x20, 0x02, 0x28, 0x02, 0x52, 0x05, 0x50,
	0x4e, 0x4e, 0x35, 0x30, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x45, 0x41, 0x4e, 0x18, 0x04, 0x20, 0x02,
	0x28, 0x02, 0x52, 0x04, 0x4d, 0x45, 0x41, 0x4e, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x74, 0x69,
	0x67, 0x75, 0x65, 0x18, 0x05, 0x20, 0x02, 0x28, 0x02, 0x52, 0x07, 0x66, 0x61, 0x74, 0x69, 0x67,
	0x75, 0x65, 0x22, 0xb6, 0x01, 0x0a, 0x0c, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x4d, 0x64, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x44, 0x4e, 0x4e, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x02, 0x52, 0x04, 0x53, 0x44, 0x4e, 0x4e, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x4d, 0x53, 0x53, 0x44,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x05, 0x52, 0x4d, 0x53, 0x53, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x50, 0x4e, 0x4e, 0x35, 0x30, 0x18, 0x03, 0x20, 0x02, 0x28, 0x02, 0x52, 0x05, 0x50, 0x4e,
	0x4e, 0x35, 0x30, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x45, 0x41, 0x4e, 0x18, 0x04, 0x20, 0x02, 0x28,
	0x02, 0x52, 0x04, 0x4d, 0x45, 0x41, 0x4e, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x05, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x48, 0x69, 0x73, 0x4d, 0x64, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x18, 0x06, 0x20, 0x02, 0x28, 0x02, 0x52, 0x06, 0x52,
	0x45, 0x53, 0x55, 0x4c, 0x54, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x45, 0x4c, 0x41, 0x58, 0x18, 0x07,
	0x20, 0x02, 0x28, 0x02, 0x52, 0x05, 0x52, 0x45, 0x4c, 0x41, 0x58, 0x22, 0x45, 0x0a, 0x0b, 0x48,
	0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x62,
	0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x03, 0x73, 0x62, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x64, 0x62, 0x70, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x03, 0x64, 0x62, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x22, 0x23, 0x0a, 0x0f, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x62,
	0x70, 0x5f, 0x62, 0x70, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x70, 0x6d, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x07, 0x52, 0x03, 0x62, 0x70, 0x6d, 0x22, 0x35, 0x0a, 0x0b, 0x48, 0x69, 0x73, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x41, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x61, 0x66, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0f, 0x52, 0x02, 0x61, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x22, 0x68,
	0x0a, 0x0e, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x6c, 0x65, 0x65, 0x70,
	0x12, 0x21, 0x0a, 0x0a, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x07, 0x42, 0x02, 0x10, 0x01, 0x52, 0x09, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x75, 0x74, 0x5f, 0x64, 0x6f, 0x77, 0x6e,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x08, 0x52, 0x08, 0x73, 0x68, 0x75, 0x74, 0x44, 0x6f, 0x77, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x08,
	0x52, 0x06, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x22, 0x2e, 0x0a, 0x0d, 0x48, 0x69, 0x73, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x4d, 0x6f, 0x6f, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x6f,
	0x64, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x09, 0x6d,
	0x6f, 0x6f, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x31, 0x0a, 0x0f, 0x48, 0x69, 0x73, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x72, 0x65, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x62,
	0x72, 0x65, 0x61, 0x74, 0x68, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52,
	0x0a, 0x62, 0x72, 0x65, 0x61, 0x74, 0x68, 0x72, 0x61, 0x74, 0x65, 0x22, 0x63, 0x0a, 0x0d, 0x48,
	0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x69, 0x6f, 0x7a, 0x12, 0x0c, 0x0a, 0x01,
	0x52, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x01, 0x52, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x01, 0x58, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x61, 0x74, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x07, 0x52, 0x03, 0x66, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x6d,
	0x69, 0x18, 0x04, 0x20, 0x02, 0x28, 0x07, 0x52, 0x03, 0x62, 0x6d, 0x69, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x02, 0x28, 0x07, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x5a, 0x0a, 0x0d, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x4f, 0x78,
	0x79, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x5f, 0x6f, 0x78, 0x79, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x07, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x4f, 0x78, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61,
	0x78, 0x5f, 0x6f, 0x78, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x06, 0x6d, 0x61, 0x78,
	0x4f, 0x78, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x67, 0x76, 0x5f, 0x6f, 0x78, 0x79, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x07, 0x52, 0x06, 0x61, 0x67, 0x76, 0x4f, 0x78, 0x79, 0x22, 0x6a, 0x0a, 0x0d,
	0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x54, 0x65, 0x6d, 0x70, 0x12, 0x23, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x54, 0x50,
	0x41, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x69, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x07, 0x52, 0x07, 0x65, 0x76, 0x69, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x19, 0x0a,
	0x08, 0x65, 0x73, 0x74, 0x69, 0x5f, 0x61, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x02, 0x28, 0x07, 0x52,
	0x07, 0x65, 0x73, 0x74, 0x69, 0x41, 0x72, 0x6d, 0x22, 0x62, 0x0a, 0x0c, 0x48, 0x69, 0x73, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x4f, 0x41, 0x51, 0x12, 0x1e, 0x0a, 0x0b, 0x4f, 0x33, 0x5f, 0x63,
	0x6f, 0x6e, 0x63, 0x5f, 0x70, 0x70, 0x62, 0x18, 0x01, 0x20, 0x02, 0x28, 0x02, 0x52, 0x09, 0x4f,
	0x33, 0x43, 0x6f, 0x6e, 0x63, 0x50, 0x70, 0x62, 0x12, 0x19, 0x0a, 0x08, 0x46, 0x41, 0x53, 0x54,
	0x5f, 0x41, 0x51, 0x49, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x07, 0x46, 0x41, 0x53, 0x54,
	0x41, 0x51, 0x49, 0x12, 0x17, 0x0a, 0x07, 0x45, 0x50, 0x41, 0x5f, 0x41, 0x51, 0x49, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x07, 0x52, 0x06, 0x45, 0x50, 0x41, 0x41, 0x51, 0x49, 0x22, 0x5c, 0x0a, 0x0c,
	0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x49, 0x41, 0x51, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x61, 0x71, 0x18, 0x01, 0x20, 0x02, 0x28, 0x02, 0x52, 0x03, 0x69, 0x61, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x76, 0x6f, 0x63, 0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x04, 0x74, 0x76,
	0x6f, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x74, 0x6f, 0x68, 0x18, 0x03, 0x20, 0x02, 0x28, 0x02,
	0x52, 0x04, 0x65, 0x74, 0x6f, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x63, 0x6f, 0x32, 0x18, 0x04,
	0x20, 0x02, 0x28, 0x02, 0x52, 0x04, 0x65, 0x63, 0x6f, 0x32, 0x22, 0x51, 0x0a, 0x11, 0x48, 0x69,
	0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x48, 0x75, 0x4d, 0x69, 0x54, 0x75, 0x72, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x48, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x02, 0x52, 0x08, 0x48, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x74,
	0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x02,
	0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xd3, 0x07,
	0x0a, 0x0d, 0x48, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12,
	0x28, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2e, 0x0a, 0x0a, 0x73, 0x6c, 0x65,
	0x65, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x52, 0x09,
	0x73, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x09, 0x70, 0x65, 0x64,
	0x6f, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x48,
	0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x50, 0x65, 0x64, 0x6f, 0x52, 0x08, 0x70, 0x65,
	0x64, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x07, 0x68, 0x72, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x48, 0x72, 0x52, 0x06, 0x68, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a,
	0x08, 0x68, 0x72, 0x76, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x48, 0x72, 0x76, 0x52, 0x07,
	0x68, 0x72, 0x76, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x07, 0x62, 0x70, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x48, 0x69, 0x73, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x42, 0x70, 0x52, 0x06, 0x62, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25,
	0x0a, 0x07, 0x61, 0x66, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x41, 0x66, 0x52, 0x06, 0x61,
	0x66, 0x44, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x08, 0x6d, 0x64, 0x74, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x4d, 0x64, 0x74, 0x52, 0x07, 0x6d, 0x64, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x2b, 0x0a, 0x09, 0x6d, 0x6f, 0x6f, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x4d, 0x6f,
	0x6f, 0x64, 0x52, 0x08, 0x6d, 0x6f, 0x6f, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x0b,
	0x62, 0x72, 0x65, 0x61, 0x74, 0x68, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x72, 0x65,
	0x61, 0x74, 0x68, 0x52, 0x0a, 0x62, 0x72, 0x65, 0x61, 0x74, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x2b, 0x0a, 0x09, 0x62, 0x69, 0x6f, 0x7a, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x69,
	0x6f, 0x7a, 0x52, 0x08, 0x62, 0x69, 0x6f, 0x7a, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x09,
	0x62, 0x78, 0x6f, 0x79, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x4f, 0x78, 0x79, 0x52,
	0x08, 0x62, 0x78, 0x6f, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x39, 0x0a, 0x10, 0x74, 0x65, 0x6d,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x54,
	0x65, 0x6d, 0x70, 0x52, 0x0f, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x0c, 0x6f, 0x75, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x48, 0x69, 0x73,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x4f, 0x75, 0x74, 0x41, 0x63, 0x74, 0x52, 0x0a, 0x6f, 0x75,
	0x74, 0x41, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x08, 0x6f, 0x61, 0x71, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x48, 0x69, 0x73,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x4f, 0x41, 0x51, 0x52, 0x07, 0x6f, 0x61, 0x71, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x28, 0x0a, 0x08, 0x69, 0x61, 0x71, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x49, 0x41, 0x51, 0x52, 0x07, 0x69, 0x61, 0x71, 0x44, 0x61, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x0d,
	0x68, 0x75, 0x6d, 0x69, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x11, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x48,
	0x75, 0x4d, 0x69, 0x54, 0x75, 0x72, 0x65, 0x52, 0x0c, 0x68, 0x75, 0x6d, 0x69, 0x74, 0x75, 0x72,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3f, 0x0a, 0x10, 0x42, 0x6c, 0x6f, 0x6f, 0x64, 0x5f, 0x73,
	0x75, 0x67, 0x61, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x6c, 0x6f, 0x6f, 0x64,
	0x5f, 0x73, 0x75, 0x67, 0x61, 0x72, 0x52, 0x0e, 0x42, 0x6c, 0x6f, 0x6f, 0x64, 0x53, 0x75, 0x67,
	0x61, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x30, 0x0a, 0x0b, 0x62, 0x70, 0x5f, 0x62, 0x70, 0x6d,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x48, 0x69,
	0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x62, 0x70, 0x5f, 0x62, 0x70, 0x6d, 0x52, 0x09, 0x62,
	0x70, 0x42, 0x70, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x49, 0x0a, 0x13, 0x62, 0x6c, 0x6f, 0x6f,
	0x64, 0x50, 0x6f, 0x74, 0x61, 0x73, 0x73, 0x69, 0x75, 0x6d, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x48, 0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x62, 0x6c, 0x6f, 0x6f, 0x64, 0x50, 0x6f, 0x74, 0x61, 0x73, 0x73, 0x69, 0x75, 0x6d, 0x52,
	0x12, 0x62, 0x6c, 0x6f, 0x6f, 0x64, 0x50, 0x6f, 0x74, 0x61, 0x73, 0x73, 0x69, 0x75, 0x6d, 0x44,
	0x61, 0x74, 0x61, 0x2a, 0x32, 0x0a, 0x0b, 0x48, 0x69, 0x73, 0x4d, 0x64, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x45, 0x50, 0x41, 0x52, 0x45, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x4f, 0x4e, 0x47, 0x4f, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x52, 0x45, 0x4c, 0x41, 0x58, 0x10, 0x02, 0x2a, 0x63, 0x0a, 0x0e, 0x54, 0x50, 0x41, 0x4d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x54, 0x50, 0x41,
	0x5f, 0x4d, 0x45, 0x41, 0x53, 0x55, 0x52, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x55,
	0x4c, 0x4c, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x54, 0x50, 0x41, 0x5f, 0x4d, 0x45, 0x41, 0x53,
	0x55, 0x52, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x55, 0x54, 0x4f, 0x10, 0x01, 0x12,
	0x1b, 0x0a, 0x17, 0x54, 0x50, 0x41, 0x5f, 0x4d, 0x45, 0x41, 0x53, 0x55, 0x52, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x41, 0x52, 0x4d, 0x50, 0x49, 0x54, 0x10, 0x02, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2f, 0x69, 0x77, 0x6f, 0x77, 0x6e,
}

var (
	file_his_health_data_proto_rawDescOnce sync.Once
	file_his_health_data_proto_rawDescData = file_his_health_data_proto_rawDesc
)

func file_his_health_data_proto_rawDescGZIP() []byte {
	file_his_health_data_proto_rawDescOnce.Do(func() {
		file_his_health_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_his_health_data_proto_rawDescData)
	})
	return file_his_health_data_proto_rawDescData
}

var file_his_health_data_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_his_health_data_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_his_health_data_proto_goTypes = []interface{}{
	(HisMdtState)(0),                // 0: HisMdtState
	(TPAMeasureType)(0),             // 1: TPAMeasureType
	(*HisHealthPedo)(nil),           // 2: HisHealthPedo
	(*HisHealthHr)(nil),             // 3: HisHealthHr
	(*HisHealthbloodPotassium)(nil), // 4: HisHealthbloodPotassium
	(*HisHealthBloodSugar)(nil),     // 5: HisHealthBlood_sugar
	(*HisHealthOutAct)(nil),         // 6: HisHealthOutAct
	(*HisHealthHrv)(nil),            // 7: HisHealthHrv
	(*HisHealthMdt)(nil),            // 8: HisHealthMdt
	(*HisHealthBp)(nil),             // 9: HisHealthBp
	(*HisHealthbpBpm)(nil),          // 10: HisHealthbp_bpm
	(*HisHealthAf)(nil),             // 11: HisHealthAf
	(*HisHealthSleep)(nil),          // 12: HisHealthSleep
	(*HisHealthMood)(nil),           // 13: HisHealthMood
	(*HisHealthBreath)(nil),         // 14: HisHealthBreath
	(*HisHealthBioz)(nil),           // 15: HisHealthBioz
	(*HisHealthBOxy)(nil),           // 16: HisHealthBOxy
	(*HisHealthTemp)(nil),           // 17: HisHealthTemp
	(*HisHealthOAQ)(nil),            // 18: HisHealthOAQ
	(*HisHealthIAQ)(nil),            // 19: HisHealthIAQ
	(*HisHealthHuMiTure)(nil),       // 20: HisHealthHuMiTure
	(*HisDataHealth)(nil),           // 21: HisDataHealth
	(*DateTime)(nil),                // 22: DateTime
}
var file_his_health_data_proto_depIdxs = []int32{
	0,  // 0: HisHealthMdt.status:type_name -> HisMdtState
	1,  // 1: HisHealthTemp.type:type_name -> TPAMeasureType
	22, // 2: HisDataHealth.time_stamp:type_name -> DateTime
	12, // 3: HisDataHealth.sleep_data:type_name -> HisHealthSleep
	2,  // 4: HisDataHealth.pedo_data:type_name -> HisHealthPedo
	3,  // 5: HisDataHealth.hr_data:type_name -> HisHealthHr
	7,  // 6: HisDataHealth.hrv_data:type_name -> HisHealthHrv
	9,  // 7: HisDataHealth.bp_data:type_name -> HisHealthBp
	11, // 8: HisDataHealth.af_data:type_name -> HisHealthAf
	8,  // 9: HisDataHealth.mdt_data:type_name -> HisHealthMdt
	13, // 10: HisDataHealth.mood_data:type_name -> HisHealthMood
	14, // 11: HisDataHealth.breath_data:type_name -> HisHealthBreath
	15, // 12: HisDataHealth.bioz_data:type_name -> HisHealthBioz
	16, // 13: HisDataHealth.bxoy_data:type_name -> HisHealthBOxy
	17, // 14: HisDataHealth.temperature_data:type_name -> HisHealthTemp
	6,  // 15: HisDataHealth.out_act_data:type_name -> HisHealthOutAct
	18, // 16: HisDataHealth.oaq_data:type_name -> HisHealthOAQ
	19, // 17: HisDataHealth.iaq_data:type_name -> HisHealthIAQ
	20, // 18: HisDataHealth.humiture_data:type_name -> HisHealthHuMiTure
	5,  // 19: HisDataHealth.Blood_sugar_data:type_name -> HisHealthBlood_sugar
	10, // 20: HisDataHealth.bp_bpm_data:type_name -> HisHealthbp_bpm
	4,  // 21: HisDataHealth.bloodPotassium_data:type_name -> HisHealthbloodPotassium
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_his_health_data_proto_init() }
func file_his_health_data_proto_init() {
	if File_his_health_data_proto != nil {
		return
	}
	file_realtime_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_his_health_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthPedo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthHr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthbloodPotassium); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthBloodSugar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthOutAct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthHrv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthMdt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthBp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthbpBpm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthAf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthSleep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthMood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthBreath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthBioz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthBOxy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthTemp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthOAQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthIAQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisHealthHuMiTure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_health_data_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisDataHealth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_his_health_data_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_his_health_data_proto_goTypes,
		DependencyIndexes: file_his_health_data_proto_depIdxs,
		EnumInfos:         file_his_health_data_proto_enumTypes,
		MessageInfos:      file_his_health_data_proto_msgTypes,
	}.Build()
	File_his_health_data_proto = out.File
	file_his_health_data_proto_rawDesc = nil
	file_his_health_data_proto_goTypes = nil
	file_his_health_data_proto_depIdxs = nil
}
