// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: his_temperature_data.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorTemp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EviBody *uint32 `protobuf:"fixed32,1,req,name=evi_body,json=eviBody" json:"evi_body,omitempty"`
	EstiArm *uint32 `protobuf:"fixed32,2,req,name=esti_arm,json=estiArm" json:"esti_arm,omitempty"`
}

func (x *SensorTemp) Reset() {
	*x = SensorTemp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_temperature_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorTemp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorTemp) ProtoMessage() {}

func (x *SensorTemp) ProtoReflect() protoreflect.Message {
	mi := &file_his_temperature_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorTemp.ProtoReflect.Descriptor instead.
func (*SensorTemp) Descriptor() ([]byte, []int) {
	return file_his_temperature_data_proto_rawDescGZIP(), []int{0}
}

func (x *SensorTemp) GetEviBody() uint32 {
	if x != nil && x.EviBody != nil {
		return *x.EviBody
	}
	return 0
}

func (x *SensorTemp) GetEstiArm() uint32 {
	if x != nil && x.EstiArm != nil {
		return *x.EstiArm
	}
	return 0
}

type HisDataTemperature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp   *DateTime   `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	Temperature *SensorTemp `protobuf:"bytes,2,req,name=temperature" json:"temperature,omitempty"`
}

func (x *HisDataTemperature) Reset() {
	*x = HisDataTemperature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_temperature_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisDataTemperature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisDataTemperature) ProtoMessage() {}

func (x *HisDataTemperature) ProtoReflect() protoreflect.Message {
	mi := &file_his_temperature_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisDataTemperature.ProtoReflect.Descriptor instead.
func (*HisDataTemperature) Descriptor() ([]byte, []int) {
	return file_his_temperature_data_proto_rawDescGZIP(), []int{1}
}

func (x *HisDataTemperature) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *HisDataTemperature) GetTemperature() *SensorTemp {
	if x != nil {
		return x.Temperature
	}
	return nil
}

var File_his_temperature_data_proto protoreflect.FileDescriptor

var file_his_temperature_data_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x68, 0x69, 0x73, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x72, 0x65,
	0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x42, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x12,
	0x19, 0x0a, 0x08, 0x65, 0x76, 0x69, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x07, 0x52, 0x07, 0x65, 0x76, 0x69, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x73,
	0x74, 0x69, 0x5f, 0x61, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x07, 0x65, 0x73,
	0x74, 0x69, 0x41, 0x72, 0x6d, 0x22, 0x6d, 0x0a, 0x12, 0x48, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x28, 0x0a, 0x0a, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2d, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x53, 0x65, 0x6e,
	0x73, 0x6f, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x69, 0x77, 0x6f, 0x77, 0x6e,
}

var (
	file_his_temperature_data_proto_rawDescOnce sync.Once
	file_his_temperature_data_proto_rawDescData = file_his_temperature_data_proto_rawDesc
)

func file_his_temperature_data_proto_rawDescGZIP() []byte {
	file_his_temperature_data_proto_rawDescOnce.Do(func() {
		file_his_temperature_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_his_temperature_data_proto_rawDescData)
	})
	return file_his_temperature_data_proto_rawDescData
}

var file_his_temperature_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_his_temperature_data_proto_goTypes = []interface{}{
	(*SensorTemp)(nil),         // 0: SensorTemp
	(*HisDataTemperature)(nil), // 1: HisDataTemperature
	(*DateTime)(nil),           // 2: DateTime
}
var file_his_temperature_data_proto_depIdxs = []int32{
	2, // 0: HisDataTemperature.time_stamp:type_name -> DateTime
	0, // 1: HisDataTemperature.temperature:type_name -> SensorTemp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_his_temperature_data_proto_init() }
func file_his_temperature_data_proto_init() {
	if File_his_temperature_data_proto != nil {
		return
	}
	file_realtime_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_his_temperature_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensorTemp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_temperature_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisDataTemperature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_his_temperature_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_his_temperature_data_proto_goTypes,
		DependencyIndexes: file_his_temperature_data_proto_depIdxs,
		MessageInfos:      file_his_temperature_data_proto_msgTypes,
	}.Build()
	File_his_temperature_data_proto = out.File
	file_his_temperature_data_proto_rawDesc = nil
	file_his_temperature_data_proto_goTypes = nil
	file_his_temperature_data_proto_depIdxs = nil
}
