// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: his_rri_data_v2.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HisDataRRIV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp *DateTime `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	RawData   []byte    `protobuf:"bytes,2,req,name=raw_data,json=rawData" json:"raw_data,omitempty"`
}

func (x *HisDataRRIV2) Reset() {
	*x = HisDataRRIV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_rri_data_v2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisDataRRIV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisDataRRIV2) ProtoMessage() {}

func (x *HisDataRRIV2) ProtoReflect() protoreflect.Message {
	mi := &file_his_rri_data_v2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisDataRRIV2.ProtoReflect.Descriptor instead.
func (*HisDataRRIV2) Descriptor() ([]byte, []int) {
	return file_his_rri_data_v2_proto_rawDescGZIP(), []int{0}
}

func (x *HisDataRRIV2) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *HisDataRRIV2) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

var File_his_rri_data_v2_proto protoreflect.FileDescriptor

var file_his_rri_data_v2_proto_rawDesc = []byte{
	0x0a, 0x15, 0x68, 0x69, 0x73, 0x5f, 0x72, 0x72, 0x69, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x76,
	0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x0d,
	0x48, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x52, 0x49, 0x5f, 0x76, 0x32, 0x12, 0x28, 0x0a,
	0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x77, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x61, 0x77, 0x44, 0x61,
	0x74, 0x61, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x69, 0x77, 0x6f, 0x77, 0x6e,
}

var (
	file_his_rri_data_v2_proto_rawDescOnce sync.Once
	file_his_rri_data_v2_proto_rawDescData = file_his_rri_data_v2_proto_rawDesc
)

func file_his_rri_data_v2_proto_rawDescGZIP() []byte {
	file_his_rri_data_v2_proto_rawDescOnce.Do(func() {
		file_his_rri_data_v2_proto_rawDescData = protoimpl.X.CompressGZIP(file_his_rri_data_v2_proto_rawDescData)
	})
	return file_his_rri_data_v2_proto_rawDescData
}

var file_his_rri_data_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_his_rri_data_v2_proto_goTypes = []interface{}{
	(*HisDataRRIV2)(nil), // 0: HisDataRRI_v2
	(*DateTime)(nil),     // 1: DateTime
}
var file_his_rri_data_v2_proto_depIdxs = []int32{
	1, // 0: HisDataRRI_v2.time_stamp:type_name -> DateTime
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_his_rri_data_v2_proto_init() }
func file_his_rri_data_v2_proto_init() {
	if File_his_rri_data_v2_proto != nil {
		return
	}
	file_realtime_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_his_rri_data_v2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisDataRRIV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_his_rri_data_v2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_his_rri_data_v2_proto_goTypes,
		DependencyIndexes: file_his_rri_data_v2_proto_depIdxs,
		MessageInfos:      file_his_rri_data_v2_proto_msgTypes,
	}.Build()
	File_his_rri_data_v2_proto = out.File
	file_his_rri_data_v2_proto_rawDesc = nil
	file_his_rri_data_v2_proto_goTypes = nil
	file_his_rri_data_v2_proto_depIdxs = nil
}
