// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: his_medic_data.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HisDataMedic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp    *DateTime `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	PainLevel    *uint32   `protobuf:"fixed32,2,opt,name=pain_level,json=painLevel" json:"pain_level,omitempty"`
	FatigueLevel *uint32   `protobuf:"fixed32,3,opt,name=fatigue_level,json=fatigueLevel" json:"fatigue_level,omitempty"`
	StiffLevel   *uint32   `protobuf:"fixed32,4,opt,name=stiff_level,json=stiffLevel" json:"stiff_level,omitempty"`
	StiffTime    *uint32   `protobuf:"fixed32,5,opt,name=stiff_time,json=stiffTime" json:"stiff_time,omitempty"`
}

func (x *HisDataMedic) Reset() {
	*x = HisDataMedic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_medic_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisDataMedic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisDataMedic) ProtoMessage() {}

func (x *HisDataMedic) ProtoReflect() protoreflect.Message {
	mi := &file_his_medic_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisDataMedic.ProtoReflect.Descriptor instead.
func (*HisDataMedic) Descriptor() ([]byte, []int) {
	return file_his_medic_data_proto_rawDescGZIP(), []int{0}
}

func (x *HisDataMedic) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *HisDataMedic) GetPainLevel() uint32 {
	if x != nil && x.PainLevel != nil {
		return *x.PainLevel
	}
	return 0
}

func (x *HisDataMedic) GetFatigueLevel() uint32 {
	if x != nil && x.FatigueLevel != nil {
		return *x.FatigueLevel
	}
	return 0
}

func (x *HisDataMedic) GetStiffLevel() uint32 {
	if x != nil && x.StiffLevel != nil {
		return *x.StiffLevel
	}
	return 0
}

func (x *HisDataMedic) GetStiffTime() uint32 {
	if x != nil && x.StiffTime != nil {
		return *x.StiffTime
	}
	return 0
}

var File_his_medic_data_proto protoreflect.FileDescriptor

var file_his_medic_data_proto_rawDesc = []byte{
	0x0a, 0x14, 0x68, 0x69, 0x73, 0x5f, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x01, 0x0a, 0x0c,
	0x48, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x12, 0x28, 0x0a, 0x0a,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x69, 0x6e, 0x5f, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x09, 0x70, 0x61, 0x69, 0x6e,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x61, 0x74, 0x69, 0x67, 0x75, 0x65,
	0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0c, 0x66, 0x61,
	0x74, 0x69, 0x67, 0x75, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74,
	0x69, 0x66, 0x66, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x07, 0x52,
	0x0a, 0x73, 0x74, 0x69, 0x66, 0x66, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x74, 0x69, 0x66, 0x66, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x07, 0x52,
	0x09, 0x73, 0x74, 0x69, 0x66, 0x66, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x69, 0x77, 0x6f, 0x77, 0x6e,
}

var (
	file_his_medic_data_proto_rawDescOnce sync.Once
	file_his_medic_data_proto_rawDescData = file_his_medic_data_proto_rawDesc
)

func file_his_medic_data_proto_rawDescGZIP() []byte {
	file_his_medic_data_proto_rawDescOnce.Do(func() {
		file_his_medic_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_his_medic_data_proto_rawDescData)
	})
	return file_his_medic_data_proto_rawDescData
}

var file_his_medic_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_his_medic_data_proto_goTypes = []interface{}{
	(*HisDataMedic)(nil), // 0: HisDataMedic
	(*DateTime)(nil),     // 1: DateTime
}
var file_his_medic_data_proto_depIdxs = []int32{
	1, // 0: HisDataMedic.time_stamp:type_name -> DateTime
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_his_medic_data_proto_init() }
func file_his_medic_data_proto_init() {
	if File_his_medic_data_proto != nil {
		return
	}
	file_realtime_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_his_medic_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisDataMedic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_his_medic_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_his_medic_data_proto_goTypes,
		DependencyIndexes: file_his_medic_data_proto_depIdxs,
		MessageInfos:      file_his_medic_data_proto_msgTypes,
	}.Build()
	File_his_medic_data_proto = out.File
	file_his_medic_data_proto_rawDesc = nil
	file_his_medic_data_proto_goTypes = nil
	file_his_medic_data_proto_depIdxs = nil
}
