// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: his_encrypt_ecg_data.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HisECGEncrypt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ecgencrypt *HisDataECG `protobuf:"bytes,1,req,name=ecgencrypt" json:"ecgencrypt,omitempty"`
	Random     []byte      `protobuf:"bytes,2,req,name=Random" json:"Random,omitempty"` //random number
	BleMac     []byte      `protobuf:"bytes,3,req,name=BleMac" json:"BleMac,omitempty"`
}

func (x *HisECGEncrypt) Reset() {
	*x = HisECGEncrypt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_encrypt_ecg_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisECGEncrypt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisECGEncrypt) ProtoMessage() {}

func (x *HisECGEncrypt) ProtoReflect() protoreflect.Message {
	mi := &file_his_encrypt_ecg_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisECGEncrypt.ProtoReflect.Descriptor instead.
func (*HisECGEncrypt) Descriptor() ([]byte, []int) {
	return file_his_encrypt_ecg_data_proto_rawDescGZIP(), []int{0}
}

func (x *HisECGEncrypt) GetEcgencrypt() *HisDataECG {
	if x != nil {
		return x.Ecgencrypt
	}
	return nil
}

func (x *HisECGEncrypt) GetRandom() []byte {
	if x != nil {
		return x.Random
	}
	return nil
}

func (x *HisECGEncrypt) GetBleMac() []byte {
	if x != nil {
		return x.BleMac
	}
	return nil
}

type HisDataECGEncrypt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HisEcg        *HisECGEncrypt `protobuf:"bytes,1,req,name=his_ecg,json=hisEcg" json:"his_ecg,omitempty"`
	SignatureData []byte         `protobuf:"bytes,2,req,name=signature_data,json=signatureData" json:"signature_data,omitempty"`
}

func (x *HisDataECGEncrypt) Reset() {
	*x = HisDataECGEncrypt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_encrypt_ecg_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisDataECGEncrypt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisDataECGEncrypt) ProtoMessage() {}

func (x *HisDataECGEncrypt) ProtoReflect() protoreflect.Message {
	mi := &file_his_encrypt_ecg_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisDataECGEncrypt.ProtoReflect.Descriptor instead.
func (*HisDataECGEncrypt) Descriptor() ([]byte, []int) {
	return file_his_encrypt_ecg_data_proto_rawDescGZIP(), []int{1}
}

func (x *HisDataECGEncrypt) GetHisEcg() *HisECGEncrypt {
	if x != nil {
		return x.HisEcg
	}
	return nil
}

func (x *HisDataECGEncrypt) GetSignatureData() []byte {
	if x != nil {
		return x.SignatureData
	}
	return nil
}

var File_his_encrypt_ecg_data_proto protoreflect.FileDescriptor

var file_his_encrypt_ecg_data_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x68, 0x69, 0x73, 0x5f, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x5f, 0x65, 0x63,
	0x67, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x72, 0x65,
	0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x12, 0x68, 0x69, 0x73, 0x5f, 0x65, 0x63, 0x67, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x0d, 0x48, 0x69, 0x73, 0x45, 0x43, 0x47, 0x45,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x12, 0x2b, 0x0a, 0x0a, 0x65, 0x63, 0x67, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x48, 0x69, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x45, 0x43, 0x47, 0x52, 0x0a, 0x65, 0x63, 0x67, 0x65, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x0c, 0x52, 0x06, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x42,
	0x6c, 0x65, 0x4d, 0x61, 0x63, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x06, 0x42, 0x6c, 0x65,
	0x4d, 0x61, 0x63, 0x22, 0x63, 0x0a, 0x11, 0x48, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x45, 0x43,
	0x47, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x12, 0x27, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x5f,
	0x65, 0x63, 0x67, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x48, 0x69, 0x73, 0x45,
	0x43, 0x47, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x06, 0x68, 0x69, 0x73, 0x45, 0x63,
	0x67, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x0d, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x69, 0x77,
	0x6f, 0x77, 0x6e,
}

var (
	file_his_encrypt_ecg_data_proto_rawDescOnce sync.Once
	file_his_encrypt_ecg_data_proto_rawDescData = file_his_encrypt_ecg_data_proto_rawDesc
)

func file_his_encrypt_ecg_data_proto_rawDescGZIP() []byte {
	file_his_encrypt_ecg_data_proto_rawDescOnce.Do(func() {
		file_his_encrypt_ecg_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_his_encrypt_ecg_data_proto_rawDescData)
	})
	return file_his_encrypt_ecg_data_proto_rawDescData
}

var file_his_encrypt_ecg_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_his_encrypt_ecg_data_proto_goTypes = []interface{}{
	(*HisECGEncrypt)(nil),     // 0: HisECGEncrypt
	(*HisDataECGEncrypt)(nil), // 1: HisDataECGEncrypt
	(*HisDataECG)(nil),        // 2: HisDataECG
}
var file_his_encrypt_ecg_data_proto_depIdxs = []int32{
	2, // 0: HisECGEncrypt.ecgencrypt:type_name -> HisDataECG
	0, // 1: HisDataECGEncrypt.his_ecg:type_name -> HisECGEncrypt
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_his_encrypt_ecg_data_proto_init() }
func file_his_encrypt_ecg_data_proto_init() {
	if File_his_encrypt_ecg_data_proto != nil {
		return
	}
	file_realtime_data_proto_init()
	file_his_ecg_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_his_encrypt_ecg_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisECGEncrypt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_encrypt_ecg_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisDataECGEncrypt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_his_encrypt_ecg_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_his_encrypt_ecg_data_proto_goTypes,
		DependencyIndexes: file_his_encrypt_ecg_data_proto_depIdxs,
		MessageInfos:      file_his_encrypt_ecg_data_proto_msgTypes,
	}.Build()
	File_his_encrypt_ecg_data_proto = out.File
	file_his_encrypt_ecg_data_proto_rawDesc = nil
	file_his_encrypt_ecg_data_proto_goTypes = nil
	file_his_encrypt_ecg_data_proto_depIdxs = nil
}
