// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: his_gnss_data.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HisDataGNSS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp *DateTime `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	Frequency *uint32   `protobuf:"fixed32,2,req,name=frequency" json:"frequency,omitempty"`
	Gnss      []*RtGNSS `protobuf:"bytes,3,rep,name=gnss" json:"gnss,omitempty"`
}

func (x *HisDataGNSS) Reset() {
	*x = HisDataGNSS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_gnss_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisDataGNSS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisDataGNSS) ProtoMessage() {}

func (x *HisDataGNSS) ProtoReflect() protoreflect.Message {
	mi := &file_his_gnss_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisDataGNSS.ProtoReflect.Descriptor instead.
func (*HisDataGNSS) Descriptor() ([]byte, []int) {
	return file_his_gnss_data_proto_rawDescGZIP(), []int{0}
}

func (x *HisDataGNSS) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *HisDataGNSS) GetFrequency() uint32 {
	if x != nil && x.Frequency != nil {
		return *x.Frequency
	}
	return 0
}

func (x *HisDataGNSS) GetGnss() []*RtGNSS {
	if x != nil {
		return x.Gnss
	}
	return nil
}

var File_his_gnss_data_proto protoreflect.FileDescriptor

var file_his_gnss_data_proto_rawDesc = []byte{
	0x0a, 0x13, 0x68, 0x69, 0x73, 0x5f, 0x67, 0x6e, 0x73, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x0b, 0x48, 0x69,
	0x73, 0x44, 0x61, 0x74, 0x61, 0x47, 0x4e, 0x53, 0x53, 0x12, 0x28, 0x0a, 0x0a, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x79, 0x12, 0x1b, 0x0a, 0x04, 0x67, 0x6e, 0x73, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x52, 0x74, 0x47, 0x4e, 0x53, 0x53, 0x52, 0x04, 0x67, 0x6e, 0x73, 0x73, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x69, 0x77, 0x6f, 0x77, 0x6e,
}

var (
	file_his_gnss_data_proto_rawDescOnce sync.Once
	file_his_gnss_data_proto_rawDescData = file_his_gnss_data_proto_rawDesc
)

func file_his_gnss_data_proto_rawDescGZIP() []byte {
	file_his_gnss_data_proto_rawDescOnce.Do(func() {
		file_his_gnss_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_his_gnss_data_proto_rawDescData)
	})
	return file_his_gnss_data_proto_rawDescData
}

var file_his_gnss_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_his_gnss_data_proto_goTypes = []interface{}{
	(*HisDataGNSS)(nil), // 0: HisDataGNSS
	(*DateTime)(nil),    // 1: DateTime
	(*RtGNSS)(nil),      // 2: RtGNSS
}
var file_his_gnss_data_proto_depIdxs = []int32{
	1, // 0: HisDataGNSS.time_stamp:type_name -> DateTime
	2, // 1: HisDataGNSS.gnss:type_name -> RtGNSS
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_his_gnss_data_proto_init() }
func file_his_gnss_data_proto_init() {
	if File_his_gnss_data_proto != nil {
		return
	}
	file_realtime_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_his_gnss_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisDataGNSS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_his_gnss_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_his_gnss_data_proto_goTypes,
		DependencyIndexes: file_his_gnss_data_proto_depIdxs,
		MessageInfos:      file_his_gnss_data_proto_msgTypes,
	}.Build()
	File_his_gnss_data_proto = out.File
	file_his_gnss_data_proto_rawDesc = nil
	file_his_gnss_data_proto_goTypes = nil
	file_his_gnss_data_proto_depIdxs = nil
}
