// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: his_swim_data.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorVec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *uint32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y *uint32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	Z *uint32 `protobuf:"fixed32,3,req,name=z" json:"z,omitempty"`
}

func (x *SensorVec) Reset() {
	*x = SensorVec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_swim_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorVec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorVec) ProtoMessage() {}

func (x *SensorVec) ProtoReflect() protoreflect.Message {
	mi := &file_his_swim_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorVec.ProtoReflect.Descriptor instead.
func (*SensorVec) Descriptor() ([]byte, []int) {
	return file_his_swim_data_proto_rawDescGZIP(), []int{0}
}

func (x *SensorVec) GetX() uint32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *SensorVec) GetY() uint32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *SensorVec) GetZ() uint32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

type HisDataSwim struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp   *DateTime    `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	AccGyroData []*SensorVec `protobuf:"bytes,2,rep,name=acc_gyro_data,json=accGyroData" json:"acc_gyro_data,omitempty"`
	MagData     *SensorVec   `protobuf:"bytes,3,req,name=mag_data,json=magData" json:"mag_data,omitempty"`
}

func (x *HisDataSwim) Reset() {
	*x = HisDataSwim{}
	if protoimpl.UnsafeEnabled {
		mi := &file_his_swim_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisDataSwim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisDataSwim) ProtoMessage() {}

func (x *HisDataSwim) ProtoReflect() protoreflect.Message {
	mi := &file_his_swim_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisDataSwim.ProtoReflect.Descriptor instead.
func (*HisDataSwim) Descriptor() ([]byte, []int) {
	return file_his_swim_data_proto_rawDescGZIP(), []int{1}
}

func (x *HisDataSwim) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *HisDataSwim) GetAccGyroData() []*SensorVec {
	if x != nil {
		return x.AccGyroData
	}
	return nil
}

func (x *HisDataSwim) GetMagData() *SensorVec {
	if x != nil {
		return x.MagData
	}
	return nil
}

var File_his_swim_data_proto protoreflect.FileDescriptor

var file_his_swim_data_proto_rawDesc = []byte{
	0x0a, 0x13, 0x68, 0x69, 0x73, 0x5f, 0x73, 0x77, 0x69, 0x6d, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x09, 0x53, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x56, 0x65, 0x63, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x07, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07,
	0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x02, 0x28, 0x07, 0x52, 0x01,
	0x7a, 0x22, 0x8e, 0x01, 0x0a, 0x0b, 0x48, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x53, 0x77, 0x69,
	0x6d, 0x12, 0x28, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2e, 0x0a, 0x0d, 0x61,
	0x63, 0x63, 0x5f, 0x67, 0x79, 0x72, 0x6f, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x56, 0x65, 0x63, 0x52, 0x0b,
	0x61, 0x63, 0x63, 0x47, 0x79, 0x72, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x08, 0x6d,
	0x61, 0x67, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x56, 0x65, 0x63, 0x52, 0x07, 0x6d, 0x61, 0x67, 0x44, 0x61,
	0x74, 0x61, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x69, 0x77, 0x6f, 0x77, 0x6e,
}

var (
	file_his_swim_data_proto_rawDescOnce sync.Once
	file_his_swim_data_proto_rawDescData = file_his_swim_data_proto_rawDesc
)

func file_his_swim_data_proto_rawDescGZIP() []byte {
	file_his_swim_data_proto_rawDescOnce.Do(func() {
		file_his_swim_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_his_swim_data_proto_rawDescData)
	})
	return file_his_swim_data_proto_rawDescData
}

var file_his_swim_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_his_swim_data_proto_goTypes = []interface{}{
	(*SensorVec)(nil),   // 0: SensorVec
	(*HisDataSwim)(nil), // 1: HisDataSwim
	(*DateTime)(nil),    // 2: DateTime
}
var file_his_swim_data_proto_depIdxs = []int32{
	2, // 0: HisDataSwim.time_stamp:type_name -> DateTime
	0, // 1: HisDataSwim.acc_gyro_data:type_name -> SensorVec
	0, // 2: HisDataSwim.mag_data:type_name -> SensorVec
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_his_swim_data_proto_init() }
func file_his_swim_data_proto_init() {
	if File_his_swim_data_proto != nil {
		return
	}
	file_realtime_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_his_swim_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensorVec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_his_swim_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisDataSwim); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_his_swim_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_his_swim_data_proto_goTypes,
		DependencyIndexes: file_his_swim_data_proto_depIdxs,
		MessageInfos:      file_his_swim_data_proto_msgTypes,
	}.Build()
	File_his_swim_data_proto = out.File
	file_his_swim_data_proto_rawDesc = nil
	file_his_swim_data_proto_goTypes = nil
	file_his_swim_data_proto_depIdxs = nil
}
