// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: om0_command.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mc30Powermode int32

const (
	Mc30Powermode_HIGH Mc30Powermode = 0
	Mc30Powermode_MID  Mc30Powermode = 1
	Mc30Powermode_LOW  Mc30Powermode = 2
)

// Enum value maps for Mc30Powermode.
var (
	Mc30Powermode_name = map[int32]string{
		0: "HIGH",
		1: "MID",
		2: "LOW",
	}
	Mc30Powermode_value = map[string]int32{
		"HIGH": 0,
		"MID":  1,
		"LOW":  2,
	}
)

func (x Mc30Powermode) Enum() *Mc30Powermode {
	p := new(Mc30Powermode)
	*p = x
	return p
}

func (x Mc30Powermode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mc30Powermode) Descriptor() protoreflect.EnumDescriptor {
	return file_om0_command_proto_enumTypes[0].Descriptor()
}

func (Mc30Powermode) Type() protoreflect.EnumType {
	return &file_om0_command_proto_enumTypes[0]
}

func (x Mc30Powermode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Mc30Powermode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Mc30Powermode(num)
	return nil
}

// Deprecated: Use Mc30Powermode.Descriptor instead.
func (Mc30Powermode) EnumDescriptor() ([]byte, []int) {
	return file_om0_command_proto_rawDescGZIP(), []int{0}
}

type GPSTYPE int32

const (
	GPSTYPE_NULL      GPSTYPE = 0
	GPSTYPE_TYPE_BTS  GPSTYPE = 1
	GPSTYPE_TYPE_WIFI GPSTYPE = 2
	GPSTYPE_TYPE_GPS  GPSTYPE = 3
)

// Enum value maps for GPSTYPE.
var (
	GPSTYPE_name = map[int32]string{
		0: "NULL",
		1: "TYPE_BTS",
		2: "TYPE_WIFI",
		3: "TYPE_GPS",
	}
	GPSTYPE_value = map[string]int32{
		"NULL":      0,
		"TYPE_BTS":  1,
		"TYPE_WIFI": 2,
		"TYPE_GPS":  3,
	}
)

func (x GPSTYPE) Enum() *GPSTYPE {
	p := new(GPSTYPE)
	*p = x
	return p
}

func (x GPSTYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GPSTYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_om0_command_proto_enumTypes[1].Descriptor()
}

func (GPSTYPE) Type() protoreflect.EnumType {
	return &file_om0_command_proto_enumTypes[1]
}

func (x GPSTYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *GPSTYPE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = GPSTYPE(num)
	return nil
}

// Deprecated: Use GPSTYPE.Descriptor instead.
func (GPSTYPE) EnumDescriptor() ([]byte, []int) {
	return file_om0_command_proto_rawDescGZIP(), []int{1}
}

type OM0TrackConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash                *uint32        `protobuf:"fixed32,1,req,name=hash" json:"hash,omitempty"`
	AutoRun             *bool          `protobuf:"varint,2,req,name=auto_run,json=autoRun" json:"auto_run,omitempty"`
	Interval            *uint32        `protobuf:"fixed32,3,req,name=interval,def=30" json:"interval,omitempty"`
	Model               *string        `protobuf:"bytes,4,opt,name=model" json:"model,omitempty"`
	Version             *string        `protobuf:"bytes,5,opt,name=version" json:"version,omitempty"`
	ForceUpgrade        *bool          `protobuf:"varint,6,opt,name=force_upgrade,json=forceUpgrade" json:"force_upgrade,omitempty"`
	Mc30PowerMode       *Mc30Powermode `protobuf:"varint,7,opt,name=mc30_power_mode,json=mc30PowerMode,enum=Mc30Powermode" json:"mc30_power_mode,omitempty"`
	GpsAutoCheck        *bool          `protobuf:"varint,8,opt,name=gps_auto_check,json=gpsAutoCheck" json:"gps_auto_check,omitempty"`
	GpsIntervalTime     *uint32        `protobuf:"fixed32,9,opt,name=gps_interval_time,json=gpsIntervalTime" json:"gps_interval_time,omitempty"`
	GPSLocatesEveryTime *bool          `protobuf:"varint,10,opt,name=GPS_locates_every_time,json=GPSLocatesEveryTime" json:"GPS_locates_every_time,omitempty"`
}

// Default values for OM0TrackConf fields.
const (
	Default_OM0TrackConf_Interval = uint32(30)
)

func (x *OM0TrackConf) Reset() {
	*x = OM0TrackConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_om0_command_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OM0TrackConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OM0TrackConf) ProtoMessage() {}

func (x *OM0TrackConf) ProtoReflect() protoreflect.Message {
	mi := &file_om0_command_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OM0TrackConf.ProtoReflect.Descriptor instead.
func (*OM0TrackConf) Descriptor() ([]byte, []int) {
	return file_om0_command_proto_rawDescGZIP(), []int{0}
}

func (x *OM0TrackConf) GetHash() uint32 {
	if x != nil && x.Hash != nil {
		return *x.Hash
	}
	return 0
}

func (x *OM0TrackConf) GetAutoRun() bool {
	if x != nil && x.AutoRun != nil {
		return *x.AutoRun
	}
	return false
}

func (x *OM0TrackConf) GetInterval() uint32 {
	if x != nil && x.Interval != nil {
		return *x.Interval
	}
	return Default_OM0TrackConf_Interval
}

func (x *OM0TrackConf) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *OM0TrackConf) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *OM0TrackConf) GetForceUpgrade() bool {
	if x != nil && x.ForceUpgrade != nil {
		return *x.ForceUpgrade
	}
	return false
}

func (x *OM0TrackConf) GetMc30PowerMode() Mc30Powermode {
	if x != nil && x.Mc30PowerMode != nil {
		return *x.Mc30PowerMode
	}
	return Mc30Powermode_HIGH
}

func (x *OM0TrackConf) GetGpsAutoCheck() bool {
	if x != nil && x.GpsAutoCheck != nil {
		return *x.GpsAutoCheck
	}
	return false
}

func (x *OM0TrackConf) GetGpsIntervalTime() uint32 {
	if x != nil && x.GpsIntervalTime != nil {
		return *x.GpsIntervalTime
	}
	return 0
}

func (x *OM0TrackConf) GetGPSLocatesEveryTime() bool {
	if x != nil && x.GPSLocatesEveryTime != nil {
		return *x.GPSLocatesEveryTime
	}
	return false
}

type OM0SleepData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SleepDate          *RtTime `protobuf:"bytes,1,req,name=sleep_date,json=sleepDate" json:"sleep_date,omitempty"`                                 // date of sleep data
	StartTime          *RtTime `protobuf:"bytes,2,req,name=start_time,json=startTime" json:"start_time,omitempty"`                                 // sleep start time
	EndTime            *RtTime `protobuf:"bytes,3,req,name=end_time,json=endTime" json:"end_time,omitempty"`                                       // sleep end time
	DeepSleep          *uint32 `protobuf:"fixed32,4,req,name=deep_sleep,json=deepSleep" json:"deep_sleep,omitempty"`                               // minutes
	LightSleep         *uint32 `protobuf:"fixed32,5,req,name=light_sleep,json=lightSleep" json:"light_sleep,omitempty"`                            // minutes
	WeakSleep          *uint32 `protobuf:"fixed32,6,req,name=weak_sleep,json=weakSleep" json:"weak_sleep,omitempty"`                               // minutes
	EyemoveSleep       *uint32 `protobuf:"fixed32,7,req,name=eyemove_sleep,json=eyemoveSleep" json:"eyemove_sleep,omitempty"`                      // minutes
	Score              *uint32 `protobuf:"fixed32,8,req,name=score" json:"score,omitempty"`                                                        // minutes
	OsahsRisk          *uint32 `protobuf:"fixed32,9,req,name=osahs_risk,json=osahsRisk" json:"osahs_risk,omitempty"`                               // minutes
	Spo2Score          *uint32 `protobuf:"fixed32,10,req,name=spo2_score,json=spo2Score" json:"spo2_score,omitempty"`                              // minutes
	AvgRespirationRate *uint32 `protobuf:"fixed32,11,req,name=avg_respiration_rate,json=avgRespirationRate" json:"avg_respiration_rate,omitempty"` // minutes
	MaxRespirationRate *uint32 `protobuf:"fixed32,12,req,name=max_respiration_rate,json=maxRespirationRate" json:"max_respiration_rate,omitempty"` // minutes
	MinRespirationRate *uint32 `protobuf:"fixed32,13,req,name=min_respiration_rate,json=minRespirationRate" json:"min_respiration_rate,omitempty"` // minutes
	SleepHr            *uint32 `protobuf:"fixed32,14,req,name=sleep_hr,json=sleepHr" json:"sleep_hr,omitempty"`                                    // minutes
	Completed          *uint32 `protobuf:"fixed32,15,req,name=completed" json:"completed,omitempty"`                                               // minutes
}

func (x *OM0SleepData) Reset() {
	*x = OM0SleepData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_om0_command_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OM0SleepData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OM0SleepData) ProtoMessage() {}

func (x *OM0SleepData) ProtoReflect() protoreflect.Message {
	mi := &file_om0_command_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OM0SleepData.ProtoReflect.Descriptor instead.
func (*OM0SleepData) Descriptor() ([]byte, []int) {
	return file_om0_command_proto_rawDescGZIP(), []int{1}
}

func (x *OM0SleepData) GetSleepDate() *RtTime {
	if x != nil {
		return x.SleepDate
	}
	return nil
}

func (x *OM0SleepData) GetStartTime() *RtTime {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *OM0SleepData) GetEndTime() *RtTime {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *OM0SleepData) GetDeepSleep() uint32 {
	if x != nil && x.DeepSleep != nil {
		return *x.DeepSleep
	}
	return 0
}

func (x *OM0SleepData) GetLightSleep() uint32 {
	if x != nil && x.LightSleep != nil {
		return *x.LightSleep
	}
	return 0
}

func (x *OM0SleepData) GetWeakSleep() uint32 {
	if x != nil && x.WeakSleep != nil {
		return *x.WeakSleep
	}
	return 0
}

func (x *OM0SleepData) GetEyemoveSleep() uint32 {
	if x != nil && x.EyemoveSleep != nil {
		return *x.EyemoveSleep
	}
	return 0
}

func (x *OM0SleepData) GetScore() uint32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *OM0SleepData) GetOsahsRisk() uint32 {
	if x != nil && x.OsahsRisk != nil {
		return *x.OsahsRisk
	}
	return 0
}

func (x *OM0SleepData) GetSpo2Score() uint32 {
	if x != nil && x.Spo2Score != nil {
		return *x.Spo2Score
	}
	return 0
}

func (x *OM0SleepData) GetAvgRespirationRate() uint32 {
	if x != nil && x.AvgRespirationRate != nil {
		return *x.AvgRespirationRate
	}
	return 0
}

func (x *OM0SleepData) GetMaxRespirationRate() uint32 {
	if x != nil && x.MaxRespirationRate != nil {
		return *x.MaxRespirationRate
	}
	return 0
}

func (x *OM0SleepData) GetMinRespirationRate() uint32 {
	if x != nil && x.MinRespirationRate != nil {
		return *x.MinRespirationRate
	}
	return 0
}

func (x *OM0SleepData) GetSleepHr() uint32 {
	if x != nil && x.SleepHr != nil {
		return *x.SleepHr
	}
	return 0
}

func (x *OM0SleepData) GetCompleted() uint32 {
	if x != nil && x.Completed != nil {
		return *x.Completed
	}
	return 0
}

type OM0Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackConf *OM0TrackConf `protobuf:"bytes,1,opt,name=track_conf,json=trackConf" json:"track_conf,omitempty"`
	SleepData *OM0SleepData `protobuf:"bytes,2,opt,name=sleep_data,json=sleepData" json:"sleep_data,omitempty"`
}

func (x *OM0Command) Reset() {
	*x = OM0Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_om0_command_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OM0Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OM0Command) ProtoMessage() {}

func (x *OM0Command) ProtoReflect() protoreflect.Message {
	mi := &file_om0_command_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OM0Command.ProtoReflect.Descriptor instead.
func (*OM0Command) Descriptor() ([]byte, []int) {
	return file_om0_command_proto_rawDescGZIP(), []int{2}
}

func (x *OM0Command) GetTrackConf() *OM0TrackConf {
	if x != nil {
		return x.TrackConf
	}
	return nil
}

func (x *OM0Command) GetSleepData() *OM0SleepData {
	if x != nil {
		return x.SleepData
	}
	return nil
}

type OM0TrackData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time    *DateTime `protobuf:"bytes,1,req,name=time" json:"time,omitempty"`
	Gnss    *RtGNSS   `protobuf:"bytes,2,opt,name=gnss" json:"gnss,omitempty"`
	Hr      *uint32   `protobuf:"fixed32,3,opt,name=hr" json:"hr,omitempty"`
	GpsType *GPSTYPE  `protobuf:"varint,4,opt,name=gps_type,json=gpsType,enum=GPSTYPE" json:"gps_type,omitempty"`
}

func (x *OM0TrackData) Reset() {
	*x = OM0TrackData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_om0_command_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OM0TrackData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OM0TrackData) ProtoMessage() {}

func (x *OM0TrackData) ProtoReflect() protoreflect.Message {
	mi := &file_om0_command_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OM0TrackData.ProtoReflect.Descriptor instead.
func (*OM0TrackData) Descriptor() ([]byte, []int) {
	return file_om0_command_proto_rawDescGZIP(), []int{3}
}

func (x *OM0TrackData) GetTime() *DateTime {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *OM0TrackData) GetGnss() *RtGNSS {
	if x != nil {
		return x.Gnss
	}
	return nil
}

func (x *OM0TrackData) GetHr() uint32 {
	if x != nil && x.Hr != nil {
		return *x.Hr
	}
	return 0
}

func (x *OM0TrackData) GetGpsType() GPSTYPE {
	if x != nil && x.GpsType != nil {
		return *x.GpsType
	}
	return GPSTYPE_NULL
}

type OM0Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *bool `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
}

func (x *OM0Response) Reset() {
	*x = OM0Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_om0_command_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OM0Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OM0Response) ProtoMessage() {}

func (x *OM0Response) ProtoReflect() protoreflect.Message {
	mi := &file_om0_command_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OM0Response.ProtoReflect.Descriptor instead.
func (*OM0Response) Descriptor() ([]byte, []int) {
	return file_om0_command_proto_rawDescGZIP(), []int{4}
}

func (x *OM0Response) GetRet() bool {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return false
}

type OM0Report struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SosSignal *bool           `protobuf:"varint,1,opt,name=sos_signal,json=sosSignal" json:"sos_signal,omitempty"`
	WakeUp    *bool           `protobuf:"varint,2,opt,name=wake_up,json=wakeUp" json:"wake_up,omitempty"`
	TrackData []*OM0TrackData `protobuf:"bytes,3,rep,name=track_data,json=trackData" json:"track_data,omitempty"`
	Battery   *RtBattery      `protobuf:"bytes,4,opt,name=battery" json:"battery,omitempty"`
	Health    *RtHealth       `protobuf:"bytes,5,opt,name=health" json:"health,omitempty"`
	DateTime  *DateTime       `protobuf:"bytes,6,opt,name=date_time,json=dateTime" json:"date_time,omitempty"`
	Rssi      *uint32         `protobuf:"fixed32,7,opt,name=rssi" json:"rssi,omitempty"`
	SleepData *OM0SleepData   `protobuf:"bytes,8,opt,name=sleep_data,json=sleepData" json:"sleep_data,omitempty"`
	SportType *uint32         `protobuf:"fixed32,9,opt,name=sport_type,json=sportType" json:"sport_type,omitempty"`
}

func (x *OM0Report) Reset() {
	*x = OM0Report{}
	if protoimpl.UnsafeEnabled {
		mi := &file_om0_command_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OM0Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OM0Report) ProtoMessage() {}

func (x *OM0Report) ProtoReflect() protoreflect.Message {
	mi := &file_om0_command_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OM0Report.ProtoReflect.Descriptor instead.
func (*OM0Report) Descriptor() ([]byte, []int) {
	return file_om0_command_proto_rawDescGZIP(), []int{5}
}

func (x *OM0Report) GetSosSignal() bool {
	if x != nil && x.SosSignal != nil {
		return *x.SosSignal
	}
	return false
}

func (x *OM0Report) GetWakeUp() bool {
	if x != nil && x.WakeUp != nil {
		return *x.WakeUp
	}
	return false
}

func (x *OM0Report) GetTrackData() []*OM0TrackData {
	if x != nil {
		return x.TrackData
	}
	return nil
}

func (x *OM0Report) GetBattery() *RtBattery {
	if x != nil {
		return x.Battery
	}
	return nil
}

func (x *OM0Report) GetHealth() *RtHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *OM0Report) GetDateTime() *DateTime {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *OM0Report) GetRssi() uint32 {
	if x != nil && x.Rssi != nil {
		return *x.Rssi
	}
	return 0
}

func (x *OM0Report) GetSleepData() *OM0SleepData {
	if x != nil {
		return x.SleepData
	}
	return nil
}

func (x *OM0Report) GetSportType() uint32 {
	if x != nil && x.SportType != nil {
		return *x.SportType
	}
	return 0
}

var File_om0_command_proto protoreflect.FileDescriptor

var file_om0_command_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6f, 0x6d, 0x30, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf1, 0x02, 0x0a, 0x0c, 0x4f, 0x4d, 0x30,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x72, 0x75, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x08, 0x52,
	0x07, 0x61, 0x75, 0x74, 0x6f, 0x52, 0x75, 0x6e, 0x12, 0x1e, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x02, 0x28, 0x07, 0x3a, 0x02, 0x33, 0x30, 0x52, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x6f, 0x72, 0x63,
	0x65, 0x5f, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0c, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x12, 0x36, 0x0a,
	0x0f, 0x6d, 0x63, 0x33, 0x30, 0x5f, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x4d, 0x63, 0x33, 0x30, 0x50, 0x6f, 0x77,
	0x65, 0x72, 0x6d, 0x6f, 0x64, 0x65, 0x52, 0x0d, 0x6d, 0x63, 0x33, 0x30, 0x50, 0x6f, 0x77, 0x65,
	0x72, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x67, 0x70, 0x73, 0x5f, 0x61, 0x75, 0x74,
	0x6f, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x67,
	0x70, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x2a, 0x0a, 0x11, 0x67,
	0x70, 0x73, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0f, 0x67, 0x70, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x16, 0x47, 0x50, 0x53, 0x5f, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x65, 0x73, 0x5f, 0x65, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x47, 0x50, 0x53, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x65, 0x73, 0x45, 0x76, 0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xa9, 0x04, 0x0a,
	0x0c, 0x4f, 0x4d, 0x30, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x26, 0x0a,
	0x0a, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x52, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x09, 0x73, 0x6c, 0x65, 0x65,
	0x70, 0x44, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a,
	0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x52, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x65, 0x70, 0x5f, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x18,
	0x04, 0x20, 0x02, 0x28, 0x07, 0x52, 0x09, 0x64, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70,
	0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x18,
	0x05, 0x20, 0x02, 0x28, 0x07, 0x52, 0x0a, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x53, 0x6c, 0x65, 0x65,
	0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x65, 0x61, 0x6b, 0x5f, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x18,
	0x06, 0x20, 0x02, 0x28, 0x07, 0x52, 0x09, 0x77, 0x65, 0x61, 0x6b, 0x53, 0x6c, 0x65, 0x65, 0x70,
	0x12, 0x23, 0x0a, 0x0d, 0x65, 0x79, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x73, 0x6c, 0x65, 0x65,
	0x70, 0x18, 0x07, 0x20, 0x02, 0x28, 0x07, 0x52, 0x0c, 0x65, 0x79, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x53, 0x6c, 0x65, 0x65, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x08,
	0x20, 0x02, 0x28, 0x07, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6f,
	0x73, 0x61, 0x68, 0x73, 0x5f, 0x72, 0x69, 0x73, 0x6b, 0x18, 0x09, 0x20, 0x02, 0x28, 0x07, 0x52,
	0x09, 0x6f, 0x73, 0x61, 0x68, 0x73, 0x52, 0x69, 0x73, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x70,
	0x6f, 0x32, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x0a, 0x20, 0x02, 0x28, 0x07, 0x52, 0x09,
	0x73, 0x70, 0x6f, 0x32, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x61, 0x76, 0x67,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x61, 0x74,
	0x65, 0x18, 0x0b, 0x20, 0x02, 0x28, 0x07, 0x52, 0x12, 0x61, 0x76, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x6d,
	0x61, 0x78, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x0c, 0x20, 0x02, 0x28, 0x07, 0x52, 0x12, 0x6d, 0x61, 0x78, 0x52, 0x65,
	0x73, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x12, 0x30, 0x0a,
	0x14, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x0d, 0x20, 0x02, 0x28, 0x07, 0x52, 0x12, 0x6d, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x5f, 0x68, 0x72, 0x18, 0x0e, 0x20, 0x02, 0x28,
	0x07, 0x52, 0x07, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x48, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x0f, 0x20, 0x02, 0x28, 0x07, 0x52, 0x09, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x68, 0x0a, 0x0a, 0x4f, 0x4d, 0x30, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x2c, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4f, 0x4d, 0x30,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x09, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x43, 0x6f, 0x6e, 0x66, 0x12, 0x2c, 0x0a, 0x0a, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4f, 0x4d, 0x30, 0x53, 0x6c,
	0x65, 0x65, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x7f, 0x0a, 0x0c, 0x4f, 0x4d, 0x30, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x04, 0x67, 0x6e, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x52, 0x74, 0x47, 0x4e, 0x53, 0x53, 0x52, 0x04, 0x67, 0x6e, 0x73, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x68, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x07, 0x52, 0x02, 0x68, 0x72, 0x12, 0x23,
	0x0a, 0x08, 0x67, 0x70, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x08, 0x2e, 0x47, 0x50, 0x53, 0x54, 0x59, 0x50, 0x45, 0x52, 0x07, 0x67, 0x70, 0x73, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x1f, 0x0a, 0x0b, 0x4f, 0x4d, 0x30, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x08, 0x52,
	0x03, 0x72, 0x65, 0x74, 0x22, 0xc3, 0x02, 0x0a, 0x09, 0x4f, 0x4d, 0x30, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x73, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x6f, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x61, 0x6b, 0x65, 0x5f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x77, 0x61, 0x6b, 0x65, 0x55, 0x70, 0x12, 0x2c, 0x0a, 0x0a, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x4f, 0x4d, 0x30, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x07, 0x62, 0x61, 0x74, 0x74,
	0x65, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x74, 0x42, 0x61,
	0x74, 0x74, 0x65, 0x72, 0x79, 0x52, 0x07, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x12, 0x21,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x52, 0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x12, 0x26, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52,
	0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x73, 0x73,
	0x69, 0x18, 0x07, 0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x72, 0x73, 0x73, 0x69, 0x12, 0x2c, 0x0a,
	0x0a, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x4f, 0x4d, 0x30, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x09, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x07, 0x52,
	0x09, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x2a, 0x2b, 0x0a, 0x0d, 0x4d, 0x63,
	0x33, 0x30, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x48,
	0x49, 0x47, 0x48, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x49, 0x44, 0x10, 0x01, 0x12, 0x07,
	0x0a, 0x03, 0x4c, 0x4f, 0x57, 0x10, 0x02, 0x2a, 0x3e, 0x0a, 0x07, 0x47, 0x50, 0x53, 0x54, 0x59,
	0x50, 0x45, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x54, 0x53, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x57, 0x49, 0x46, 0x49, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x47, 0x50, 0x53, 0x10, 0x03, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x69, 0x77, 0x6f,
	0x77, 0x6e,
}

var (
	file_om0_command_proto_rawDescOnce sync.Once
	file_om0_command_proto_rawDescData = file_om0_command_proto_rawDesc
)

func file_om0_command_proto_rawDescGZIP() []byte {
	file_om0_command_proto_rawDescOnce.Do(func() {
		file_om0_command_proto_rawDescData = protoimpl.X.CompressGZIP(file_om0_command_proto_rawDescData)
	})
	return file_om0_command_proto_rawDescData
}

var file_om0_command_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_om0_command_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_om0_command_proto_goTypes = []interface{}{
	(Mc30Powermode)(0),   // 0: Mc30Powermode
	(GPSTYPE)(0),         // 1: GPSTYPE
	(*OM0TrackConf)(nil), // 2: OM0TrackConf
	(*OM0SleepData)(nil), // 3: OM0SleepData
	(*OM0Command)(nil),   // 4: OM0Command
	(*OM0TrackData)(nil), // 5: OM0TrackData
	(*OM0Response)(nil),  // 6: OM0Response
	(*OM0Report)(nil),    // 7: OM0Report
	(*RtTime)(nil),       // 8: RtTime
	(*DateTime)(nil),     // 9: DateTime
	(*RtGNSS)(nil),       // 10: RtGNSS
	(*RtBattery)(nil),    // 11: RtBattery
	(*RtHealth)(nil),     // 12: RtHealth
}
var file_om0_command_proto_depIdxs = []int32{
	0,  // 0: OM0TrackConf.mc30_power_mode:type_name -> Mc30Powermode
	8,  // 1: OM0SleepData.sleep_date:type_name -> RtTime
	8,  // 2: OM0SleepData.start_time:type_name -> RtTime
	8,  // 3: OM0SleepData.end_time:type_name -> RtTime
	2,  // 4: OM0Command.track_conf:type_name -> OM0TrackConf
	3,  // 5: OM0Command.sleep_data:type_name -> OM0SleepData
	9,  // 6: OM0TrackData.time:type_name -> DateTime
	10, // 7: OM0TrackData.gnss:type_name -> RtGNSS
	1,  // 8: OM0TrackData.gps_type:type_name -> GPSTYPE
	5,  // 9: OM0Report.track_data:type_name -> OM0TrackData
	11, // 10: OM0Report.battery:type_name -> RtBattery
	12, // 11: OM0Report.health:type_name -> RtHealth
	9,  // 12: OM0Report.date_time:type_name -> DateTime
	3,  // 13: OM0Report.sleep_data:type_name -> OM0SleepData
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_om0_command_proto_init() }
func file_om0_command_proto_init() {
	if File_om0_command_proto != nil {
		return
	}
	file_realtime_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_om0_command_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OM0TrackConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_om0_command_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OM0SleepData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_om0_command_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OM0Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_om0_command_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OM0TrackData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_om0_command_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OM0Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_om0_command_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OM0Report); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_om0_command_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_om0_command_proto_goTypes,
		DependencyIndexes: file_om0_command_proto_depIdxs,
		EnumInfos:         file_om0_command_proto_enumTypes,
		MessageInfos:      file_om0_command_proto_msgTypes,
	}.Build()
	File_om0_command_proto = out.File
	file_om0_command_proto_rawDesc = nil
	file_om0_command_proto_goTypes = nil
	file_om0_command_proto_depIdxs = nil
}
