// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.3
// source: phone_book.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PhoneOperation int32

const (
	PhoneOperation_ADD    PhoneOperation = 1
	PhoneOperation_REMOVE PhoneOperation = 2
	PhoneOperation_CLEAR  PhoneOperation = 3
)

// Enum value maps for PhoneOperation.
var (
	PhoneOperation_name = map[int32]string{
		1: "ADD",
		2: "REMOVE",
		3: "CLEAR",
	}
	PhoneOperation_value = map[string]int32{
		"ADD":    1,
		"REMOVE": 2,
		"CLEAR":  3,
	}
)

func (x PhoneOperation) Enum() *PhoneOperation {
	p := new(PhoneOperation)
	*p = x
	return p
}

func (x PhoneOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhoneOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_phone_book_proto_enumTypes[0].Descriptor()
}

func (PhoneOperation) Type() protoreflect.EnumType {
	return &file_phone_book_proto_enumTypes[0]
}

func (x PhoneOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PhoneOperation) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PhoneOperation(num)
	return nil
}

// Deprecated: Use PhoneOperation.Descriptor instead.
func (PhoneOperation) EnumDescriptor() ([]byte, []int) {
	return file_phone_book_proto_rawDescGZIP(), []int{0}
}

type PhoneResponse int32

const (
	PhoneResponse_SUCCEED PhoneResponse = 1
	PhoneResponse_FAIL    PhoneResponse = 2
	PhoneResponse_EXIST   PhoneResponse = 3
)

// Enum value maps for PhoneResponse.
var (
	PhoneResponse_name = map[int32]string{
		1: "SUCCEED",
		2: "FAIL",
		3: "EXIST",
	}
	PhoneResponse_value = map[string]int32{
		"SUCCEED": 1,
		"FAIL":    2,
		"EXIST":   3,
	}
)

func (x PhoneResponse) Enum() *PhoneResponse {
	p := new(PhoneResponse)
	*p = x
	return p
}

func (x PhoneResponse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhoneResponse) Descriptor() protoreflect.EnumDescriptor {
	return file_phone_book_proto_enumTypes[1].Descriptor()
}

func (PhoneResponse) Type() protoreflect.EnumType {
	return &file_phone_book_proto_enumTypes[1]
}

func (x PhoneResponse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PhoneResponse) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PhoneResponse(num)
	return nil
}

// Deprecated: Use PhoneResponse.Descriptor instead.
func (PhoneResponse) EnumDescriptor() ([]byte, []int) {
	return file_phone_book_proto_rawDescGZIP(), []int{1}
}

type SOSGNSSINFO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longitude *float32 `protobuf:"fixed32,1,req,name=longitude" json:"longitude,omitempty"`
	Latitude  *float32 `protobuf:"fixed32,2,req,name=latitude" json:"latitude,omitempty"`
}

func (x *SOSGNSSINFO) Reset() {
	*x = SOSGNSSINFO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_book_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SOSGNSSINFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SOSGNSSINFO) ProtoMessage() {}

func (x *SOSGNSSINFO) ProtoReflect() protoreflect.Message {
	mi := &file_phone_book_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SOSGNSSINFO.ProtoReflect.Descriptor instead.
func (*SOSGNSSINFO) Descriptor() ([]byte, []int) {
	return file_phone_book_proto_rawDescGZIP(), []int{0}
}

func (x *SOSGNSSINFO) GetLongitude() float32 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *SOSGNSSINFO) GetLatitude() float32 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

type HrAlarmV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hr *uint32 `protobuf:"fixed32,1,req,name=hr" json:"hr,omitempty"`
}

func (x *HrAlarmV2) Reset() {
	*x = HrAlarmV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_book_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HrAlarmV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HrAlarmV2) ProtoMessage() {}

func (x *HrAlarmV2) ProtoReflect() protoreflect.Message {
	mi := &file_phone_book_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HrAlarmV2.ProtoReflect.Descriptor instead.
func (*HrAlarmV2) Descriptor() ([]byte, []int) {
	return file_phone_book_proto_rawDescGZIP(), []int{1}
}

func (x *HrAlarmV2) GetHr() uint32 {
	if x != nil && x.Hr != nil {
		return *x.Hr
	}
	return 0
}

type Spo2AlarmV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spo2 *uint32 `protobuf:"fixed32,1,req,name=spo2" json:"spo2,omitempty"`
}

func (x *Spo2AlarmV2) Reset() {
	*x = Spo2AlarmV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_book_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spo2AlarmV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spo2AlarmV2) ProtoMessage() {}

func (x *Spo2AlarmV2) ProtoReflect() protoreflect.Message {
	mi := &file_phone_book_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spo2AlarmV2.ProtoReflect.Descriptor instead.
func (*Spo2AlarmV2) Descriptor() ([]byte, []int) {
	return file_phone_book_proto_rawDescGZIP(), []int{2}
}

func (x *Spo2AlarmV2) GetSpo2() uint32 {
	if x != nil && x.Spo2 != nil {
		return *x.Spo2
	}
	return 0
}

type ThrombusAlarmV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThrombusAlarm *bool `protobuf:"varint,1,req,name=Thrombus_alarm,json=ThrombusAlarm" json:"Thrombus_alarm,omitempty"`
}

func (x *ThrombusAlarmV2) Reset() {
	*x = ThrombusAlarmV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_book_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThrombusAlarmV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrombusAlarmV2) ProtoMessage() {}

func (x *ThrombusAlarmV2) ProtoReflect() protoreflect.Message {
	mi := &file_phone_book_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrombusAlarmV2.ProtoReflect.Descriptor instead.
func (*ThrombusAlarmV2) Descriptor() ([]byte, []int) {
	return file_phone_book_proto_rawDescGZIP(), []int{3}
}

func (x *ThrombusAlarmV2) GetThrombusAlarm() bool {
	if x != nil && x.ThrombusAlarm != nil {
		return *x.ThrombusAlarm
	}
	return false
}

type FallAlarmConfV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FallAlarm *bool `protobuf:"varint,1,req,name=fall_alarm,json=fallAlarm" json:"fall_alarm,omitempty"`
}

func (x *FallAlarmConfV2) Reset() {
	*x = FallAlarmConfV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_book_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FallAlarmConfV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FallAlarmConfV2) ProtoMessage() {}

func (x *FallAlarmConfV2) ProtoReflect() protoreflect.Message {
	mi := &file_phone_book_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FallAlarmConfV2.ProtoReflect.Descriptor instead.
func (*FallAlarmConfV2) Descriptor() ([]byte, []int) {
	return file_phone_book_proto_rawDescGZIP(), []int{4}
}

func (x *FallAlarmConfV2) GetFallAlarm() bool {
	if x != nil && x.FallAlarm != nil {
		return *x.FallAlarm
	}
	return false
}

type PhoneAlarminfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp            *DateTime    `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	Wearstate            *bool        `protobuf:"varint,2,opt,name=wearstate" json:"wearstate,omitempty"`                                                    //Not wearing status information warning report
	Sleepstate           *bool        `protobuf:"varint,3,opt,name=sleepstate" json:"sleepstate,omitempty"`                                                  //sleep status information warning report
	Gnssinfo             *SOSGNSSINFO `protobuf:"bytes,4,opt,name=gnssinfo" json:"gnssinfo,omitempty"`                                                       //SOS warning information reporting
	LowpowerPercentage   *uint32      `protobuf:"fixed32,5,opt,name=lowpowerPercentage" json:"lowpowerPercentage,omitempty"`                                 //Low battery warning information reporting
	PoweroffPercentage   *uint32      `protobuf:"fixed32,6,opt,name=poweroffPercentage" json:"poweroffPercentage,omitempty"`                                 //Report shutdown information
	PhoneInterceptNumber *string      `protobuf:"bytes,7,opt,name=Phone_intercept_number,json=PhoneInterceptNumber" json:"Phone_intercept_number,omitempty"` //Unknown number blocking
}

func (x *PhoneAlarminfo) Reset() {
	*x = PhoneAlarminfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_book_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhoneAlarminfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneAlarminfo) ProtoMessage() {}

func (x *PhoneAlarminfo) ProtoReflect() protoreflect.Message {
	mi := &file_phone_book_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneAlarminfo.ProtoReflect.Descriptor instead.
func (*PhoneAlarminfo) Descriptor() ([]byte, []int) {
	return file_phone_book_proto_rawDescGZIP(), []int{5}
}

func (x *PhoneAlarminfo) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *PhoneAlarminfo) GetWearstate() bool {
	if x != nil && x.Wearstate != nil {
		return *x.Wearstate
	}
	return false
}

func (x *PhoneAlarminfo) GetSleepstate() bool {
	if x != nil && x.Sleepstate != nil {
		return *x.Sleepstate
	}
	return false
}

func (x *PhoneAlarminfo) GetGnssinfo() *SOSGNSSINFO {
	if x != nil {
		return x.Gnssinfo
	}
	return nil
}

func (x *PhoneAlarminfo) GetLowpowerPercentage() uint32 {
	if x != nil && x.LowpowerPercentage != nil {
		return *x.LowpowerPercentage
	}
	return 0
}

func (x *PhoneAlarminfo) GetPoweroffPercentage() uint32 {
	if x != nil && x.PoweroffPercentage != nil {
		return *x.PoweroffPercentage
	}
	return 0
}

func (x *PhoneAlarminfo) GetPhoneInterceptNumber() string {
	if x != nil && x.PhoneInterceptNumber != nil {
		return *x.PhoneInterceptNumber
	}
	return ""
}

type HealthAlarmV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp      *DateTime        `protobuf:"bytes,1,req,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	AlarmHr        *HrAlarmV2       `protobuf:"bytes,2,opt,name=alarm_hr,json=alarmHr" json:"alarm_hr,omitempty"`
	AlarmSpo2      *Spo2AlarmV2     `protobuf:"bytes,3,opt,name=alarm_spo2,json=alarmSpo2" json:"alarm_spo2,omitempty"`
	Alarm_Thrombus *ThrombusAlarmV2 `protobuf:"bytes,4,opt,name=alarm_Thrombus,json=alarmThrombus" json:"alarm_Thrombus,omitempty"`
	AlarmFall      *FallAlarmConfV2 `protobuf:"bytes,5,opt,name=alarm_fall,json=alarmFall" json:"alarm_fall,omitempty"`
}

func (x *HealthAlarmV2) Reset() {
	*x = HealthAlarmV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_book_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthAlarmV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthAlarmV2) ProtoMessage() {}

func (x *HealthAlarmV2) ProtoReflect() protoreflect.Message {
	mi := &file_phone_book_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthAlarmV2.ProtoReflect.Descriptor instead.
func (*HealthAlarmV2) Descriptor() ([]byte, []int) {
	return file_phone_book_proto_rawDescGZIP(), []int{6}
}

func (x *HealthAlarmV2) GetTimeStamp() *DateTime {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *HealthAlarmV2) GetAlarmHr() *HrAlarmV2 {
	if x != nil {
		return x.AlarmHr
	}
	return nil
}

func (x *HealthAlarmV2) GetAlarmSpo2() *Spo2AlarmV2 {
	if x != nil {
		return x.AlarmSpo2
	}
	return nil
}

func (x *HealthAlarmV2) GetAlarm_Thrombus() *ThrombusAlarmV2 {
	if x != nil {
		return x.Alarm_Thrombus
	}
	return nil
}

func (x *HealthAlarmV2) GetAlarmFall() *FallAlarmConfV2 {
	if x != nil {
		return x.AlarmFall
	}
	return nil
}

type PhoneBookInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *uint32 `protobuf:"fixed32,1,req,name=id" json:"id,omitempty"`
	IsSos  *bool   `protobuf:"varint,2,req,name=is_sos,json=isSos" json:"is_sos,omitempty"`
	Name   *string `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	Number *string `protobuf:"bytes,4,req,name=number" json:"number,omitempty"`
}

func (x *PhoneBookInfo) Reset() {
	*x = PhoneBookInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_book_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhoneBookInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneBookInfo) ProtoMessage() {}

func (x *PhoneBookInfo) ProtoReflect() protoreflect.Message {
	mi := &file_phone_book_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneBookInfo.ProtoReflect.Descriptor instead.
func (*PhoneBookInfo) Descriptor() ([]byte, []int) {
	return file_phone_book_proto_rawDescGZIP(), []int{7}
}

func (x *PhoneBookInfo) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PhoneBookInfo) GetIsSos() bool {
	if x != nil && x.IsSos != nil {
		return *x.IsSos
	}
	return false
}

func (x *PhoneBookInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PhoneBookInfo) GetNumber() string {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return ""
}

type PhoneBookNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Opt            *PhoneOperation  `protobuf:"varint,1,req,name=opt,enum=PhoneOperation" json:"opt,omitempty"`
	Info           []*PhoneBookInfo `protobuf:"bytes,2,rep,name=info" json:"info,omitempty"`
	PhoneIntercept *bool            `protobuf:"varint,3,opt,name=PhoneIntercept" json:"PhoneIntercept,omitempty"`
}

func (x *PhoneBookNotify) Reset() {
	*x = PhoneBookNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_book_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhoneBookNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneBookNotify) ProtoMessage() {}

func (x *PhoneBookNotify) ProtoReflect() protoreflect.Message {
	mi := &file_phone_book_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneBookNotify.ProtoReflect.Descriptor instead.
func (*PhoneBookNotify) Descriptor() ([]byte, []int) {
	return file_phone_book_proto_rawDescGZIP(), []int{8}
}

func (x *PhoneBookNotify) GetOpt() PhoneOperation {
	if x != nil && x.Opt != nil {
		return *x.Opt
	}
	return PhoneOperation_ADD
}

func (x *PhoneBookNotify) GetInfo() []*PhoneBookInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *PhoneBookNotify) GetPhoneIntercept() bool {
	if x != nil && x.PhoneIntercept != nil {
		return *x.PhoneIntercept
	}
	return false
}

type PhoneBookConfirm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res       *PhoneResponse  `protobuf:"varint,1,req,name=res,enum=PhoneResponse" json:"res,omitempty"`
	Num       *uint32         `protobuf:"fixed32,2,req,name=num" json:"num,omitempty"`
	Alarminfo *PhoneAlarminfo `protobuf:"bytes,3,opt,name=Alarminfo" json:"Alarminfo,omitempty"`
	Alarm     *HealthAlarmV2  `protobuf:"bytes,4,opt,name=alarm" json:"alarm,omitempty"`
}

func (x *PhoneBookConfirm) Reset() {
	*x = PhoneBookConfirm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_book_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhoneBookConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneBookConfirm) ProtoMessage() {}

func (x *PhoneBookConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_phone_book_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneBookConfirm.ProtoReflect.Descriptor instead.
func (*PhoneBookConfirm) Descriptor() ([]byte, []int) {
	return file_phone_book_proto_rawDescGZIP(), []int{9}
}

func (x *PhoneBookConfirm) GetRes() PhoneResponse {
	if x != nil && x.Res != nil {
		return *x.Res
	}
	return PhoneResponse_SUCCEED
}

func (x *PhoneBookConfirm) GetNum() uint32 {
	if x != nil && x.Num != nil {
		return *x.Num
	}
	return 0
}

func (x *PhoneBookConfirm) GetAlarminfo() *PhoneAlarminfo {
	if x != nil {
		return x.Alarminfo
	}
	return nil
}

func (x *PhoneBookConfirm) GetAlarm() *HealthAlarmV2 {
	if x != nil {
		return x.Alarm
	}
	return nil
}

var File_phone_book_proto protoreflect.FileDescriptor

var file_phone_book_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x13, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x0b, 0x53, 0x4f, 0x53, 0x47, 0x4e,
	0x53, 0x53, 0x49, 0x4e, 0x46, 0x4f, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x22, 0x1b, 0x0a, 0x09, 0x48, 0x72, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x56, 0x32, 0x12, 0x0e, 0x0a,
	0x02, 0x68, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x02, 0x68, 0x72, 0x22, 0x21, 0x0a,
	0x0b, 0x53, 0x70, 0x6f, 0x32, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x56, 0x32, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x70, 0x6f, 0x32, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x04, 0x73, 0x70, 0x6f, 0x32,
	0x22, 0x38, 0x0a, 0x0f, 0x54, 0x68, 0x72, 0x6f, 0x6d, 0x62, 0x75, 0x73, 0x41, 0x6c, 0x61, 0x72,
	0x6d, 0x56, 0x32, 0x12, 0x25, 0x0a, 0x0e, 0x54, 0x68, 0x72, 0x6f, 0x6d, 0x62, 0x75, 0x73, 0x5f,
	0x61, 0x6c, 0x61, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x08, 0x52, 0x0d, 0x54, 0x68, 0x72,
	0x6f, 0x6d, 0x62, 0x75, 0x73, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x22, 0x30, 0x0a, 0x0f, 0x46, 0x61,
	0x6c, 0x6c, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x56, 0x32, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x61, 0x6c, 0x6c, 0x5f, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x08, 0x52, 0x09, 0x66, 0x61, 0x6c, 0x6c, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x22, 0xb8, 0x02, 0x0a,
	0x0e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x69, 0x6e, 0x66, 0x6f, 0x12,
	0x28, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x65, 0x61,
	0x72, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x77, 0x65,
	0x61, 0x72, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6c, 0x65, 0x65, 0x70,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73, 0x6c, 0x65,
	0x65, 0x70, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x67, 0x6e, 0x73, 0x73, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x4f, 0x53, 0x47,
	0x4e, 0x53, 0x53, 0x49, 0x4e, 0x46, 0x4f, 0x52, 0x08, 0x67, 0x6e, 0x73, 0x73, 0x69, 0x6e, 0x66,
	0x6f, 0x12, 0x2e, 0x0a, 0x12, 0x6c, 0x6f, 0x77, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x50, 0x65, 0x72,
	0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x07, 0x52, 0x12, 0x6c,
	0x6f, 0x77, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67,
	0x65, 0x12, 0x2e, 0x0a, 0x12, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6f, 0x66, 0x66, 0x50, 0x65, 0x72,
	0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x07, 0x52, 0x12, 0x70,
	0x6f, 0x77, 0x65, 0x72, 0x6f, 0x66, 0x66, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67,
	0x65, 0x12, 0x34, 0x0a, 0x16, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x63, 0x65, 0x70, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x14, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x65, 0x70,
	0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0xf7, 0x01, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x56, 0x32, 0x12, 0x28, 0x0a, 0x0a, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x25, 0x0a, 0x08, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x5f, 0x68, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x48, 0x72, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x56,
	0x32, 0x52, 0x07, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x48, 0x72, 0x12, 0x2b, 0x0a, 0x0a, 0x61, 0x6c,
	0x61, 0x72, 0x6d, 0x5f, 0x73, 0x70, 0x6f, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x53, 0x70, 0x6f, 0x32, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x56, 0x32, 0x52, 0x09, 0x61, 0x6c,
	0x61, 0x72, 0x6d, 0x53, 0x70, 0x6f, 0x32, 0x12, 0x37, 0x0a, 0x0e, 0x61, 0x6c, 0x61, 0x72, 0x6d,
	0x5f, 0x54, 0x68, 0x72, 0x6f, 0x6d, 0x62, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x54, 0x68, 0x72, 0x6f, 0x6d, 0x62, 0x75, 0x73, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x56,
	0x32, 0x52, 0x0d, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x54, 0x68, 0x72, 0x6f, 0x6d, 0x62, 0x75, 0x73,
	0x12, 0x2f, 0x0a, 0x0a, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x5f, 0x66, 0x61, 0x6c, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x46, 0x61, 0x6c, 0x6c, 0x41, 0x6c, 0x61, 0x72, 0x6d,
	0x43, 0x6f, 0x6e, 0x66, 0x56, 0x32, 0x52, 0x09, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x46, 0x61, 0x6c,
	0x6c, 0x22, 0x62, 0x0a, 0x0d, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x73, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x53, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x80, 0x01, 0x0a, 0x0f, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x42,
	0x6f, 0x6f, 0x6b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x21, 0x0a, 0x03, 0x6f, 0x70, 0x74,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x6f, 0x70, 0x74, 0x12, 0x22, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x12, 0x26, 0x0a, 0x0e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x65,
	0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x63, 0x65, 0x70, 0x74, 0x22, 0x9b, 0x01, 0x0a, 0x10, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x20, 0x0a,
	0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x03, 0x6e, 0x75,
	0x6d, 0x12, 0x2d, 0x0a, 0x09, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x41, 0x6c, 0x61, 0x72,
	0x6d, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x69, 0x6e, 0x66, 0x6f,
	0x12, 0x24, 0x0a, 0x05, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x56, 0x32, 0x52,
	0x05, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x2a, 0x30, 0x0a, 0x0e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x02, 0x12, 0x09, 0x0a,
	0x05, 0x43, 0x4c, 0x45, 0x41, 0x52, 0x10, 0x03, 0x2a, 0x31, 0x0a, 0x0d, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x45, 0x44, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0x03, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x69, 0x77, 0x6f, 0x77, 0x6e,
}

var (
	file_phone_book_proto_rawDescOnce sync.Once
	file_phone_book_proto_rawDescData = file_phone_book_proto_rawDesc
)

func file_phone_book_proto_rawDescGZIP() []byte {
	file_phone_book_proto_rawDescOnce.Do(func() {
		file_phone_book_proto_rawDescData = protoimpl.X.CompressGZIP(file_phone_book_proto_rawDescData)
	})
	return file_phone_book_proto_rawDescData
}

var file_phone_book_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_phone_book_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_phone_book_proto_goTypes = []interface{}{
	(PhoneOperation)(0),      // 0: PhoneOperation
	(PhoneResponse)(0),       // 1: PhoneResponse
	(*SOSGNSSINFO)(nil),      // 2: SOSGNSSINFO
	(*HrAlarmV2)(nil),        // 3: HrAlarmV2
	(*Spo2AlarmV2)(nil),      // 4: Spo2AlarmV2
	(*ThrombusAlarmV2)(nil),  // 5: ThrombusAlarmV2
	(*FallAlarmConfV2)(nil),  // 6: FallAlarmConfV2
	(*PhoneAlarminfo)(nil),   // 7: PhoneAlarminfo
	(*HealthAlarmV2)(nil),    // 8: HealthAlarmV2
	(*PhoneBookInfo)(nil),    // 9: PhoneBookInfo
	(*PhoneBookNotify)(nil),  // 10: PhoneBookNotify
	(*PhoneBookConfirm)(nil), // 11: PhoneBookConfirm
	(*DateTime)(nil),         // 12: DateTime
}
var file_phone_book_proto_depIdxs = []int32{
	12, // 0: PhoneAlarminfo.time_stamp:type_name -> DateTime
	2,  // 1: PhoneAlarminfo.gnssinfo:type_name -> SOSGNSSINFO
	12, // 2: HealthAlarmV2.time_stamp:type_name -> DateTime
	3,  // 3: HealthAlarmV2.alarm_hr:type_name -> HrAlarmV2
	4,  // 4: HealthAlarmV2.alarm_spo2:type_name -> Spo2AlarmV2
	5,  // 5: HealthAlarmV2.alarm_Thrombus:type_name -> ThrombusAlarmV2
	6,  // 6: HealthAlarmV2.alarm_fall:type_name -> FallAlarmConfV2
	0,  // 7: PhoneBookNotify.opt:type_name -> PhoneOperation
	9,  // 8: PhoneBookNotify.info:type_name -> PhoneBookInfo
	1,  // 9: PhoneBookConfirm.res:type_name -> PhoneResponse
	7,  // 10: PhoneBookConfirm.Alarminfo:type_name -> PhoneAlarminfo
	8,  // 11: PhoneBookConfirm.alarm:type_name -> HealthAlarmV2
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_phone_book_proto_init() }
func file_phone_book_proto_init() {
	if File_phone_book_proto != nil {
		return
	}
	file_realtime_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_phone_book_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SOSGNSSINFO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phone_book_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HrAlarmV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phone_book_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spo2AlarmV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phone_book_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThrombusAlarmV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phone_book_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FallAlarmConfV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phone_book_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhoneAlarminfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phone_book_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthAlarmV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phone_book_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhoneBookInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phone_book_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhoneBookNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phone_book_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhoneBookConfirm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_phone_book_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_phone_book_proto_goTypes,
		DependencyIndexes: file_phone_book_proto_depIdxs,
		EnumInfos:         file_phone_book_proto_enumTypes,
		MessageInfos:      file_phone_book_proto_msgTypes,
	}.Build()
	File_phone_book_proto = out.File
	file_phone_book_proto_rawDesc = nil
	file_phone_book_proto_goTypes = nil
	file_phone_book_proto_depIdxs = nil
}
