// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: realtime_data.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RtMode int32

const (
	RtMode_RT_MODE_BACK_NORMAL      RtMode = 0
	RtMode_RT_MODE_ENTER_CAMERA     RtMode = 1
	RtMode_RT_START_FIND_WATCH      RtMode = 2
	RtMode_RT_START_DFU_MODE        RtMode = 3
	RtMode_RT_MODE_HR_MEASURE       RtMode = 4
	RtMode_RT_MODE_FATIGUE_MEASURE  RtMode = 5
	RtMode_RT_MODE_PRESSURE_MEASURE RtMode = 6
	RtMode_RT_VIEW_MEASURE_STATE    RtMode = 7
)

// Enum value maps for RtMode.
var (
	RtMode_name = map[int32]string{
		0: "RT_MODE_BACK_NORMAL",
		1: "RT_MODE_ENTER_CAMERA",
		2: "RT_START_FIND_WATCH",
		3: "RT_START_DFU_MODE",
		4: "RT_MODE_HR_MEASURE",
		5: "RT_MODE_FATIGUE_MEASURE",
		6: "RT_MODE_PRESSURE_MEASURE",
		7: "RT_VIEW_MEASURE_STATE",
	}
	RtMode_value = map[string]int32{
		"RT_MODE_BACK_NORMAL":      0,
		"RT_MODE_ENTER_CAMERA":     1,
		"RT_START_FIND_WATCH":      2,
		"RT_START_DFU_MODE":        3,
		"RT_MODE_HR_MEASURE":       4,
		"RT_MODE_FATIGUE_MEASURE":  5,
		"RT_MODE_PRESSURE_MEASURE": 6,
		"RT_VIEW_MEASURE_STATE":    7,
	}
)

func (x RtMode) Enum() *RtMode {
	p := new(RtMode)
	*p = x
	return p
}

func (x RtMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RtMode) Descriptor() protoreflect.EnumDescriptor {
	return file_realtime_data_proto_enumTypes[0].Descriptor()
}

func (RtMode) Type() protoreflect.EnumType {
	return &file_realtime_data_proto_enumTypes[0]
}

func (x RtMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RtMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RtMode(num)
	return nil
}

// Deprecated: Use RtMode.Descriptor instead.
func (RtMode) EnumDescriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{0}
}

type RtKeyEvent int32

const (
	RtKeyEvent_RT_KEY_CAMERA            RtKeyEvent = 0
	RtKeyEvent_RT_KEY_AUDIO_PLAY        RtKeyEvent = 1
	RtKeyEvent_RT_KEY_AUDIO_PRE         RtKeyEvent = 2
	RtKeyEvent_RT_KEY_AUDIO_NEXT        RtKeyEvent = 3
	RtKeyEvent_RT_KEY_AUDIO_VOLUME_UP   RtKeyEvent = 4
	RtKeyEvent_RT_KEY_AUDIO_VOLUME_DOWN RtKeyEvent = 5
	RtKeyEvent_RT_START_FIND_PHONE      RtKeyEvent = 6
	RtKeyEvent_RT_STOP_FIND_DEVICE      RtKeyEvent = 7
	RtKeyEvent_RT_LN_HEALTH_MEASURE     RtKeyEvent = 8
	RtKeyEvent_RT_NONE_MEASURE          RtKeyEvent = 9
)

// Enum value maps for RtKeyEvent.
var (
	RtKeyEvent_name = map[int32]string{
		0: "RT_KEY_CAMERA",
		1: "RT_KEY_AUDIO_PLAY",
		2: "RT_KEY_AUDIO_PRE",
		3: "RT_KEY_AUDIO_NEXT",
		4: "RT_KEY_AUDIO_VOLUME_UP",
		5: "RT_KEY_AUDIO_VOLUME_DOWN",
		6: "RT_START_FIND_PHONE",
		7: "RT_STOP_FIND_DEVICE",
		8: "RT_LN_HEALTH_MEASURE",
		9: "RT_NONE_MEASURE",
	}
	RtKeyEvent_value = map[string]int32{
		"RT_KEY_CAMERA":            0,
		"RT_KEY_AUDIO_PLAY":        1,
		"RT_KEY_AUDIO_PRE":         2,
		"RT_KEY_AUDIO_NEXT":        3,
		"RT_KEY_AUDIO_VOLUME_UP":   4,
		"RT_KEY_AUDIO_VOLUME_DOWN": 5,
		"RT_START_FIND_PHONE":      6,
		"RT_STOP_FIND_DEVICE":      7,
		"RT_LN_HEALTH_MEASURE":     8,
		"RT_NONE_MEASURE":          9,
	}
)

func (x RtKeyEvent) Enum() *RtKeyEvent {
	p := new(RtKeyEvent)
	*p = x
	return p
}

func (x RtKeyEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RtKeyEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_realtime_data_proto_enumTypes[1].Descriptor()
}

func (RtKeyEvent) Type() protoreflect.EnumType {
	return &file_realtime_data_proto_enumTypes[1]
}

func (x RtKeyEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RtKeyEvent) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RtKeyEvent(num)
	return nil
}

// Deprecated: Use RtKeyEvent.Descriptor instead.
func (RtKeyEvent) EnumDescriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{1}
}

type RtSync int32

const (
	RtSync_STOP_ALL             RtSync = 0
	RtSync_ONLY_ONCE            RtSync = 1
	RtSync_ON_VALUE_CHANGE      RtSync = 2
	RtSync_ON_SECOND_CHANGE     RtSync = 3
	RtSync_ON_MINUTE_CHANGE     RtSync = 4
	RtSync_ON_HOUR_CHANGE       RtSync = 5
	RtSync_ON_DAY_CHANGE        RtSync = 6
	RtSync_ON_TEN_MINUTE_CHANGE RtSync = 7
)

// Enum value maps for RtSync.
var (
	RtSync_name = map[int32]string{
		0: "STOP_ALL",
		1: "ONLY_ONCE",
		2: "ON_VALUE_CHANGE",
		3: "ON_SECOND_CHANGE",
		4: "ON_MINUTE_CHANGE",
		5: "ON_HOUR_CHANGE",
		6: "ON_DAY_CHANGE",
		7: "ON_TEN_MINUTE_CHANGE",
	}
	RtSync_value = map[string]int32{
		"STOP_ALL":             0,
		"ONLY_ONCE":            1,
		"ON_VALUE_CHANGE":      2,
		"ON_SECOND_CHANGE":     3,
		"ON_MINUTE_CHANGE":     4,
		"ON_HOUR_CHANGE":       5,
		"ON_DAY_CHANGE":        6,
		"ON_TEN_MINUTE_CHANGE": 7,
	}
)

func (x RtSync) Enum() *RtSync {
	p := new(RtSync)
	*p = x
	return p
}

func (x RtSync) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RtSync) Descriptor() protoreflect.EnumDescriptor {
	return file_realtime_data_proto_enumTypes[2].Descriptor()
}

func (RtSync) Type() protoreflect.EnumType {
	return &file_realtime_data_proto_enumTypes[2]
}

func (x RtSync) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RtSync) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RtSync(num)
	return nil
}

// Deprecated: Use RtSync.Descriptor instead.
func (RtSync) EnumDescriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{2}
}

type SensorType int32

const (
	SensorType_NONE         SensorType = 0
	SensorType_ECG          SensorType = 1
	SensorType_PPG          SensorType = 2
	SensorType_MAG          SensorType = 4
	SensorType_GYRO         SensorType = 8
	SensorType_ACC          SensorType = 16
	SensorType_BP           SensorType = 32
	SensorType_BPRESULT     SensorType = 64
	SensorType_TEMPERATURE  SensorType = 128
	SensorType_TWO_ECG      SensorType = 256
	SensorType_BIOZ         SensorType = 512
	SensorType_ECG_DETECT   SensorType = 1024
	SensorType_FACTORY_ECG  SensorType = 2048
	SensorType_FACTORY_BIOZ SensorType = 4096
	SensorType_HR_LEAK      SensorType = 8192
	SensorType_BP_LEAK      SensorType = 16384
	SensorType_SPO2         SensorType = 32768
	SensorType_OAQ          SensorType = 65536
	SensorType_IAQ          SensorType = 131072
	SensorType_HUMITURE     SensorType = 262144
	SensorType_ULTRASONIC   SensorType = 524288
)

// Enum value maps for SensorType.
var (
	SensorType_name = map[int32]string{
		0:      "NONE",
		1:      "ECG",
		2:      "PPG",
		4:      "MAG",
		8:      "GYRO",
		16:     "ACC",
		32:     "BP",
		64:     "BPRESULT",
		128:    "TEMPERATURE",
		256:    "TWO_ECG",
		512:    "BIOZ",
		1024:   "ECG_DETECT",
		2048:   "FACTORY_ECG",
		4096:   "FACTORY_BIOZ",
		8192:   "HR_LEAK",
		16384:  "BP_LEAK",
		32768:  "SPO2",
		65536:  "OAQ",
		131072: "IAQ",
		262144: "HUMITURE",
		524288: "ULTRASONIC",
	}
	SensorType_value = map[string]int32{
		"NONE":         0,
		"ECG":          1,
		"PPG":          2,
		"MAG":          4,
		"GYRO":         8,
		"ACC":          16,
		"BP":           32,
		"BPRESULT":     64,
		"TEMPERATURE":  128,
		"TWO_ECG":      256,
		"BIOZ":         512,
		"ECG_DETECT":   1024,
		"FACTORY_ECG":  2048,
		"FACTORY_BIOZ": 4096,
		"HR_LEAK":      8192,
		"BP_LEAK":      16384,
		"SPO2":         32768,
		"OAQ":          65536,
		"IAQ":          131072,
		"HUMITURE":     262144,
		"ULTRASONIC":   524288,
	}
)

func (x SensorType) Enum() *SensorType {
	p := new(SensorType)
	*p = x
	return p
}

func (x SensorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SensorType) Descriptor() protoreflect.EnumDescriptor {
	return file_realtime_data_proto_enumTypes[3].Descriptor()
}

func (SensorType) Type() protoreflect.EnumType {
	return &file_realtime_data_proto_enumTypes[3]
}

func (x SensorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SensorType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SensorType(num)
	return nil
}

// Deprecated: Use SensorType.Descriptor instead.
func (SensorType) EnumDescriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{3}
}

type SensorOperation int32

const (
	SensorOperation_SENSOR_START_SYNC SensorOperation = 0 // start sync
	SensorOperation_SENSOR_PAUSE_SYNC SensorOperation = 1 // pause sync
	SensorOperation_SENSOR_STOP_SYNC  SensorOperation = 2 // stop sync
)

// Enum value maps for SensorOperation.
var (
	SensorOperation_name = map[int32]string{
		0: "SENSOR_START_SYNC",
		1: "SENSOR_PAUSE_SYNC",
		2: "SENSOR_STOP_SYNC",
	}
	SensorOperation_value = map[string]int32{
		"SENSOR_START_SYNC": 0,
		"SENSOR_PAUSE_SYNC": 1,
		"SENSOR_STOP_SYNC":  2,
	}
)

func (x SensorOperation) Enum() *SensorOperation {
	p := new(SensorOperation)
	*p = x
	return p
}

func (x SensorOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SensorOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_realtime_data_proto_enumTypes[4].Descriptor()
}

func (SensorOperation) Type() protoreflect.EnumType {
	return &file_realtime_data_proto_enumTypes[4]
}

func (x SensorOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SensorOperation) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SensorOperation(num)
	return nil
}

// Deprecated: Use SensorOperation.Descriptor instead.
func (SensorOperation) EnumDescriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{4}
}

type SportOperation int32

const (
	SportOperation_SPORT_START SportOperation = 0 // start sync
	SportOperation_SPORT_PAUSE SportOperation = 1 // pause sync
	SportOperation_SPORT_STOP  SportOperation = 2 // stop sync
)

// Enum value maps for SportOperation.
var (
	SportOperation_name = map[int32]string{
		0: "SPORT_START",
		1: "SPORT_PAUSE",
		2: "SPORT_STOP",
	}
	SportOperation_value = map[string]int32{
		"SPORT_START": 0,
		"SPORT_PAUSE": 1,
		"SPORT_STOP":  2,
	}
)

func (x SportOperation) Enum() *SportOperation {
	p := new(SportOperation)
	*p = x
	return p
}

func (x SportOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SportOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_realtime_data_proto_enumTypes[5].Descriptor()
}

func (SportOperation) Type() protoreflect.EnumType {
	return &file_realtime_data_proto_enumTypes[5]
}

func (x SportOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SportOperation) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SportOperation(num)
	return nil
}

// Deprecated: Use SportOperation.Descriptor instead.
func (SportOperation) EnumDescriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{5}
}

type RtTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seconds *uint32 `protobuf:"fixed32,1,req,name=seconds" json:"seconds,omitempty"`
}

func (x *RtTime) Reset() {
	*x = RtTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtTime) ProtoMessage() {}

func (x *RtTime) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtTime.ProtoReflect.Descriptor instead.
func (*RtTime) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{0}
}

func (x *RtTime) GetSeconds() uint32 {
	if x != nil && x.Seconds != nil {
		return *x.Seconds
	}
	return 0
}

type DateTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateTime *RtTime `protobuf:"bytes,1,req,name=date_time,json=dateTime" json:"date_time,omitempty"`
	TimeZone *int32  `protobuf:"fixed32,2,req,name=time_zone,json=timeZone" json:"time_zone,omitempty"`
}

func (x *DateTime) Reset() {
	*x = DateTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateTime) ProtoMessage() {}

func (x *DateTime) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateTime.ProtoReflect.Descriptor instead.
func (*DateTime) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{1}
}

func (x *DateTime) GetDateTime() *RtTime {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *DateTime) GetTimeZone() int32 {
	if x != nil && x.TimeZone != nil {
		return *x.TimeZone
	}
	return 0
}

type RtBattery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level    *uint32 `protobuf:"fixed32,1,req,name=level" json:"level,omitempty"` //0~9
	Charging *bool   `protobuf:"varint,2,req,name=charging" json:"charging,omitempty"`
}

func (x *RtBattery) Reset() {
	*x = RtBattery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtBattery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtBattery) ProtoMessage() {}

func (x *RtBattery) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtBattery.ProtoReflect.Descriptor instead.
func (*RtBattery) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{2}
}

func (x *RtBattery) GetLevel() uint32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *RtBattery) GetCharging() bool {
	if x != nil && x.Charging != nil {
		return *x.Charging
	}
	return false
}

type RtHealth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Steps    *uint32 `protobuf:"fixed32,1,req,name=steps" json:"steps,omitempty"`
	Distance *uint32 `protobuf:"fixed32,2,req,name=distance" json:"distance,omitempty"`
	Calorie  *uint32 `protobuf:"fixed32,3,req,name=calorie" json:"calorie,omitempty"`
}

func (x *RtHealth) Reset() {
	*x = RtHealth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtHealth) ProtoMessage() {}

func (x *RtHealth) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtHealth.ProtoReflect.Descriptor instead.
func (*RtHealth) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{3}
}

func (x *RtHealth) GetSteps() uint32 {
	if x != nil && x.Steps != nil {
		return *x.Steps
	}
	return 0
}

func (x *RtHealth) GetDistance() uint32 {
	if x != nil && x.Distance != nil {
		return *x.Distance
	}
	return 0
}

func (x *RtHealth) GetCalorie() uint32 {
	if x != nil && x.Calorie != nil {
		return *x.Calorie
	}
	return 0
}

type BPresult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sbp *uint32 `protobuf:"fixed32,1,req,name=sbp" json:"sbp,omitempty"`
	Dbp *uint32 `protobuf:"fixed32,2,req,name=dbp" json:"dbp,omitempty"`
}

func (x *BPresult) Reset() {
	*x = BPresult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BPresult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BPresult) ProtoMessage() {}

func (x *BPresult) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BPresult.ProtoReflect.Descriptor instead.
func (*BPresult) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{4}
}

func (x *BPresult) GetSbp() uint32 {
	if x != nil && x.Sbp != nil {
		return *x.Sbp
	}
	return 0
}

func (x *BPresult) GetDbp() uint32 {
	if x != nil && x.Dbp != nil {
		return *x.Dbp
	}
	return 0
}

type RtHealthResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fatigue    *uint32   `protobuf:"fixed32,1,opt,name=fatigue" json:"fatigue,omitempty"`
	Stress     *uint32   `protobuf:"fixed32,2,opt,name=stress" json:"stress,omitempty"`
	Spo2       *uint32   `protobuf:"fixed32,3,opt,name=spo2" json:"spo2,omitempty"`
	Hr         *uint32   `protobuf:"fixed32,4,opt,name=hr" json:"hr,omitempty"`
	Bp         *BPresult `protobuf:"bytes,5,opt,name=bp" json:"bp,omitempty"`
	Breathrate *uint32   `protobuf:"fixed32,6,opt,name=breathrate" json:"breathrate,omitempty"`
	Temperatur *uint32   `protobuf:"fixed32,7,opt,name=temperatur" json:"temperatur,omitempty"`
}

func (x *RtHealthResult) Reset() {
	*x = RtHealthResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtHealthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtHealthResult) ProtoMessage() {}

func (x *RtHealthResult) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtHealthResult.ProtoReflect.Descriptor instead.
func (*RtHealthResult) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{5}
}

func (x *RtHealthResult) GetFatigue() uint32 {
	if x != nil && x.Fatigue != nil {
		return *x.Fatigue
	}
	return 0
}

func (x *RtHealthResult) GetStress() uint32 {
	if x != nil && x.Stress != nil {
		return *x.Stress
	}
	return 0
}

func (x *RtHealthResult) GetSpo2() uint32 {
	if x != nil && x.Spo2 != nil {
		return *x.Spo2
	}
	return 0
}

func (x *RtHealthResult) GetHr() uint32 {
	if x != nil && x.Hr != nil {
		return *x.Hr
	}
	return 0
}

func (x *RtHealthResult) GetBp() *BPresult {
	if x != nil {
		return x.Bp
	}
	return nil
}

func (x *RtHealthResult) GetBreathrate() uint32 {
	if x != nil && x.Breathrate != nil {
		return *x.Breathrate
	}
	return 0
}

func (x *RtHealthResult) GetTemperatur() uint32 {
	if x != nil && x.Temperatur != nil {
		return *x.Temperatur
	}
	return 0
}

type RtGNSS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longitude *float32 `protobuf:"fixed32,1,req,name=longitude" json:"longitude,omitempty"`
	Latitude  *float32 `protobuf:"fixed32,2,req,name=latitude" json:"latitude,omitempty"`
	Speed     *float32 `protobuf:"fixed32,3,req,name=speed" json:"speed,omitempty"`       // m/s
	Altitude  *float32 `protobuf:"fixed32,4,req,name=altitude" json:"altitude,omitempty"` // m
}

func (x *RtGNSS) Reset() {
	*x = RtGNSS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtGNSS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtGNSS) ProtoMessage() {}

func (x *RtGNSS) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtGNSS.ProtoReflect.Descriptor instead.
func (*RtGNSS) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{6}
}

func (x *RtGNSS) GetLongitude() float32 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *RtGNSS) GetLatitude() float32 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *RtGNSS) GetSpeed() float32 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

func (x *RtGNSS) GetAltitude() float32 {
	if x != nil && x.Altitude != nil {
		return *x.Altitude
	}
	return 0
}

type RtSensor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation *SensorOperation `protobuf:"varint,1,req,name=operation,enum=SensorOperation" json:"operation,omitempty"`
	Type      *uint32          `protobuf:"fixed32,2,req,name=type" json:"type,omitempty"`
}

func (x *RtSensor) Reset() {
	*x = RtSensor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtSensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtSensor) ProtoMessage() {}

func (x *RtSensor) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtSensor.ProtoReflect.Descriptor instead.
func (*RtSensor) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{7}
}

func (x *RtSensor) GetOperation() SensorOperation {
	if x != nil && x.Operation != nil {
		return *x.Operation
	}
	return SensorOperation_SENSOR_START_SYNC
}

func (x *RtSensor) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

type Rtsport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation *SportOperation `protobuf:"varint,1,req,name=operation,enum=SportOperation" json:"operation,omitempty"`
	SportType *uint32         `protobuf:"fixed32,2,req,name=sport_type,json=sportType" json:"sport_type,omitempty"`
}

func (x *Rtsport) Reset() {
	*x = Rtsport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rtsport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rtsport) ProtoMessage() {}

func (x *Rtsport) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rtsport.ProtoReflect.Descriptor instead.
func (*Rtsport) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{8}
}

func (x *Rtsport) GetOperation() SportOperation {
	if x != nil && x.Operation != nil {
		return *x.Operation
	}
	return SportOperation_SPORT_START
}

func (x *Rtsport) GetSportType() uint32 {
	if x != nil && x.SportType != nil {
		return *x.SportType
	}
	return 0
}

type RtSubscriber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time    *RtSync   `protobuf:"varint,1,opt,name=time,enum=RtSync" json:"time,omitempty"`
	Battery *RtSync   `protobuf:"varint,2,opt,name=battery,enum=RtSync" json:"battery,omitempty"`
	Health  *RtSync   `protobuf:"varint,3,opt,name=health,enum=RtSync" json:"health,omitempty"`
	Mode    *RtMode   `protobuf:"varint,4,opt,name=mode,enum=RtMode" json:"mode,omitempty"`
	Sensor  *RtSensor `protobuf:"bytes,5,opt,name=sensor" json:"sensor,omitempty"`
	Sport   *Rtsport  `protobuf:"bytes,6,opt,name=sport" json:"sport,omitempty"`
}

func (x *RtSubscriber) Reset() {
	*x = RtSubscriber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtSubscriber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtSubscriber) ProtoMessage() {}

func (x *RtSubscriber) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtSubscriber.ProtoReflect.Descriptor instead.
func (*RtSubscriber) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{9}
}

func (x *RtSubscriber) GetTime() RtSync {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return RtSync_STOP_ALL
}

func (x *RtSubscriber) GetBattery() RtSync {
	if x != nil && x.Battery != nil {
		return *x.Battery
	}
	return RtSync_STOP_ALL
}

func (x *RtSubscriber) GetHealth() RtSync {
	if x != nil && x.Health != nil {
		return *x.Health
	}
	return RtSync_STOP_ALL
}

func (x *RtSubscriber) GetMode() RtMode {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return RtMode_RT_MODE_BACK_NORMAL
}

func (x *RtSubscriber) GetSensor() *RtSensor {
	if x != nil {
		return x.Sensor
	}
	return nil
}

func (x *RtSubscriber) GetSport() *Rtsport {
	if x != nil {
		return x.Sport
	}
	return nil
}

type RtData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time         *RtTime         `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	Battery      *RtBattery      `protobuf:"bytes,2,opt,name=battery" json:"battery,omitempty"`
	Health       *RtHealth       `protobuf:"bytes,3,opt,name=health" json:"health,omitempty"`
	Key          *RtKeyEvent     `protobuf:"varint,4,opt,name=key,enum=RtKeyEvent" json:"key,omitempty"`
	TimeZone     *int32          `protobuf:"fixed32,5,opt,name=time_zone,json=timeZone" json:"time_zone,omitempty"`
	Healthresult *RtHealthResult `protobuf:"bytes,6,opt,name=healthresult" json:"healthresult,omitempty"`
}

func (x *RtData) Reset() {
	*x = RtData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtData) ProtoMessage() {}

func (x *RtData) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtData.ProtoReflect.Descriptor instead.
func (*RtData) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{10}
}

func (x *RtData) GetTime() *RtTime {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *RtData) GetBattery() *RtBattery {
	if x != nil {
		return x.Battery
	}
	return nil
}

func (x *RtData) GetHealth() *RtHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *RtData) GetKey() RtKeyEvent {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return RtKeyEvent_RT_KEY_CAMERA
}

func (x *RtData) GetTimeZone() int32 {
	if x != nil && x.TimeZone != nil {
		return *x.TimeZone
	}
	return 0
}

func (x *RtData) GetHealthresult() *RtHealthResult {
	if x != nil {
		return x.Healthresult
	}
	return nil
}

type RtState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time    *RtSync `protobuf:"varint,1,opt,name=time,enum=RtSync" json:"time,omitempty"`
	Battery *RtSync `protobuf:"varint,2,opt,name=battery,enum=RtSync" json:"battery,omitempty"`
	Health  *RtSync `protobuf:"varint,3,opt,name=health,enum=RtSync" json:"health,omitempty"`
	Mode    *RtMode `protobuf:"varint,4,opt,name=mode,enum=RtMode" json:"mode,omitempty"`
}

func (x *RtState) Reset() {
	*x = RtState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtState) ProtoMessage() {}

func (x *RtState) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtState.ProtoReflect.Descriptor instead.
func (*RtState) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{11}
}

func (x *RtState) GetTime() RtSync {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return RtSync_STOP_ALL
}

func (x *RtState) GetBattery() RtSync {
	if x != nil && x.Battery != nil {
		return *x.Battery
	}
	return RtSync_STOP_ALL
}

func (x *RtState) GetHealth() RtSync {
	if x != nil && x.Health != nil {
		return *x.Health
	}
	return RtSync_STOP_ALL
}

func (x *RtState) GetMode() RtMode {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return RtMode_RT_MODE_BACK_NORMAL
}

type RtSensorData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *uint32  `protobuf:"fixed32,1,req,name=type" json:"type,omitempty"`
	Time *RtTime  `protobuf:"bytes,2,req,name=time" json:"time,omitempty"`
	Seq  *uint32  `protobuf:"fixed32,3,req,name=seq" json:"seq,omitempty"`
	Data []uint32 `protobuf:"fixed32,4,rep,name=data" json:"data,omitempty"`
}

func (x *RtSensorData) Reset() {
	*x = RtSensorData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtSensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtSensorData) ProtoMessage() {}

func (x *RtSensorData) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtSensorData.ProtoReflect.Descriptor instead.
func (*RtSensorData) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{12}
}

func (x *RtSensorData) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *RtSensorData) GetTime() *RtTime {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *RtSensorData) GetSeq() uint32 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *RtSensorData) GetData() []uint32 {
	if x != nil {
		return x.Data
	}
	return nil
}

type RtDtda_Summary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time     *uint32 `protobuf:"fixed32,1,req,name=time" json:"time,omitempty"`
	Steps    *uint32 `protobuf:"fixed32,2,req,name=steps" json:"steps,omitempty"`
	Distance *uint32 `protobuf:"fixed32,3,req,name=distance" json:"distance,omitempty"`
	Calorie  *uint32 `protobuf:"fixed32,4,req,name=calorie" json:"calorie,omitempty"`
}

func (x *RtDtda_Summary) Reset() {
	*x = RtDtda_Summary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtDtda_Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtDtda_Summary) ProtoMessage() {}

func (x *RtDtda_Summary) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtDtda_Summary.ProtoReflect.Descriptor instead.
func (*RtDtda_Summary) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{13}
}

func (x *RtDtda_Summary) GetTime() uint32 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *RtDtda_Summary) GetSteps() uint32 {
	if x != nil && x.Steps != nil {
		return *x.Steps
	}
	return 0
}

func (x *RtDtda_Summary) GetDistance() uint32 {
	if x != nil && x.Distance != nil {
		return *x.Distance
	}
	return 0
}

func (x *RtDtda_Summary) GetCalorie() uint32 {
	if x != nil && x.Calorie != nil {
		return *x.Calorie
	}
	return 0
}

type RtSportData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SdSportType  *uint32         `protobuf:"fixed32,1,req,name=sd_sportType,json=sdSportType" json:"sd_sportType,omitempty"`
	HrTotal      *uint32         `protobuf:"fixed32,2,req,name=hr_total,json=hrTotal" json:"hr_total,omitempty"`
	HrCount      *uint32         `protobuf:"fixed32,3,req,name=hr_count,json=hrCount" json:"hr_count,omitempty"`
	RealtimePace *uint32         `protobuf:"fixed32,4,req,name=realtime_pace,json=realtimePace" json:"realtime_pace,omitempty"`
	RealtimeSpm  *uint32         `protobuf:"fixed32,5,req,name=realtime_spm,json=realtimeSpm" json:"realtime_spm,omitempty"`
	RealtimeHr   *uint32         `protobuf:"fixed32,6,req,name=realtime_hr,json=realtimeHr" json:"realtime_hr,omitempty"`
	SwimCircle   *uint32         `protobuf:"fixed32,7,req,name=swim_circle,json=swimCircle" json:"swim_circle,omitempty"`
	SwimStroke   *uint32         `protobuf:"fixed32,8,req,name=swim_stroke,json=swimStroke" json:"swim_stroke,omitempty"`
	DataTotal    *RtDtda_Summary `protobuf:"bytes,9,req,name=data_total,json=dataTotal" json:"data_total,omitempty"`
	DataSport    *RtDtda_Summary `protobuf:"bytes,10,req,name=data_sport,json=dataSport" json:"data_sport,omitempty"`
}

func (x *RtSportData) Reset() {
	*x = RtSportData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtSportData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtSportData) ProtoMessage() {}

func (x *RtSportData) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtSportData.ProtoReflect.Descriptor instead.
func (*RtSportData) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{14}
}

func (x *RtSportData) GetSdSportType() uint32 {
	if x != nil && x.SdSportType != nil {
		return *x.SdSportType
	}
	return 0
}

func (x *RtSportData) GetHrTotal() uint32 {
	if x != nil && x.HrTotal != nil {
		return *x.HrTotal
	}
	return 0
}

func (x *RtSportData) GetHrCount() uint32 {
	if x != nil && x.HrCount != nil {
		return *x.HrCount
	}
	return 0
}

func (x *RtSportData) GetRealtimePace() uint32 {
	if x != nil && x.RealtimePace != nil {
		return *x.RealtimePace
	}
	return 0
}

func (x *RtSportData) GetRealtimeSpm() uint32 {
	if x != nil && x.RealtimeSpm != nil {
		return *x.RealtimeSpm
	}
	return 0
}

func (x *RtSportData) GetRealtimeHr() uint32 {
	if x != nil && x.RealtimeHr != nil {
		return *x.RealtimeHr
	}
	return 0
}

func (x *RtSportData) GetSwimCircle() uint32 {
	if x != nil && x.SwimCircle != nil {
		return *x.SwimCircle
	}
	return 0
}

func (x *RtSportData) GetSwimStroke() uint32 {
	if x != nil && x.SwimStroke != nil {
		return *x.SwimStroke
	}
	return 0
}

func (x *RtSportData) GetDataTotal() *RtDtda_Summary {
	if x != nil {
		return x.DataTotal
	}
	return nil
}

func (x *RtSportData) GetDataSport() *RtDtda_Summary {
	if x != nil {
		return x.DataSport
	}
	return nil
}

type RtNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*RtNotification_RtData
	//	*RtNotification_RtState
	//	*RtNotification_RtSensordata
	//	*RtNotification_RtSportData
	Data isRtNotification_Data `protobuf_oneof:"data"`
}

func (x *RtNotification) Reset() {
	*x = RtNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realtime_data_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtNotification) ProtoMessage() {}

func (x *RtNotification) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_data_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtNotification.ProtoReflect.Descriptor instead.
func (*RtNotification) Descriptor() ([]byte, []int) {
	return file_realtime_data_proto_rawDescGZIP(), []int{15}
}

func (m *RtNotification) GetData() isRtNotification_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *RtNotification) GetRtData() *RtData {
	if x, ok := x.GetData().(*RtNotification_RtData); ok {
		return x.RtData
	}
	return nil
}

func (x *RtNotification) GetRtState() *RtState {
	if x, ok := x.GetData().(*RtNotification_RtState); ok {
		return x.RtState
	}
	return nil
}

func (x *RtNotification) GetRtSensordata() *RtSensorData {
	if x, ok := x.GetData().(*RtNotification_RtSensordata); ok {
		return x.RtSensordata
	}
	return nil
}

func (x *RtNotification) GetRtSportData() *RtSportData {
	if x, ok := x.GetData().(*RtNotification_RtSportData); ok {
		return x.RtSportData
	}
	return nil
}

type isRtNotification_Data interface {
	isRtNotification_Data()
}

type RtNotification_RtData struct {
	RtData *RtData `protobuf:"bytes,1,opt,name=rt_data,json=rtData,oneof"`
}

type RtNotification_RtState struct {
	RtState *RtState `protobuf:"bytes,2,opt,name=rt_state,json=rtState,oneof"`
}

type RtNotification_RtSensordata struct {
	RtSensordata *RtSensorData `protobuf:"bytes,3,opt,name=rt_sensordata,json=rtSensordata,oneof"`
}

type RtNotification_RtSportData struct {
	RtSportData *RtSportData `protobuf:"bytes,4,opt,name=rt_sport_data,json=rtSportData,oneof"`
}

func (*RtNotification_RtData) isRtNotification_Data() {}

func (*RtNotification_RtState) isRtNotification_Data() {}

func (*RtNotification_RtSensordata) isRtNotification_Data() {}

func (*RtNotification_RtSportData) isRtNotification_Data() {}

var File_realtime_data_proto protoreflect.FileDescriptor

var file_realtime_data_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x06, 0x52, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07,
	0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x4d, 0x0a, 0x08, 0x44, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0f, 0x52, 0x08,
	0x74, 0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x22, 0x3d, 0x0a, 0x09, 0x52, 0x74, 0x42, 0x61,
	0x74, 0x74, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x07, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x68, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x02, 0x28, 0x08, 0x52, 0x08, 0x63,
	0x68, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x67, 0x22, 0x56, 0x0a, 0x08, 0x52, 0x74, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x07, 0x52, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x08, 0x64, 0x69, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6f, 0x72, 0x69, 0x65,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x07, 0x52, 0x07, 0x63, 0x61, 0x6c, 0x6f, 0x72, 0x69, 0x65, 0x22,
	0x2e, 0x0a, 0x08, 0x42, 0x50, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x62, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x03, 0x73, 0x62, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x62, 0x70, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x03, 0x64, 0x62, 0x70, 0x22,
	0xc1, 0x01, 0x0a, 0x0e, 0x52, 0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x74, 0x69, 0x67, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x07, 0x52, 0x07, 0x66, 0x61, 0x74, 0x69, 0x67, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x06, 0x73, 0x74,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x70, 0x6f, 0x32, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x07, 0x52, 0x04, 0x73, 0x70, 0x6f, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x07, 0x52, 0x02, 0x68, 0x72, 0x12, 0x19, 0x0a, 0x02, 0x62, 0x70, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x42, 0x50, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x02, 0x62, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x65, 0x61, 0x74, 0x68, 0x72, 0x61, 0x74,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0a, 0x62, 0x72, 0x65, 0x61, 0x74, 0x68, 0x72,
	0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75,
	0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x75, 0x72, 0x22, 0x74, 0x0a, 0x06, 0x52, 0x74, 0x47, 0x4e, 0x53, 0x53, 0x12, 0x1c, 0x0a,
	0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x02,
	0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x08, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x02, 0x52,
	0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x4e, 0x0a, 0x08, 0x52, 0x74, 0x53,
	0x65, 0x6e, 0x73, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x07, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x57, 0x0a, 0x07, 0x52, 0x74, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x2d, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x09, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x22, 0xcf, 0x01, 0x0a, 0x0c, 0x52, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x07, 0x2e, 0x52, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x21, 0x0a, 0x07, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x07, 0x2e, 0x52, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x07, 0x62, 0x61, 0x74, 0x74,
	0x65, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x52, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x07, 0x2e, 0x52, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x12, 0x21, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x52, 0x74, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x06, 0x73, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x05, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x74, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x05, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x22, 0xdf, 0x01, 0x0a, 0x06, 0x52, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1b, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x52, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x07,
	0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x52, 0x74, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x52, 0x07, 0x62, 0x61, 0x74, 0x74, 0x65,
	0x72, 0x79, 0x12, 0x21, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x52, 0x74, 0x4b, 0x65, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x7a, 0x6f, 0x6e,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0f, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e,
	0x65, 0x12, 0x33, 0x0a, 0x0c, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x74, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0c, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x87, 0x01, 0x0a, 0x07, 0x52, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x07, 0x2e, 0x52, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x21, 0x0a, 0x07, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x07, 0x2e, 0x52, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x07, 0x62, 0x61, 0x74, 0x74, 0x65,
	0x72, 0x79, 0x12, 0x1f, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x07, 0x2e, 0x52, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x07, 0x2e, 0x52, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x22, 0x65, 0x0a, 0x0c, 0x52, 0x74, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x02, 0x28, 0x07, 0x52, 0x03,
	0x73, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x07, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x70, 0x0a, 0x0e, 0x52, 0x74, 0x44, 0x74, 0x64,
	0x61, 0x5f, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x05, 0x73, 0x74,
	0x65, 0x70, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x07, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6f, 0x72, 0x69, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x07,
	0x52, 0x07, 0x63, 0x61, 0x6c, 0x6f, 0x72, 0x69, 0x65, 0x22, 0xf1, 0x02, 0x0a, 0x0b, 0x52, 0x74,
	0x53, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x64, 0x5f,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52,
	0x0b, 0x73, 0x64, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x68, 0x72, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x07,
	0x68, 0x72, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x72, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x07, 0x52, 0x07, 0x68, 0x72, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x07, 0x52, 0x0c, 0x72, 0x65, 0x61, 0x6c, 0x74,
	0x69, 0x6d, 0x65, 0x50, 0x61, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x61, 0x6c, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x73, 0x70, 0x6d, 0x18, 0x05, 0x20, 0x02, 0x28, 0x07, 0x52, 0x0b, 0x72,
	0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65,
	0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x68, 0x72, 0x18, 0x06, 0x20, 0x02, 0x28, 0x07, 0x52,
	0x0a, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x48, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x77, 0x69, 0x6d, 0x5f, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x02, 0x28, 0x07,
	0x52, 0x0a, 0x73, 0x77, 0x69, 0x6d, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x77, 0x69, 0x6d, 0x5f, 0x73, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x18, 0x08, 0x20, 0x02, 0x28,
	0x07, 0x52, 0x0a, 0x73, 0x77, 0x69, 0x6d, 0x53, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x12, 0x2e, 0x0a,
	0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x09, 0x20, 0x02, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x74, 0x44, 0x74, 0x64, 0x61, 0x5f, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2e, 0x0a,
	0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x0a, 0x20, 0x02, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x74, 0x44, 0x74, 0x64, 0x61, 0x5f, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x22, 0xcd, 0x01,
	0x0a, 0x0e, 0x52, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x22, 0x0a, 0x07, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x52, 0x74, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x06, 0x72, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x08, 0x72, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x48, 0x00, 0x52, 0x07, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x34, 0x0a, 0x0d, 0x72,
	0x74, 0x5f, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x52, 0x74, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x74, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x32, 0x0a, 0x0d, 0x72, 0x74, 0x5f, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x52, 0x74, 0x53, 0x70, 0x6f,
	0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x74, 0x53, 0x70, 0x6f, 0x72,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0xd9, 0x01,
	0x0a, 0x06, 0x52, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x54, 0x5f, 0x4d,
	0x4f, 0x44, 0x45, 0x5f, 0x42, 0x41, 0x43, 0x4b, 0x5f, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10,
	0x00, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x54, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x45, 0x4e, 0x54,
	0x45, 0x52, 0x5f, 0x43, 0x41, 0x4d, 0x45, 0x52, 0x41, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x52,
	0x54, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x46, 0x49, 0x4e, 0x44, 0x5f, 0x57, 0x41, 0x54,
	0x43, 0x48, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54,
	0x5f, 0x44, 0x46, 0x55, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x52,
	0x54, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x48, 0x52, 0x5f, 0x4d, 0x45, 0x41, 0x53, 0x55, 0x52,
	0x45, 0x10, 0x04, 0x12, 0x1b, 0x0a, 0x17, 0x52, 0x54, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x46,
	0x41, 0x54, 0x49, 0x47, 0x55, 0x45, 0x5f, 0x4d, 0x45, 0x41, 0x53, 0x55, 0x52, 0x45, 0x10, 0x05,
	0x12, 0x1c, 0x0a, 0x18, 0x52, 0x54, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x50, 0x52, 0x45, 0x53,
	0x53, 0x55, 0x52, 0x45, 0x5f, 0x4d, 0x45, 0x41, 0x53, 0x55, 0x52, 0x45, 0x10, 0x06, 0x12, 0x19,
	0x0a, 0x15, 0x52, 0x54, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x5f, 0x4d, 0x45, 0x41, 0x53, 0x55, 0x52,
	0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x07, 0x2a, 0xfe, 0x01, 0x0a, 0x0a, 0x52, 0x74,
	0x4b, 0x65, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x54, 0x5f, 0x4b,
	0x45, 0x59, 0x5f, 0x43, 0x41, 0x4d, 0x45, 0x52, 0x41, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x52,
	0x54, 0x5f, 0x4b, 0x45, 0x59, 0x5f, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x5f, 0x50, 0x4c, 0x41, 0x59,
	0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x54, 0x5f, 0x4b, 0x45, 0x59, 0x5f, 0x41, 0x55, 0x44,
	0x49, 0x4f, 0x5f, 0x50, 0x52, 0x45, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x54, 0x5f, 0x4b,
	0x45, 0x59, 0x5f, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x5f, 0x4e, 0x45, 0x58, 0x54, 0x10, 0x03, 0x12,
	0x1a, 0x0a, 0x16, 0x52, 0x54, 0x5f, 0x4b, 0x45, 0x59, 0x5f, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x5f,
	0x56, 0x4f, 0x4c, 0x55, 0x4d, 0x45, 0x5f, 0x55, 0x50, 0x10, 0x04, 0x12, 0x1c, 0x0a, 0x18, 0x52,
	0x54, 0x5f, 0x4b, 0x45, 0x59, 0x5f, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x5f, 0x56, 0x4f, 0x4c, 0x55,
	0x4d, 0x45, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x05, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x54, 0x5f,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x46, 0x49, 0x4e, 0x44, 0x5f, 0x50, 0x48, 0x4f, 0x4e, 0x45,
	0x10, 0x06, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x54, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x46, 0x49,
	0x4e, 0x44, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x10, 0x07, 0x12, 0x18, 0x0a, 0x14, 0x52,
	0x54, 0x5f, 0x4c, 0x4e, 0x5f, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x5f, 0x4d, 0x45, 0x41, 0x53,
	0x55, 0x52, 0x45, 0x10, 0x08, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x54, 0x5f, 0x4e, 0x4f, 0x4e, 0x45,
	0x5f, 0x4d, 0x45, 0x41, 0x53, 0x55, 0x52, 0x45, 0x10, 0x09, 0x2a, 0xa7, 0x01, 0x0a, 0x06, 0x52,
	0x74, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x41, 0x4c,
	0x4c, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x4e, 0x4c, 0x59, 0x5f, 0x4f, 0x4e, 0x43, 0x45,
	0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4f, 0x4e, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x5f, 0x43,
	0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x4e, 0x5f, 0x53, 0x45,
	0x43, 0x4f, 0x4e, 0x44, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x03, 0x12, 0x14, 0x0a,
	0x10, 0x4f, 0x4e, 0x5f, 0x4d, 0x49, 0x4e, 0x55, 0x54, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47,
	0x45, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x4e, 0x5f, 0x48, 0x4f, 0x55, 0x52, 0x5f, 0x43,
	0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x4f, 0x4e, 0x5f, 0x44, 0x41,
	0x59, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x06, 0x12, 0x18, 0x0a, 0x14, 0x4f, 0x4e,
	0x5f, 0x54, 0x45, 0x4e, 0x5f, 0x4d, 0x49, 0x4e, 0x55, 0x54, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e,
	0x47, 0x45, 0x10, 0x07, 0x2a, 0x9c, 0x02, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x45, 0x43, 0x47, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x50, 0x47, 0x10, 0x02, 0x12,
	0x07, 0x0a, 0x03, 0x4d, 0x41, 0x47, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x59, 0x52, 0x4f,
	0x10, 0x08, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x43, 0x43, 0x10, 0x10, 0x12, 0x06, 0x0a, 0x02, 0x42,
	0x50, 0x10, 0x20, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x50, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10,
	0x40, 0x12, 0x10, 0x0a, 0x0b, 0x54, 0x45, 0x4d, 0x50, 0x45, 0x52, 0x41, 0x54, 0x55, 0x52, 0x45,
	0x10, 0x80, 0x01, 0x12, 0x0c, 0x0a, 0x07, 0x54, 0x57, 0x4f, 0x5f, 0x45, 0x43, 0x47, 0x10, 0x80,
	0x02, 0x12, 0x09, 0x0a, 0x04, 0x42, 0x49, 0x4f, 0x5a, 0x10, 0x80, 0x04, 0x12, 0x0f, 0x0a, 0x0a,
	0x45, 0x43, 0x47, 0x5f, 0x44, 0x45, 0x54, 0x45, 0x43, 0x54, 0x10, 0x80, 0x08, 0x12, 0x10, 0x0a,
	0x0b, 0x46, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x45, 0x43, 0x47, 0x10, 0x80, 0x10, 0x12,
	0x11, 0x0a, 0x0c, 0x46, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x42, 0x49, 0x4f, 0x5a, 0x10,
	0x80, 0x20, 0x12, 0x0c, 0x0a, 0x07, 0x48, 0x52, 0x5f, 0x4c, 0x45, 0x41, 0x4b, 0x10, 0x80, 0x40,
	0x12, 0x0d, 0x0a, 0x07, 0x42, 0x50, 0x5f, 0x4c, 0x45, 0x41, 0x4b, 0x10, 0x80, 0x80, 0x01, 0x12,
	0x0a, 0x0a, 0x04, 0x53, 0x50, 0x4f, 0x32, 0x10, 0x80, 0x80, 0x02, 0x12, 0x09, 0x0a, 0x03, 0x4f,
	0x41, 0x51, 0x10, 0x80, 0x80, 0x04, 0x12, 0x09, 0x0a, 0x03, 0x49, 0x41, 0x51, 0x10, 0x80, 0x80,
	0x08, 0x12, 0x0e, 0x0a, 0x08, 0x48, 0x55, 0x4d, 0x49, 0x54, 0x55, 0x52, 0x45, 0x10, 0x80, 0x80,
	0x10, 0x12, 0x10, 0x0a, 0x0a, 0x55, 0x4c, 0x54, 0x52, 0x41, 0x53, 0x4f, 0x4e, 0x49, 0x43, 0x10,
	0x80, 0x80, 0x20, 0x2a, 0x55, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x45, 0x4e, 0x53, 0x4f, 0x52,
	0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x53, 0x59, 0x4e, 0x43, 0x10, 0x00, 0x12, 0x15, 0x0a,
	0x11, 0x53, 0x45, 0x4e, 0x53, 0x4f, 0x52, 0x5f, 0x50, 0x41, 0x55, 0x53, 0x45, 0x5f, 0x53, 0x59,
	0x4e, 0x43, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x45, 0x4e, 0x53, 0x4f, 0x52, 0x5f, 0x53,
	0x54, 0x4f, 0x50, 0x5f, 0x53, 0x59, 0x4e, 0x43, 0x10, 0x02, 0x2a, 0x42, 0x0a, 0x0e, 0x53, 0x70,
	0x6f, 0x72, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x0a, 0x0b,
	0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x50, 0x41, 0x55, 0x53, 0x45, 0x10, 0x01, 0x12, 0x0e,
	0x0a, 0x0a, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x02, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x69, 0x77, 0x6f, 0x77, 0x6e,
}

var (
	file_realtime_data_proto_rawDescOnce sync.Once
	file_realtime_data_proto_rawDescData = file_realtime_data_proto_rawDesc
)

func file_realtime_data_proto_rawDescGZIP() []byte {
	file_realtime_data_proto_rawDescOnce.Do(func() {
		file_realtime_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_realtime_data_proto_rawDescData)
	})
	return file_realtime_data_proto_rawDescData
}

var file_realtime_data_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_realtime_data_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_realtime_data_proto_goTypes = []interface{}{
	(RtMode)(0),            // 0: RtMode
	(RtKeyEvent)(0),        // 1: RtKeyEvent
	(RtSync)(0),            // 2: RtSync
	(SensorType)(0),        // 3: SensorType
	(SensorOperation)(0),   // 4: SensorOperation
	(SportOperation)(0),    // 5: SportOperation
	(*RtTime)(nil),         // 6: RtTime
	(*DateTime)(nil),       // 7: DateTime
	(*RtBattery)(nil),      // 8: RtBattery
	(*RtHealth)(nil),       // 9: RtHealth
	(*BPresult)(nil),       // 10: BPresult
	(*RtHealthResult)(nil), // 11: RtHealthResult
	(*RtGNSS)(nil),         // 12: RtGNSS
	(*RtSensor)(nil),       // 13: RtSensor
	(*Rtsport)(nil),        // 14: Rtsport
	(*RtSubscriber)(nil),   // 15: RtSubscriber
	(*RtData)(nil),         // 16: RtData
	(*RtState)(nil),        // 17: RtState
	(*RtSensorData)(nil),   // 18: RtSensorData
	(*RtDtda_Summary)(nil), // 19: RtDtda_Summary
	(*RtSportData)(nil),    // 20: RtSportData
	(*RtNotification)(nil), // 21: RtNotification
}
var file_realtime_data_proto_depIdxs = []int32{
	6,  // 0: DateTime.date_time:type_name -> RtTime
	10, // 1: RtHealthResult.bp:type_name -> BPresult
	4,  // 2: RtSensor.operation:type_name -> SensorOperation
	5,  // 3: Rtsport.operation:type_name -> SportOperation
	2,  // 4: RtSubscriber.time:type_name -> RtSync
	2,  // 5: RtSubscriber.battery:type_name -> RtSync
	2,  // 6: RtSubscriber.health:type_name -> RtSync
	0,  // 7: RtSubscriber.mode:type_name -> RtMode
	13, // 8: RtSubscriber.sensor:type_name -> RtSensor
	14, // 9: RtSubscriber.sport:type_name -> Rtsport
	6,  // 10: RtData.time:type_name -> RtTime
	8,  // 11: RtData.battery:type_name -> RtBattery
	9,  // 12: RtData.health:type_name -> RtHealth
	1,  // 13: RtData.key:type_name -> RtKeyEvent
	11, // 14: RtData.healthresult:type_name -> RtHealthResult
	2,  // 15: RtState.time:type_name -> RtSync
	2,  // 16: RtState.battery:type_name -> RtSync
	2,  // 17: RtState.health:type_name -> RtSync
	0,  // 18: RtState.mode:type_name -> RtMode
	6,  // 19: RtSensorData.time:type_name -> RtTime
	19, // 20: RtSportData.data_total:type_name -> RtDtda_Summary
	19, // 21: RtSportData.data_sport:type_name -> RtDtda_Summary
	16, // 22: RtNotification.rt_data:type_name -> RtData
	17, // 23: RtNotification.rt_state:type_name -> RtState
	18, // 24: RtNotification.rt_sensordata:type_name -> RtSensorData
	20, // 25: RtNotification.rt_sport_data:type_name -> RtSportData
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_realtime_data_proto_init() }
func file_realtime_data_proto_init() {
	if File_realtime_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_realtime_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realtime_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DateTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realtime_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtBattery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realtime_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtHealth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realtime_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BPresult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realtime_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtHealthResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realtime_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtGNSS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realtime_data_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtSensor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realtime_data_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rtsport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realtime_data_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtSubscriber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realtime_data_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realtime_data_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realtime_data_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtSensorData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realtime_data_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtDtda_Summary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realtime_data_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtSportData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realtime_data_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_realtime_data_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*RtNotification_RtData)(nil),
		(*RtNotification_RtState)(nil),
		(*RtNotification_RtSensordata)(nil),
		(*RtNotification_RtSportData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_realtime_data_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_realtime_data_proto_goTypes,
		DependencyIndexes: file_realtime_data_proto_depIdxs,
		EnumInfos:         file_realtime_data_proto_enumTypes,
		MessageInfos:      file_realtime_data_proto_msgTypes,
	}.Build()
	File_realtime_data_proto = out.File
	file_realtime_data_proto_rawDesc = nil
	file_realtime_data_proto_goTypes = nil
	file_realtime_data_proto_depIdxs = nil
}
