// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: ThirdParty_health_data.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MEASURE_MODE int32

const (
	MEASURE_MODE_MANUAL MEASURE_MODE = 0
	MEASURE_MODE_AUTO   MEASURE_MODE = 1
)

// Enum value maps for MEASURE_MODE.
var (
	MEASURE_MODE_name = map[int32]string{
		0: "MANUAL",
		1: "AUTO",
	}
	MEASURE_MODE_value = map[string]int32{
		"MANUAL": 0,
		"AUTO":   1,
	}
)

func (x MEASURE_MODE) Enum() *MEASURE_MODE {
	p := new(MEASURE_MODE)
	*p = x
	return p
}

func (x MEASURE_MODE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MEASURE_MODE) Descriptor() protoreflect.EnumDescriptor {
	return file_ThirdParty_health_data_proto_enumTypes[0].Descriptor()
}

func (MEASURE_MODE) Type() protoreflect.EnumType {
	return &file_ThirdParty_health_data_proto_enumTypes[0]
}

func (x MEASURE_MODE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MEASURE_MODE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MEASURE_MODE(num)
	return nil
}

// Deprecated: Use MEASURE_MODE.Descriptor instead.
func (MEASURE_MODE) EnumDescriptor() ([]byte, []int) {
	return file_ThirdParty_health_data_proto_rawDescGZIP(), []int{0}
}

type ThirdPartyHealthBp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sbp   *uint32       `protobuf:"fixed32,1,req,name=sbp" json:"sbp,omitempty"`
	Dbp   *uint32       `protobuf:"fixed32,2,req,name=dbp" json:"dbp,omitempty"`
	Hr    *uint32       `protobuf:"fixed32,3,req,name=hr" json:"hr,omitempty"`
	Pulse *uint32       `protobuf:"fixed32,4,req,name=pulse" json:"pulse,omitempty"`
	Time  *DateTime     `protobuf:"bytes,5,req,name=time" json:"time,omitempty"`
	MODE  *MEASURE_MODE `protobuf:"varint,6,req,name=MODE,enum=MEASURE_MODE" json:"MODE,omitempty"`
}

func (x *ThirdPartyHealthBp) Reset() {
	*x = ThirdPartyHealthBp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ThirdParty_health_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdPartyHealthBp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyHealthBp) ProtoMessage() {}

func (x *ThirdPartyHealthBp) ProtoReflect() protoreflect.Message {
	mi := &file_ThirdParty_health_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyHealthBp.ProtoReflect.Descriptor instead.
func (*ThirdPartyHealthBp) Descriptor() ([]byte, []int) {
	return file_ThirdParty_health_data_proto_rawDescGZIP(), []int{0}
}

func (x *ThirdPartyHealthBp) GetSbp() uint32 {
	if x != nil && x.Sbp != nil {
		return *x.Sbp
	}
	return 0
}

func (x *ThirdPartyHealthBp) GetDbp() uint32 {
	if x != nil && x.Dbp != nil {
		return *x.Dbp
	}
	return 0
}

func (x *ThirdPartyHealthBp) GetHr() uint32 {
	if x != nil && x.Hr != nil {
		return *x.Hr
	}
	return 0
}

func (x *ThirdPartyHealthBp) GetPulse() uint32 {
	if x != nil && x.Pulse != nil {
		return *x.Pulse
	}
	return 0
}

func (x *ThirdPartyHealthBp) GetTime() *DateTime {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ThirdPartyHealthBp) GetMODE() MEASURE_MODE {
	if x != nil && x.MODE != nil {
		return *x.MODE
	}
	return MEASURE_MODE_MANUAL
}

type ThirdPartyHealthScale struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weight            *uint32   `protobuf:"fixed32,1,req,name=weight" json:"weight,omitempty"`
	Impedance         *uint32   `protobuf:"fixed32,2,req,name=impedance" json:"impedance,omitempty"`
	Uints             *uint32   `protobuf:"fixed32,3,req,name=uints" json:"uints,omitempty"`
	BodyFatPercentage *uint32   `protobuf:"fixed32,4,req,name=body_fat_percentage,json=bodyFatPercentage" json:"body_fat_percentage,omitempty"`
	Time              *DateTime `protobuf:"bytes,5,req,name=time" json:"time,omitempty"`
}

func (x *ThirdPartyHealthScale) Reset() {
	*x = ThirdPartyHealthScale{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ThirdParty_health_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdPartyHealthScale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyHealthScale) ProtoMessage() {}

func (x *ThirdPartyHealthScale) ProtoReflect() protoreflect.Message {
	mi := &file_ThirdParty_health_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyHealthScale.ProtoReflect.Descriptor instead.
func (*ThirdPartyHealthScale) Descriptor() ([]byte, []int) {
	return file_ThirdParty_health_data_proto_rawDescGZIP(), []int{1}
}

func (x *ThirdPartyHealthScale) GetWeight() uint32 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *ThirdPartyHealthScale) GetImpedance() uint32 {
	if x != nil && x.Impedance != nil {
		return *x.Impedance
	}
	return 0
}

func (x *ThirdPartyHealthScale) GetUints() uint32 {
	if x != nil && x.Uints != nil {
		return *x.Uints
	}
	return 0
}

func (x *ThirdPartyHealthScale) GetBodyFatPercentage() uint32 {
	if x != nil && x.BodyFatPercentage != nil {
		return *x.BodyFatPercentage
	}
	return 0
}

func (x *ThirdPartyHealthScale) GetTime() *DateTime {
	if x != nil {
		return x.Time
	}
	return nil
}

type ThirdPartyHealthSpo2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bpm  *uint32   `protobuf:"fixed32,1,req,name=bpm" json:"bpm,omitempty"`
	Spo2 *uint32   `protobuf:"fixed32,2,req,name=spo2" json:"spo2,omitempty"`
	Pi   *uint32   `protobuf:"fixed32,3,req,name=pi" json:"pi,omitempty"`
	Time *DateTime `protobuf:"bytes,4,req,name=time" json:"time,omitempty"`
}

func (x *ThirdPartyHealthSpo2) Reset() {
	*x = ThirdPartyHealthSpo2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ThirdParty_health_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdPartyHealthSpo2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyHealthSpo2) ProtoMessage() {}

func (x *ThirdPartyHealthSpo2) ProtoReflect() protoreflect.Message {
	mi := &file_ThirdParty_health_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyHealthSpo2.ProtoReflect.Descriptor instead.
func (*ThirdPartyHealthSpo2) Descriptor() ([]byte, []int) {
	return file_ThirdParty_health_data_proto_rawDescGZIP(), []int{2}
}

func (x *ThirdPartyHealthSpo2) GetBpm() uint32 {
	if x != nil && x.Bpm != nil {
		return *x.Bpm
	}
	return 0
}

func (x *ThirdPartyHealthSpo2) GetSpo2() uint32 {
	if x != nil && x.Spo2 != nil {
		return *x.Spo2
	}
	return 0
}

func (x *ThirdPartyHealthSpo2) GetPi() uint32 {
	if x != nil && x.Pi != nil {
		return *x.Pi
	}
	return 0
}

func (x *ThirdPartyHealthSpo2) GetTime() *DateTime {
	if x != nil {
		return x.Time
	}
	return nil
}

type ThirdPartyHealthTemp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BodyTemp *uint32   `protobuf:"fixed32,1,req,name=body_temp,json=bodyTemp" json:"body_temp,omitempty"`
	Time     *DateTime `protobuf:"bytes,2,req,name=time" json:"time,omitempty"`
}

func (x *ThirdPartyHealthTemp) Reset() {
	*x = ThirdPartyHealthTemp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ThirdParty_health_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdPartyHealthTemp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyHealthTemp) ProtoMessage() {}

func (x *ThirdPartyHealthTemp) ProtoReflect() protoreflect.Message {
	mi := &file_ThirdParty_health_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyHealthTemp.ProtoReflect.Descriptor instead.
func (*ThirdPartyHealthTemp) Descriptor() ([]byte, []int) {
	return file_ThirdParty_health_data_proto_rawDescGZIP(), []int{3}
}

func (x *ThirdPartyHealthTemp) GetBodyTemp() uint32 {
	if x != nil && x.BodyTemp != nil {
		return *x.BodyTemp
	}
	return 0
}

func (x *ThirdPartyHealthTemp) GetTime() *DateTime {
	if x != nil {
		return x.Time
	}
	return nil
}

type ThirdPartyHealthGlu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Glu  *uint32   `protobuf:"fixed32,1,req,name=glu" json:"glu,omitempty"`
	Time *DateTime `protobuf:"bytes,2,req,name=time" json:"time,omitempty"`
}

func (x *ThirdPartyHealthGlu) Reset() {
	*x = ThirdPartyHealthGlu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ThirdParty_health_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdPartyHealthGlu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyHealthGlu) ProtoMessage() {}

func (x *ThirdPartyHealthGlu) ProtoReflect() protoreflect.Message {
	mi := &file_ThirdParty_health_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyHealthGlu.ProtoReflect.Descriptor instead.
func (*ThirdPartyHealthGlu) Descriptor() ([]byte, []int) {
	return file_ThirdParty_health_data_proto_rawDescGZIP(), []int{4}
}

func (x *ThirdPartyHealthGlu) GetGlu() uint32 {
	if x != nil && x.Glu != nil {
		return *x.Glu
	}
	return 0
}

func (x *ThirdPartyHealthGlu) GetTime() *DateTime {
	if x != nil {
		return x.Time
	}
	return nil
}

type ThirdPartyHealthBloodKetones struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BloodKetones *uint32   `protobuf:"fixed32,1,req,name=BloodKetones" json:"BloodKetones,omitempty"`
	Time         *DateTime `protobuf:"bytes,2,req,name=time" json:"time,omitempty"`
}

func (x *ThirdPartyHealthBloodKetones) Reset() {
	*x = ThirdPartyHealthBloodKetones{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ThirdParty_health_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdPartyHealthBloodKetones) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyHealthBloodKetones) ProtoMessage() {}

func (x *ThirdPartyHealthBloodKetones) ProtoReflect() protoreflect.Message {
	mi := &file_ThirdParty_health_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyHealthBloodKetones.ProtoReflect.Descriptor instead.
func (*ThirdPartyHealthBloodKetones) Descriptor() ([]byte, []int) {
	return file_ThirdParty_health_data_proto_rawDescGZIP(), []int{5}
}

func (x *ThirdPartyHealthBloodKetones) GetBloodKetones() uint32 {
	if x != nil && x.BloodKetones != nil {
		return *x.BloodKetones
	}
	return 0
}

func (x *ThirdPartyHealthBloodKetones) GetTime() *DateTime {
	if x != nil {
		return x.Time
	}
	return nil
}

type ThirdPartyHealthUricAcid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UricAcid *uint32   `protobuf:"fixed32,1,req,name=UricAcid" json:"UricAcid,omitempty"`
	Time     *DateTime `protobuf:"bytes,2,req,name=time" json:"time,omitempty"`
}

func (x *ThirdPartyHealthUricAcid) Reset() {
	*x = ThirdPartyHealthUricAcid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ThirdParty_health_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdPartyHealthUricAcid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyHealthUricAcid) ProtoMessage() {}

func (x *ThirdPartyHealthUricAcid) ProtoReflect() protoreflect.Message {
	mi := &file_ThirdParty_health_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyHealthUricAcid.ProtoReflect.Descriptor instead.
func (*ThirdPartyHealthUricAcid) Descriptor() ([]byte, []int) {
	return file_ThirdParty_health_data_proto_rawDescGZIP(), []int{6}
}

func (x *ThirdPartyHealthUricAcid) GetUricAcid() uint32 {
	if x != nil && x.UricAcid != nil {
		return *x.UricAcid
	}
	return 0
}

func (x *ThirdPartyHealthUricAcid) GetTime() *DateTime {
	if x != nil {
		return x.Time
	}
	return nil
}

type ThirdPartyDataHealth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DevName          *string                       `protobuf:"bytes,1,req,name=dev_name,json=devName" json:"dev_name,omitempty"`
	MacAddr          *string                       `protobuf:"bytes,2,req,name=mac_addr,json=macAddr" json:"mac_addr,omitempty"`
	DevType          *uint32                       `protobuf:"fixed32,3,req,name=dev_type,json=devType" json:"dev_type,omitempty"`
	User             *uint32                       `protobuf:"fixed32,4,req,name=user" json:"user,omitempty"`
	BpData           *ThirdPartyHealthBp           `protobuf:"bytes,5,opt,name=bp_data,json=bpData" json:"bp_data,omitempty"`
	ScaleData        *ThirdPartyHealthScale        `protobuf:"bytes,6,opt,name=scale_data,json=scaleData" json:"scale_data,omitempty"`
	Spo2Data         *ThirdPartyHealthSpo2         `protobuf:"bytes,7,opt,name=Spo2_data,json=Spo2Data" json:"Spo2_data,omitempty"`
	TempData         *ThirdPartyHealthTemp         `protobuf:"bytes,8,opt,name=Temp_data,json=TempData" json:"Temp_data,omitempty"`
	GluData          *ThirdPartyHealthGlu          `protobuf:"bytes,9,opt,name=Glu_data,json=GluData" json:"Glu_data,omitempty"`
	BloodKetonesData *ThirdPartyHealthBloodKetones `protobuf:"bytes,10,opt,name=BloodKetones_data,json=BloodKetonesData" json:"BloodKetones_data,omitempty"`
	UricAcidData     *ThirdPartyHealthUricAcid     `protobuf:"bytes,11,opt,name=UricAcid_data,json=UricAcidData" json:"UricAcid_data,omitempty"`
}

func (x *ThirdPartyDataHealth) Reset() {
	*x = ThirdPartyDataHealth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ThirdParty_health_data_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdPartyDataHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyDataHealth) ProtoMessage() {}

func (x *ThirdPartyDataHealth) ProtoReflect() protoreflect.Message {
	mi := &file_ThirdParty_health_data_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyDataHealth.ProtoReflect.Descriptor instead.
func (*ThirdPartyDataHealth) Descriptor() ([]byte, []int) {
	return file_ThirdParty_health_data_proto_rawDescGZIP(), []int{7}
}

func (x *ThirdPartyDataHealth) GetDevName() string {
	if x != nil && x.DevName != nil {
		return *x.DevName
	}
	return ""
}

func (x *ThirdPartyDataHealth) GetMacAddr() string {
	if x != nil && x.MacAddr != nil {
		return *x.MacAddr
	}
	return ""
}

func (x *ThirdPartyDataHealth) GetDevType() uint32 {
	if x != nil && x.DevType != nil {
		return *x.DevType
	}
	return 0
}

func (x *ThirdPartyDataHealth) GetUser() uint32 {
	if x != nil && x.User != nil {
		return *x.User
	}
	return 0
}

func (x *ThirdPartyDataHealth) GetBpData() *ThirdPartyHealthBp {
	if x != nil {
		return x.BpData
	}
	return nil
}

func (x *ThirdPartyDataHealth) GetScaleData() *ThirdPartyHealthScale {
	if x != nil {
		return x.ScaleData
	}
	return nil
}

func (x *ThirdPartyDataHealth) GetSpo2Data() *ThirdPartyHealthSpo2 {
	if x != nil {
		return x.Spo2Data
	}
	return nil
}

func (x *ThirdPartyDataHealth) GetTempData() *ThirdPartyHealthTemp {
	if x != nil {
		return x.TempData
	}
	return nil
}

func (x *ThirdPartyDataHealth) GetGluData() *ThirdPartyHealthGlu {
	if x != nil {
		return x.GluData
	}
	return nil
}

func (x *ThirdPartyDataHealth) GetBloodKetonesData() *ThirdPartyHealthBloodKetones {
	if x != nil {
		return x.BloodKetonesData
	}
	return nil
}

func (x *ThirdPartyDataHealth) GetUricAcidData() *ThirdPartyHealthUricAcid {
	if x != nil {
		return x.UricAcidData
	}
	return nil
}

type HisDataThirdParty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataHealth *ThirdPartyDataHealth `protobuf:"bytes,1,opt,name=DataHealth" json:"DataHealth,omitempty"`
}

func (x *HisDataThirdParty) Reset() {
	*x = HisDataThirdParty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ThirdParty_health_data_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisDataThirdParty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisDataThirdParty) ProtoMessage() {}

func (x *HisDataThirdParty) ProtoReflect() protoreflect.Message {
	mi := &file_ThirdParty_health_data_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisDataThirdParty.ProtoReflect.Descriptor instead.
func (*HisDataThirdParty) Descriptor() ([]byte, []int) {
	return file_ThirdParty_health_data_proto_rawDescGZIP(), []int{8}
}

func (x *HisDataThirdParty) GetDataHealth() *ThirdPartyDataHealth {
	if x != nil {
		return x.DataHealth
	}
	return nil
}

var File_ThirdParty_health_data_proto protoreflect.FileDescriptor

var file_ThirdParty_health_data_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13,
	0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x01, 0x0a, 0x12, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72,
	0x74, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x62,
	0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x03, 0x73, 0x62, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x64, 0x62, 0x70, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x03, 0x64, 0x62, 0x70, 0x12, 0x0e,
	0x0a, 0x02, 0x68, 0x72, 0x18, 0x03, 0x20, 0x02, 0x28, 0x07, 0x52, 0x02, 0x68, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x75, 0x6c, 0x73, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x07, 0x52, 0x05, 0x70,
	0x75, 0x6c, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x4d, 0x4f, 0x44, 0x45, 0x18, 0x06, 0x20, 0x02, 0x28,
	0x0e, 0x32, 0x0d, 0x2e, 0x4d, 0x45, 0x41, 0x53, 0x55, 0x52, 0x45, 0x5f, 0x4d, 0x4f, 0x44, 0x45,
	0x52, 0x04, 0x4d, 0x4f, 0x44, 0x45, 0x22, 0xb2, 0x01, 0x0a, 0x15, 0x54, 0x68, 0x69, 0x72, 0x64,
	0x50, 0x61, 0x72, 0x74, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x63, 0x61, 0x6c, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07,
	0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x70, 0x65,
	0x64, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x07, 0x52, 0x09, 0x69, 0x6d, 0x70,
	0x65, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x69, 0x6e, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x07, 0x52, 0x05, 0x75, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x2e, 0x0a, 0x13,
	0x62, 0x6f, 0x64, 0x79, 0x5f, 0x66, 0x61, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x07, 0x52, 0x11, 0x62, 0x6f, 0x64, 0x79, 0x46,
	0x61, 0x74, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x6b, 0x0a, 0x14, 0x54,
	0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x53,
	0x70, 0x6f, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x70, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07,
	0x52, 0x03, 0x62, 0x70, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x70, 0x6f, 0x32, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x07, 0x52, 0x04, 0x73, 0x70, 0x6f, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x69, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x07, 0x52, 0x02, 0x70, 0x69, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x52, 0x0a, 0x14, 0x54, 0x68, 0x69, 0x72,
	0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x54, 0x65, 0x6d, 0x70,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x07, 0x52, 0x08, 0x62, 0x6f, 0x64, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x12, 0x1d, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x46, 0x0a, 0x13,
	0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x47, 0x6c, 0x75, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x6c, 0x75, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07,
	0x52, 0x03, 0x67, 0x6c, 0x75, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x22, 0x61, 0x0a, 0x1c, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72,
	0x74, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x6c, 0x6f, 0x6f, 0x64, 0x4b, 0x65, 0x74,
	0x6f, 0x6e, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x42, 0x6c, 0x6f, 0x6f, 0x64, 0x4b, 0x65, 0x74,
	0x6f, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x0c, 0x42, 0x6c, 0x6f, 0x6f,
	0x64, 0x4b, 0x65, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x55, 0x0a, 0x18, 0x54, 0x68, 0x69, 0x72, 0x64,
	0x50, 0x61, 0x72, 0x74, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x55, 0x72, 0x69, 0x63, 0x41,
	0x63, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x72, 0x69, 0x63, 0x41, 0x63, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x07, 0x52, 0x08, 0x55, 0x72, 0x69, 0x63, 0x41, 0x63, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x85,
	0x04, 0x0a, 0x14, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x44, 0x61, 0x74,
	0x61, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x76, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x12, 0x19, 0x0a,
	0x08, 0x64, 0x65, 0x76, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x07, 0x52,
	0x07, 0x64, 0x65, 0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x02, 0x28, 0x07, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x07,
	0x62, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x42, 0x70, 0x52, 0x06, 0x62, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x0a, 0x73, 0x63,
	0x61, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x52, 0x09, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x32, 0x0a, 0x09, 0x53, 0x70, 0x6f, 0x32, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74,
	0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x70, 0x6f, 0x32, 0x52, 0x08, 0x53, 0x70, 0x6f,
	0x32, 0x44, 0x61, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x09, 0x54, 0x65, 0x6d, 0x70, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x54, 0x68, 0x69, 0x72, 0x64,
	0x50, 0x61, 0x72, 0x74, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x54, 0x65, 0x6d, 0x70, 0x52,
	0x08, 0x54, 0x65, 0x6d, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x08, 0x47, 0x6c, 0x75,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x54, 0x68,
	0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x47, 0x6c,
	0x75, 0x52, 0x07, 0x47, 0x6c, 0x75, 0x44, 0x61, 0x74, 0x61, 0x12, 0x4a, 0x0a, 0x11, 0x42, 0x6c,
	0x6f, 0x6f, 0x64, 0x4b, 0x65, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72,
	0x74, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x6c, 0x6f, 0x6f, 0x64, 0x4b, 0x65, 0x74,
	0x6f, 0x6e, 0x65, 0x73, 0x52, 0x10, 0x42, 0x6c, 0x6f, 0x6f, 0x64, 0x4b, 0x65, 0x74, 0x6f, 0x6e,
	0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3e, 0x0a, 0x0d, 0x55, 0x72, 0x69, 0x63, 0x41, 0x63,
	0x69, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x55, 0x72, 0x69, 0x63, 0x41, 0x63, 0x69, 0x64, 0x52, 0x0c, 0x55, 0x72, 0x69, 0x63, 0x41, 0x63,
	0x69, 0x64, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4a, 0x0a, 0x11, 0x48, 0x69, 0x73, 0x44, 0x61, 0x74,
	0x61, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x12, 0x35, 0x0a, 0x0a, 0x44,
	0x61, 0x74, 0x61, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x2a, 0x24, 0x0a, 0x0c, 0x4d, 0x45, 0x41, 0x53, 0x55, 0x52, 0x45, 0x5f, 0x4d, 0x4f,
	0x44, 0x45, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x41, 0x4e, 0x55, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x41, 0x55, 0x54, 0x4f, 0x10, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x69, 0x77,
	0x6f, 0x77, 0x6e,
}

var (
	file_ThirdParty_health_data_proto_rawDescOnce sync.Once
	file_ThirdParty_health_data_proto_rawDescData = file_ThirdParty_health_data_proto_rawDesc
)

func file_ThirdParty_health_data_proto_rawDescGZIP() []byte {
	file_ThirdParty_health_data_proto_rawDescOnce.Do(func() {
		file_ThirdParty_health_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_ThirdParty_health_data_proto_rawDescData)
	})
	return file_ThirdParty_health_data_proto_rawDescData
}

var file_ThirdParty_health_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ThirdParty_health_data_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ThirdParty_health_data_proto_goTypes = []interface{}{
	(MEASURE_MODE)(0),                    // 0: MEASURE_MODE
	(*ThirdPartyHealthBp)(nil),           // 1: ThirdPartyHealthBp
	(*ThirdPartyHealthScale)(nil),        // 2: ThirdPartyHealthScale
	(*ThirdPartyHealthSpo2)(nil),         // 3: ThirdPartyHealthSpo2
	(*ThirdPartyHealthTemp)(nil),         // 4: ThirdPartyHealthTemp
	(*ThirdPartyHealthGlu)(nil),          // 5: ThirdPartyHealthGlu
	(*ThirdPartyHealthBloodKetones)(nil), // 6: ThirdPartyHealthBloodKetones
	(*ThirdPartyHealthUricAcid)(nil),     // 7: ThirdPartyHealthUricAcid
	(*ThirdPartyDataHealth)(nil),         // 8: ThirdPartyDataHealth
	(*HisDataThirdParty)(nil),            // 9: HisDataThirdParty
	(*DateTime)(nil),                     // 10: DateTime
}
var file_ThirdParty_health_data_proto_depIdxs = []int32{
	10, // 0: ThirdPartyHealthBp.time:type_name -> DateTime
	0,  // 1: ThirdPartyHealthBp.MODE:type_name -> MEASURE_MODE
	10, // 2: ThirdPartyHealthScale.time:type_name -> DateTime
	10, // 3: ThirdPartyHealthSpo2.time:type_name -> DateTime
	10, // 4: ThirdPartyHealthTemp.time:type_name -> DateTime
	10, // 5: ThirdPartyHealthGlu.time:type_name -> DateTime
	10, // 6: ThirdPartyHealthBloodKetones.time:type_name -> DateTime
	10, // 7: ThirdPartyHealthUricAcid.time:type_name -> DateTime
	1,  // 8: ThirdPartyDataHealth.bp_data:type_name -> ThirdPartyHealthBp
	2,  // 9: ThirdPartyDataHealth.scale_data:type_name -> ThirdPartyHealthScale
	3,  // 10: ThirdPartyDataHealth.Spo2_data:type_name -> ThirdPartyHealthSpo2
	4,  // 11: ThirdPartyDataHealth.Temp_data:type_name -> ThirdPartyHealthTemp
	5,  // 12: ThirdPartyDataHealth.Glu_data:type_name -> ThirdPartyHealthGlu
	6,  // 13: ThirdPartyDataHealth.BloodKetones_data:type_name -> ThirdPartyHealthBloodKetones
	7,  // 14: ThirdPartyDataHealth.UricAcid_data:type_name -> ThirdPartyHealthUricAcid
	8,  // 15: HisDataThirdParty.DataHealth:type_name -> ThirdPartyDataHealth
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_ThirdParty_health_data_proto_init() }
func file_ThirdParty_health_data_proto_init() {
	if File_ThirdParty_health_data_proto != nil {
		return
	}
	file_realtime_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ThirdParty_health_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdPartyHealthBp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ThirdParty_health_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdPartyHealthScale); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ThirdParty_health_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdPartyHealthSpo2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ThirdParty_health_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdPartyHealthTemp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ThirdParty_health_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdPartyHealthGlu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ThirdParty_health_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdPartyHealthBloodKetones); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ThirdParty_health_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdPartyHealthUricAcid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ThirdParty_health_data_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdPartyDataHealth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ThirdParty_health_data_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisDataThirdParty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ThirdParty_health_data_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ThirdParty_health_data_proto_goTypes,
		DependencyIndexes: file_ThirdParty_health_data_proto_depIdxs,
		EnumInfos:         file_ThirdParty_health_data_proto_enumTypes,
		MessageInfos:      file_ThirdParty_health_data_proto_msgTypes,
	}.Build()
	File_ThirdParty_health_data_proto = out.File
	file_ThirdParty_health_data_proto_rawDesc = nil
	file_ThirdParty_health_data_proto_goTypes = nil
	file_ThirdParty_health_data_proto_depIdxs = nil
}
