// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: yyl_info.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type YylReportType int32

const (
	YylReportType_YYL_REPORT_AUTO   YylReportType = 0
	YylReportType_YYL_REPORT_MANUAL YylReportType = 1
)

// Enum value maps for YylReportType.
var (
	YylReportType_name = map[int32]string{
		0: "YYL_REPORT_AUTO",
		1: "YYL_REPORT_MANUAL",
	}
	YylReportType_value = map[string]int32{
		"YYL_REPORT_AUTO":   0,
		"YYL_REPORT_MANUAL": 1,
	}
)

func (x YylReportType) Enum() *YylReportType {
	p := new(YylReportType)
	*p = x
	return p
}

func (x YylReportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (YylReportType) Descriptor() protoreflect.EnumDescriptor {
	return file_yyl_info_proto_enumTypes[0].Descriptor()
}

func (YylReportType) Type() protoreflect.EnumType {
	return &file_yyl_info_proto_enumTypes[0]
}

func (x YylReportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *YylReportType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = YylReportType(num)
	return nil
}

// Deprecated: Use YylReportType.Descriptor instead.
func (YylReportType) EnumDescriptor() ([]byte, []int) {
	return file_yyl_info_proto_rawDescGZIP(), []int{0}
}

type YylWuqiReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wq    []byte `protobuf:"bytes,1,req,name=wq" json:"wq,omitempty"`
	Score []byte `protobuf:"bytes,2,req,name=score" json:"score,omitempty"`
}

func (x *YylWuqiReport) Reset() {
	*x = YylWuqiReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yyl_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YylWuqiReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YylWuqiReport) ProtoMessage() {}

func (x *YylWuqiReport) ProtoReflect() protoreflect.Message {
	mi := &file_yyl_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YylWuqiReport.ProtoReflect.Descriptor instead.
func (*YylWuqiReport) Descriptor() ([]byte, []int) {
	return file_yyl_info_proto_rawDescGZIP(), []int{0}
}

func (x *YylWuqiReport) GetWq() []byte {
	if x != nil {
		return x.Wq
	}
	return nil
}

func (x *YylWuqiReport) GetScore() []byte {
	if x != nil {
		return x.Score
	}
	return nil
}

type YylBodyReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TzName     []byte `protobuf:"bytes,1,req,name=tz_name,json=tzName" json:"tz_name,omitempty"`
	TzScore    []byte `protobuf:"bytes,2,req,name=tz_score,json=tzScore" json:"tz_score,omitempty"`
	PreTzName  []byte `protobuf:"bytes,3,req,name=pre_tz_name,json=preTzName" json:"pre_tz_name,omitempty"`
	PreTzScore []byte `protobuf:"bytes,4,req,name=pre_tz_score,json=preTzScore" json:"pre_tz_score,omitempty"`
}

func (x *YylBodyReport) Reset() {
	*x = YylBodyReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yyl_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YylBodyReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YylBodyReport) ProtoMessage() {}

func (x *YylBodyReport) ProtoReflect() protoreflect.Message {
	mi := &file_yyl_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YylBodyReport.ProtoReflect.Descriptor instead.
func (*YylBodyReport) Descriptor() ([]byte, []int) {
	return file_yyl_info_proto_rawDescGZIP(), []int{1}
}

func (x *YylBodyReport) GetTzName() []byte {
	if x != nil {
		return x.TzName
	}
	return nil
}

func (x *YylBodyReport) GetTzScore() []byte {
	if x != nil {
		return x.TzScore
	}
	return nil
}

func (x *YylBodyReport) GetPreTzName() []byte {
	if x != nil {
		return x.PreTzName
	}
	return nil
}

func (x *YylBodyReport) GetPreTzScore() []byte {
	if x != nil {
		return x.PreTzScore
	}
	return nil
}

type YylNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasReport  *bool          `protobuf:"varint,1,opt,name=has_report,json=hasReport" json:"has_report,omitempty"`
	ReportType *YylReportType `protobuf:"varint,2,opt,name=report_type,json=reportType,enum=YylReportType" json:"report_type,omitempty"`
}

func (x *YylNotify) Reset() {
	*x = YylNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yyl_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YylNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YylNotify) ProtoMessage() {}

func (x *YylNotify) ProtoReflect() protoreflect.Message {
	mi := &file_yyl_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YylNotify.ProtoReflect.Descriptor instead.
func (*YylNotify) Descriptor() ([]byte, []int) {
	return file_yyl_info_proto_rawDescGZIP(), []int{2}
}

func (x *YylNotify) GetHasReport() bool {
	if x != nil && x.HasReport != nil {
		return *x.HasReport
	}
	return false
}

func (x *YylNotify) GetReportType() YylReportType {
	if x != nil && x.ReportType != nil {
		return *x.ReportType
	}
	return YylReportType_YYL_REPORT_AUTO
}

type Yyl_Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modeling   *bool          `protobuf:"varint,1,opt,name=modeling" json:"modeling,omitempty"`
	WuqiReport *YylWuqiReport `protobuf:"bytes,4,opt,name=wuqi_report,json=wuqiReport" json:"wuqi_report,omitempty"`
	BodyReport *YylBodyReport `protobuf:"bytes,5,opt,name=body_report,json=bodyReport" json:"body_report,omitempty"`
}

func (x *Yyl_Command) Reset() {
	*x = Yyl_Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yyl_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Yyl_Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Yyl_Command) ProtoMessage() {}

func (x *Yyl_Command) ProtoReflect() protoreflect.Message {
	mi := &file_yyl_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Yyl_Command.ProtoReflect.Descriptor instead.
func (*Yyl_Command) Descriptor() ([]byte, []int) {
	return file_yyl_info_proto_rawDescGZIP(), []int{3}
}

func (x *Yyl_Command) GetModeling() bool {
	if x != nil && x.Modeling != nil {
		return *x.Modeling
	}
	return false
}

func (x *Yyl_Command) GetWuqiReport() *YylWuqiReport {
	if x != nil {
		return x.WuqiReport
	}
	return nil
}

func (x *Yyl_Command) GetBodyReport() *YylBodyReport {
	if x != nil {
		return x.BodyReport
	}
	return nil
}

var File_yyl_info_proto protoreflect.FileDescriptor

var file_yyl_info_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x79, 0x79, 0x6c, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x37, 0x0a, 0x0f, 0x79, 0x79, 0x6c, 0x5f, 0x77, 0x75, 0x71, 0x69, 0x5f, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x77, 0x71, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52,
	0x02, 0x77, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x0c, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x0f, 0x79, 0x79,
	0x6c, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x7a, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x06,
	0x74, 0x7a, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x7a, 0x5f, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x07, 0x74, 0x7a, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x5f, 0x74, 0x7a, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x72, 0x65, 0x54, 0x7a, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0c, 0x70, 0x72, 0x65, 0x5f, 0x74, 0x7a, 0x5f, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x54, 0x7a, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x22, 0x5e, 0x0a, 0x0a, 0x79, 0x79, 0x6c, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x73, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x61, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x31, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x79, 0x79, 0x6c, 0x5f, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x0b, 0x79, 0x79, 0x6c, 0x5f, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x69, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x69, 0x6e, 0x67, 0x12,
	0x31, 0x0a, 0x0b, 0x77, 0x75, 0x71, 0x69, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x79, 0x79, 0x6c, 0x5f, 0x77, 0x75, 0x71, 0x69, 0x5f,
	0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x0a, 0x77, 0x75, 0x71, 0x69, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x79, 0x79, 0x6c, 0x5f, 0x62, 0x6f,
	0x64, 0x79, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x0a, 0x62, 0x6f, 0x64, 0x79, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x2a, 0x3d, 0x0a, 0x0f, 0x79, 0x79, 0x6c, 0x5f, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x59, 0x59, 0x4c, 0x5f,
	0x52, 0x45, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x41, 0x55, 0x54, 0x4f, 0x10, 0x00, 0x12, 0x15, 0x0a,
	0x11, 0x59, 0x59, 0x4c, 0x5f, 0x52, 0x45, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x4d, 0x41, 0x4e, 0x55,
	0x41, 0x4c, 0x10, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x69, 0x77, 0x6f, 0x77, 0x6e,
}

var (
	file_yyl_info_proto_rawDescOnce sync.Once
	file_yyl_info_proto_rawDescData = file_yyl_info_proto_rawDesc
)

func file_yyl_info_proto_rawDescGZIP() []byte {
	file_yyl_info_proto_rawDescOnce.Do(func() {
		file_yyl_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_yyl_info_proto_rawDescData)
	})
	return file_yyl_info_proto_rawDescData
}

var file_yyl_info_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yyl_info_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_yyl_info_proto_goTypes = []interface{}{
	(YylReportType)(0),    // 0: yyl_report_type
	(*YylWuqiReport)(nil), // 1: yyl_wuqi_report
	(*YylBodyReport)(nil), // 2: yyl_body_report
	(*YylNotify)(nil),     // 3: yyl_notify
	(*Yyl_Command)(nil),   // 4: yyl_Command
}
var file_yyl_info_proto_depIdxs = []int32{
	0, // 0: yyl_notify.report_type:type_name -> yyl_report_type
	1, // 1: yyl_Command.wuqi_report:type_name -> yyl_wuqi_report
	2, // 2: yyl_Command.body_report:type_name -> yyl_body_report
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_yyl_info_proto_init() }
func file_yyl_info_proto_init() {
	if File_yyl_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yyl_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YylWuqiReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yyl_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YylBodyReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yyl_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YylNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yyl_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Yyl_Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yyl_info_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yyl_info_proto_goTypes,
		DependencyIndexes: file_yyl_info_proto_depIdxs,
		EnumInfos:         file_yyl_info_proto_enumTypes,
		MessageInfos:      file_yyl_info_proto_msgTypes,
	}.Build()
	File_yyl_info_proto = out.File
	file_yyl_info_proto_rawDesc = nil
	file_yyl_info_proto_goTypes = nil
	file_yyl_info_proto_depIdxs = nil
}
