apiVersion: v1
kind: Service
metadata:
  name: gw-mongodb-nodeport
  namespace: gw
spec:
  type: NodePort
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
    nodePort: 30217
    protocol: TCP
  selector:
    app: gw-mongodb-svc
