apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapi
  namespace: gateway
  labels:
    app: kapi
spec:
  selector:
    matchLabels:
      app: kapi
  template:
    metadata:
      labels:
        app: kapi
    spec:
      nodeSelector:
        kubernetes.io/hostname: edgexpert-1c3b
      containers:
        - name: kapi
          image: regis.pointit.co.th/infra/klynx-api-aliza-arm:0.0.1
          command: ["sleep"]
          args: ["infinity"]
          # command: ["go", "run", ".", "--env=prod"]
          # command: ["./main", "--env=prod"]
          imagePullPolicy: IfNotPresent
          # envFrom:
          #   - configMapRef:
          #       name: kapi-config
          #   - secretRef:
          #       name: kapi-secrets
          ports:
            - name: http
              containerPort: 3001
          volumeMounts:
            - name: src-code
              mountPath: /app
            - name: rootca-volume
              mountPath: /app/certs/tls.ca
              subPath: tls.ca
              readOnly: true
            - name: crimes
              mountPath: /app/crimes
              subPath: upload
              # readOnly: true
          securityContext:
            privileged: true
      volumes:
        - name: src-code
          hostPath:
            path: /home/aisom/gw
            type: Directory
        - name: crimes
          hostPath:
            path: /home/aisom/gw/data/crimes
            type: Directory
        - name: rootca-volume
          hostPath:
            path: /home/aisom/gw/certs
            type: Directory
        # - name: rootca-volume
        #   configMap:
        #     name: rootca
        #     items:
        #       - key: ca.crt
        #         path: tls.ca
---
apiVersion: v1
kind: Service
metadata:
  name: kapi
  namespace: gateway
spec:
  selector:
    app: kapi
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  generation: 1
  name: grant-kapi-to-istio
  namespace: gateway
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: istio-system
  to:
  - group: ""
    kind: Service
    name: kapi
---
apiVersion: v1
kind: Service
metadata:
  name: aisom-mongodb-external
  namespace: aisom
spec:
  type: LoadBalancer
  selector:
    app: aisom-mongodb-svc
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
